// AUTO-GENERATED by scripts/translate.mjs — NICHT von Hand bearbeiten.
// Plan 2 Task 4: stations.s01 und stations.s03 stehen hier vorübergehend auf Deutsch — Task 9 übersetzt sie.
// Manuell ergaenzt 03.09.2026 (Plan 2 Task 3): ui.bossCheckHeading/Hint + etappen.*.badge — de.js
// ist gewachsen, die volle Neuuebersetzung folgt erst in Plan 2 Task 9 (`translate.mjs --lang all`
// nach den neuen Stationen); bis dahin haelt dieser Handeintrag i18n-complete.test.js gruen.
// Source: src/i18n/de.js   sourceHash: 8edb57a86d18
// Language: ar   model: claude-opus-5   generated: 2026-09-03T04:40:08.933Z
// Stuetz-Ebene: Deutsch bleibt daneben sichtbar. Bei Aenderung an de.js neu erzeugen.

export default {
  "ui": {
    "appTitle": "عالم الكود",
    "tagline": "الوكيل (Agent) يفهم الكود فقط.",
    "home": "نظرة عامة",
    "station": "المحطة {n}",
    "ds": "الحصة المزدوجة {n}",
    "support": "بلغتك",
    "supportShow": "أظهر المساعدة بلغتك",
    "supportHide": "أخفِ المساعدة",
    "storyHeading": "القصة",
    "conceptHeading": "الفكرة",
    "bridgeGame": "في اللعبة",
    "bridgeCode": "في الكود",
    "blocksLabel": "هكذا يكون الشكل بالبلوكات",
    "pythonLabel": "هكذا يكون الشكل بـ Python",
    "tasksHeading": "مهامك في اللعبة",
    "taskAuftrag": "مهمة",
    "taskNochEiner": "مهمة أخرى",
    "taskRemix": "Remix",
    "tipsHeading": "سلّم التلميحات",
    "tipStep": "تلميح {n}",
    "tipSolution": "الحل",
    "tipRemixNote": "إذا أخذت الحل: غيّر بعده شيئًا واحدًا. هذا واجب.",
    "check": "اختبار",
    "checkHeading": "هل فهمت؟",
    "predictPrompt": "أين يقف الوكيل (Agent) في النهاية؟ اضغط على المربع.",
    "predictRight": "صحيح! الوكيل (Agent) يقف هناك بالضبط.",
    "predictWrong": "ليس بعد. اقرأ البرنامج من الأعلى إلى الأسفل. إلى أين يتوجّه وجهه؟",
    "parsonsPrompt": "رتّب الأسطر بالترتيب الصحيح.",
    "parsonsUp": "إلى الأعلى",
    "parsonsDown": "إلى الأسفل",
    "parsonsCheck": "تحقّق",
    "parsonsRight": "صحيح! هذا هو الترتيب.",
    "parsonsWrong": "ليس بعد. ما الذي يجب أن يفعله الوكيل (Agent) أولًا؟",
    "spielstandHeading": "حالة اللعب",
    "spielstandPrompt": "ماذا تستطيع الآن؟ اكتب ثلاث جمل قصيرة.",
    "spielstandSave": "حفظ",
    "spielstandSaved": "تمّ الحفظ. على هذا الجهاز فقط.",
    "progress": "زرت {done} من {total} محطات.",
    "next": "التالي",
    "prev": "السابق",
    "play": "قراءة بصوت عالٍ",
    "langLabel": "اللغة",
    "footer": "وحدة تعليمية من Dirk Schulenburg · CC BY 4.0 · ليس منتجًا رسميًا من Minecraft.",
    "bossCheckHeading": "اختبار الزعيم",
    "bossCheckHint": "نفّذ المهمة بدون سلّم التلميحات. سلّم Share-Link واكتب ثلاث جمل."
  },
  "glossary": {
    "befehl": {
      "term": "الأمر",
      "short": "سطر واحد من الكود. الـ Agent ينفّذه تمامًا."
    },
    "programm": {
      "term": "البرنامج",
      "short": "أوامر كثيرة، من الأعلى إلى الأسفل."
    },
    "sequenz": {
      "term": "التسلسل",
      "short": "ترتيب الأوامر."
    },
    "agent": {
      "term": "Agent",
      "short": "الروبوت في Minecraft. هو يفهم الكود فقط."
    },
    "zauberwort": {
      "term": "الكلمة السحرية",
      "short": "كلمة في الدردشة. هي تشغّل برنامجك."
    },
    "python": {
      "term": "Python",
      "short": "لغة برمجة. كودك يكون نصًّا."
    },
    "bloecke": {
      "term": "البلوكات",
      "short": "كودك على شكل قطع تسحبها."
    },
    "fehler": {
      "term": "الخطأ",
      "short": "الـ Agent فهمك بشكل خاطئ. يمكنك إصلاح ذلك."
    }
  },
  "etappen": {
    "holz": {
      "name": "خشب",
      "badge": {
        "name": "خشب",
        "description": "أكملت كل اختبارات مرحلة خشب وسلّمت اختبار الزعيم."
      }
    },
    "stein": {
      "name": "حجر",
      "badge": {
        "name": "حجر",
        "description": "أكملت كل اختبارات مرحلة حجر وسلّمت اختبار الزعيم."
      }
    },
    "eisen": {
      "name": "حديد",
      "badge": {
        "name": "حديد",
        "description": "أكملت كل اختبارات مرحلة حديد وسلّمت اختبار الزعيم."
      }
    },
    "gold": {
      "name": "ذهب",
      "badge": {
        "name": "ذهب",
        "description": "أكملت كل اختبارات مرحلة ذهب وسلّمت اختبار الزعيم."
      }
    },
    "diamant": {
      "name": "ألماس",
      "badge": {
        "name": "ألماس",
        "description": "أكملت كل اختبارات مرحلة ألماس وسلّمت اختبار الزعيم."
      }
    },
    "netherite": {
      "name": "نيذرايت",
      "badge": {
        "name": "نيذرايت",
        "description": "أكملت كل اختبارات مرحلة نيذرايت وسلّمت اختبار الزعيم."
      }
    },
    "enderdrache": {
      "name": "تنين الإندر",
      "badge": {
        "name": "تنين الإندر",
        "description": "أكملت كل اختبارات مرحلة تنين الإندر وسلّمت اختبار الزعيم."
      }
    }
  },
  "stations": {
    "s01": {
      "title": "Die neue Welt",
      "storyShort": "Der Agent ist dein Roboter in Minecraft. Er versteht kein Deutsch, nur Code. Er startet erst, wenn du ein Zauberwort in den Chat schreibst.",
      "bridge": {
        "game": "Du tippst hi in den Chat. Der Agent kommt zu dir und geht einen Schritt.",
        "code": "Ein Befehl ist eine Zeile Code. Das Zauberwort startet das ganze Programm."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Sag hi",
          "text": "Schreibe hi in den Chat. Der Agent kommt zu dir. Dann geht er einen Schritt vor."
        },
        {
          "kind": "nochEiner",
          "title": "Dein Wort",
          "text": "Ändere das Zauberwort von hi zu hallo. Ändere die Schritte von 1 auf 3. Probier es aus."
        },
        {
          "kind": "remix",
          "title": "Noch ein Wort",
          "text": "Erfinde ein zweites Zauberwort. Der Agent soll damit etwas anderes machen. Zeig es deinem Partner oder deiner Partnerin."
        }
      ],
      "tipSolution": "Schreibe agent.teleport_to_player() und darunter agent.move(FORWARD, 3). In der letzten Zeile ersetzt du hi durch hallo. Dann tippst du hallo in den Chat.",
      "exercises": [
        {
          "prompt": "Der Agent steht unten in der Mitte. Seine Nase zeigt nach oben. Das Programm: 1 Schritt vor."
        },
        {
          "prompt": "Der Agent soll zu dir kommen und einen Schritt gehen. Die Zeile mit dem Zauberwort kommt zum Schluss."
        }
      ],
      "quiz": [
        {
          "q": "Wozu ist das Zauberwort da?",
          "answers": [
            {
              "text": "Es startet dein Programm",
              "correct": true
            },
            {
              "text": "Es öffnet den Code Builder",
              "correct": false
            },
            {
              "text": "Es speichert dein Programm",
              "correct": false
            }
          ]
        },
        {
          "q": "Welche Taste öffnet den Code Builder?",
          "answers": [
            {
              "text": "Die Taste C",
              "correct": true
            },
            {
              "text": "Die Taste E",
              "correct": false
            },
            {
              "text": "Die Taste T",
              "correct": false
            }
          ]
        },
        {
          "q": "Was macht agent.teleport_to_player()?",
          "answers": [
            {
              "text": "Der Agent kommt zu dir",
              "correct": true
            },
            {
              "text": "Der Agent geht einen Schritt vor",
              "correct": false
            },
            {
              "text": "Der Agent legt einen Block",
              "correct": false
            }
          ]
        },
        {
          "q": "Der Agent versteht …",
          "answers": [
            {
              "text": "nur Code",
              "correct": true
            },
            {
              "text": "jedes Wort im Chat",
              "correct": false
            },
            {
              "text": "Deutsch, wenn du langsam schreibst",
              "correct": false
            }
          ]
        }
      ]
    },
    "s02": {
      "title": "الترتيب مهم",
      "storyShort": "ينفّذ Agent الأوامر بالترتيب نفسه الذي تكتبه به. أن تمشي أولًا ثم تستدير ليس مثل أن تستدير أولًا ثم تمشي.",
      "bridge": {
        "game": "يمشي Agent خطوة خطوة ويضع كتلًا خلفه.",
        "code": "البرنامج قائمة من الأوامر. ينفّذها الحاسوب من الأعلى إلى الأسفل."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "الطريق",
          "text": "اكتب الكلمة السحرية weg في الدردشة. يضع Agent ثلاث كتل. انظر جيدًا: أين الزاوية؟"
        },
        {
          "kind": "nochEiner",
          "title": "أطول",
          "text": "غيّر البرنامج. يجب أن يضع Agent خمس كتل، ثم يدور عند الزاوية، ثم يضع كتلتين أخريين."
        },
        {
          "kind": "remix",
          "title": "نمطك الخاص",
          "text": "ابنِ نمطًا خاصًا بك من الكتل. مثلًا حرف Z أو حرف U. اعرضه على زميلك أو زميلتك."
        }
      ],
      "tipSolution": "لخمس كتل: اكتب agent.move(FORWARD, 1) و agent.place(BACK) خمس مرات. ثم agent.turn(LEFT_TURN). ثم move و place مرتين أخريين.",
      "exercises": [
        {
          "prompt": "يقف Agent في الأسفل في الوسط. وجهه نحو الأعلى. البرنامج: خطوتان إلى الأمام، دوران إلى اليسار، خطوة واحدة إلى الأمام."
        },
        {
          "prompt": "يجب أن يأتي Agent إليك: يمشي خطوتين، يدور إلى اليسار، ثم يمشي خطوة أخرى."
        }
      ],
      "quiz": [
        {
          "q": "يجب أن يمشي Agent ٣ خطوات ثم يدور إلى اليسار. أي ترتيب صحيح؟",
          "answers": [
            {
              "text": "أولًا agent.move(FORWARD, 3)، ثم agent.turn(LEFT_TURN)",
              "correct": true
            },
            {
              "text": "أولًا agent.turn(LEFT_TURN)، ثم agent.move(FORWARD, 3)",
              "correct": false
            },
            {
              "text": "الترتيب لا يهم",
              "correct": false
            }
          ]
        },
        {
          "q": "تكتب agent.move(FORWARD, 3) مرتين واحدة تحت الأخرى. ماذا يفعل Agent؟",
          "answers": [
            {
              "text": "يمشي ٦ خطوات",
              "correct": true
            },
            {
              "text": "يمشي ٣ خطوات",
              "correct": false
            },
            {
              "text": "يظهر رسالة خطأ",
              "correct": false
            }
          ]
        },
        {
          "q": "متى يبدأ برنامجك؟",
          "answers": [
            {
              "text": "عندما تكتب الكلمة السحرية في الدردشة",
              "correct": true
            },
            {
              "text": "فورًا عندما تفتح Code Builder",
              "correct": false
            },
            {
              "text": "عندما تنقر على Agent",
              "correct": false
            }
          ]
        },
        {
          "q": "يفهم Agent …",
          "answers": [
            {
              "text": "الكود فقط",
              "correct": true
            },
            {
              "text": "الألمانية والإنجليزية",
              "correct": false
            },
            {
              "text": "كل اللغات",
              "correct": false
            }
          ]
        }
      ]
    },
    "s03": {
      "title": "Zauberwörter",
      "storyShort": "Ein Wort im Chat ist ein Ereignis. Jedes Zauberwort startet sein eigenes Programm. Du kannst mehrere Zauberwörter haben.",
      "bridge": {
        "game": "Du tippst weg oder turm in den Chat. Der Agent baut das, was zu dem Wort gehört.",
        "code": "Jedes Zauberwort hat einen eigenen Hut-Block. Darunter steht sein eigenes Programm."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Zwei Wörter",
          "text": "Schreibe weg in den Chat. Dann schreibe turm. Schau dir beide Bauten genau an."
        },
        {
          "kind": "nochEiner",
          "title": "Höher",
          "text": "Ändere das Programm für turm. Der Turm soll fünf Blöcke hoch werden."
        },
        {
          "kind": "remix",
          "title": "Die Brücke",
          "text": "Erfinde ein drittes Zauberwort: brücke. Der Agent baut damit einen Weg über eine Lücke."
        }
      ],
      "tipSolution": "Für fünf Blöcke schreibst du agent.place(FORWARD) und agent.move(UP, 1) abwechselnd. Am Ende kommt noch einmal agent.place(FORWARD). Zähle nach: fünf Zeilen mit place.",
      "exercises": [
        {
          "prompt": "Der Agent steht unten links. Seine Nase zeigt nach oben. Das Programm: 2 Schritte vor, rechts drehen, 2 Schritte vor."
        },
        {
          "prompt": "Der Agent kommt zu dir. Er nimmt Gras. Er geht einen Schritt und legt einen Block. Die Zeile mit dem Zauberwort kommt zum Schluss."
        }
      ],
      "quiz": [
        {
          "q": "Was ist ein Ereignis?",
          "answers": [
            {
              "text": "Etwas passiert im Spiel, zum Beispiel ein Wort im Chat",
              "correct": true
            },
            {
              "text": "Ein Fehler in deinem Programm",
              "correct": false
            },
            {
              "text": "Ein Block, den der Agent legt",
              "correct": false
            }
          ]
        },
        {
          "q": "Du hast zwei Zauberwörter. Wie viele Programme sind das?",
          "answers": [
            {
              "text": "Zwei. Jedes Wort hat sein eigenes Programm",
              "correct": true
            },
            {
              "text": "Eins. Beide Wörter starten dasselbe Programm",
              "correct": false
            },
            {
              "text": "Keins. Zwei Zauberwörter gehen nicht",
              "correct": false
            }
          ]
        },
        {
          "q": "Was macht agent.move(UP, 1)?",
          "answers": [
            {
              "text": "Der Agent geht einen Block nach oben",
              "correct": true
            },
            {
              "text": "Der Agent geht einen Schritt nach vorne",
              "correct": false
            },
            {
              "text": "Der Agent legt einen Block über sich",
              "correct": false
            }
          ]
        },
        {
          "q": "Du tippst erst weg, dann turm. Was passiert?",
          "answers": [
            {
              "text": "Erst läuft das Programm für weg, dann das für turm",
              "correct": true
            },
            {
              "text": "Beide Programme laufen gleichzeitig",
              "correct": false
            },
            {
              "text": "Nur das Programm für turm läuft",
              "correct": false
            }
          ]
        }
      ],
      "bossCheck": {
        "title": "Boss-Check Holz: Das L",
        "task": "Der Agent legt ein L aus Blöcken: 4 Blöcke geradeaus, dann Ecke, dann 2 Blöcke. Ohne Tipp-Leiter. Gib den Share-Link ab und schreibe drei Sätze: Was macht dein Programm? Warum ist die Reihenfolge wichtig? Was war schwer?"
      }
    }
  }
};
