// AUTO-GENERATED by scripts/translate.mjs — NICHT von Hand bearbeiten.
// Source: src/i18n/de.js   sourceHash: 8edb57a86d18
// Language: ar   model: claude-opus-5   generated: 2026-09-03T04:40:08.933Z
// Stuetz-Ebene: Deutsch bleibt daneben sichtbar. Bei Aenderung an de.js neu erzeugen.

export default {
  "ui": {
    "appTitle": "عالم الكود",
    "tagline": "الوكيل (Agent) يفهم الكود فقط.",
    "home": "نظرة عامة",
    "station": "المحطة {n}",
    "ds": "الحصة المزدوجة {n}",
    "support": "بلغتك",
    "supportShow": "أظهر المساعدة بلغتك",
    "supportHide": "أخفِ المساعدة",
    "storyHeading": "القصة",
    "conceptHeading": "الفكرة",
    "bridgeGame": "في اللعبة",
    "bridgeCode": "في الكود",
    "blocksLabel": "هكذا يكون الشكل بالبلوكات",
    "pythonLabel": "هكذا يكون الشكل بـ Python",
    "tasksHeading": "مهامك في اللعبة",
    "taskAuftrag": "مهمة",
    "taskNochEiner": "مهمة أخرى",
    "taskRemix": "Remix",
    "tipsHeading": "سلّم التلميحات",
    "tipStep": "تلميح {n}",
    "tipSolution": "الحل",
    "tipRemixNote": "إذا أخذت الحل: غيّر بعده شيئًا واحدًا. هذا واجب.",
    "check": "اختبار",
    "checkHeading": "هل فهمت؟",
    "predictPrompt": "أين يقف الوكيل (Agent) في النهاية؟ اضغط على المربع.",
    "predictRight": "صحيح! الوكيل (Agent) يقف هناك بالضبط.",
    "predictWrong": "ليس بعد. اقرأ البرنامج من الأعلى إلى الأسفل. إلى أين يتوجّه وجهه؟",
    "parsonsPrompt": "رتّب الأسطر بالترتيب الصحيح.",
    "parsonsUp": "إلى الأعلى",
    "parsonsDown": "إلى الأسفل",
    "parsonsCheck": "تحقّق",
    "parsonsRight": "صحيح! هذا هو الترتيب.",
    "parsonsWrong": "ليس بعد. ما الذي يجب أن يفعله الوكيل (Agent) أولًا؟",
    "spielstandHeading": "حالة اللعب",
    "spielstandPrompt": "ماذا تستطيع الآن؟ اكتب ثلاث جمل قصيرة.",
    "spielstandSave": "حفظ",
    "spielstandSaved": "تمّ الحفظ. على هذا الجهاز فقط.",
    "progress": "زرت {done} من {total} محطات.",
    "next": "التالي",
    "prev": "السابق",
    "play": "قراءة بصوت عالٍ",
    "langLabel": "اللغة",
    "footer": "وحدة تعليمية من Dirk Schulenburg · CC BY 4.0 · ليس منتجًا رسميًا من Minecraft."
  },
  "glossary": {
    "befehl": {
      "term": "الأمر",
      "short": "سطر واحد من الكود. الـ Agent ينفّذه تمامًا."
    },
    "programm": {
      "term": "البرنامج",
      "short": "أوامر كثيرة، من الأعلى إلى الأسفل."
    },
    "sequenz": {
      "term": "التسلسل",
      "short": "ترتيب الأوامر."
    },
    "agent": {
      "term": "Agent",
      "short": "الروبوت في Minecraft. هو يفهم الكود فقط."
    },
    "zauberwort": {
      "term": "الكلمة السحرية",
      "short": "كلمة في الدردشة. هي تشغّل برنامجك."
    },
    "python": {
      "term": "Python",
      "short": "لغة برمجة. كودك يكون نصًّا."
    },
    "bloecke": {
      "term": "البلوكات",
      "short": "كودك على شكل قطع تسحبها."
    },
    "fehler": {
      "term": "الخطأ",
      "short": "الـ Agent فهمك بشكل خاطئ. يمكنك إصلاح ذلك."
    }
  },
  "etappen": {
    "holz": {
      "name": "خشب"
    },
    "stein": {
      "name": "حجر"
    },
    "eisen": {
      "name": "حديد"
    },
    "gold": {
      "name": "ذهب"
    },
    "diamant": {
      "name": "ألماس"
    },
    "netherite": {
      "name": "نيذرايت"
    },
    "enderdrache": {
      "name": "تنين الإندر"
    }
  },
  "stations": {
    "s02": {
      "title": "الترتيب مهم",
      "storyShort": "ينفّذ Agent الأوامر بالترتيب نفسه الذي تكتبه به. أن تمشي أولًا ثم تستدير ليس مثل أن تستدير أولًا ثم تمشي.",
      "bridge": {
        "game": "يمشي Agent خطوة خطوة ويضع كتلًا خلفه.",
        "code": "البرنامج قائمة من الأوامر. ينفّذها الحاسوب من الأعلى إلى الأسفل."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "الطريق",
          "text": "اكتب الكلمة السحرية weg في الدردشة. يضع Agent ثلاث كتل. انظر جيدًا: أين الزاوية؟"
        },
        {
          "kind": "nochEiner",
          "title": "أطول",
          "text": "غيّر البرنامج. يجب أن يضع Agent خمس كتل، ثم يدور عند الزاوية، ثم يضع كتلتين أخريين."
        },
        {
          "kind": "remix",
          "title": "نمطك الخاص",
          "text": "ابنِ نمطًا خاصًا بك من الكتل. مثلًا حرف Z أو حرف U. اعرضه على زميلك أو زميلتك."
        }
      ],
      "tipSolution": "لخمس كتل: اكتب agent.move(FORWARD, 1) و agent.place(BACK) خمس مرات. ثم agent.turn(LEFT_TURN). ثم move و place مرتين أخريين.",
      "exercises": [
        {
          "prompt": "يقف Agent في الأسفل في الوسط. وجهه نحو الأعلى. البرنامج: خطوتان إلى الأمام، دوران إلى اليسار، خطوة واحدة إلى الأمام."
        },
        {
          "prompt": "يجب أن يأتي Agent إليك: يمشي خطوتين، يدور إلى اليسار، ثم يمشي خطوة أخرى."
        }
      ],
      "quiz": [
        {
          "q": "يجب أن يمشي Agent ٣ خطوات ثم يدور إلى اليسار. أي ترتيب صحيح؟",
          "answers": [
            {
              "text": "أولًا agent.move(FORWARD, 3)، ثم agent.turn(LEFT_TURN)",
              "correct": true
            },
            {
              "text": "أولًا agent.turn(LEFT_TURN)، ثم agent.move(FORWARD, 3)",
              "correct": false
            },
            {
              "text": "الترتيب لا يهم",
              "correct": false
            }
          ]
        },
        {
          "q": "تكتب agent.move(FORWARD, 3) مرتين واحدة تحت الأخرى. ماذا يفعل Agent؟",
          "answers": [
            {
              "text": "يمشي ٦ خطوات",
              "correct": true
            },
            {
              "text": "يمشي ٣ خطوات",
              "correct": false
            },
            {
              "text": "يظهر رسالة خطأ",
              "correct": false
            }
          ]
        },
        {
          "q": "متى يبدأ برنامجك؟",
          "answers": [
            {
              "text": "عندما تكتب الكلمة السحرية في الدردشة",
              "correct": true
            },
            {
              "text": "فورًا عندما تفتح Code Builder",
              "correct": false
            },
            {
              "text": "عندما تنقر على Agent",
              "correct": false
            }
          ]
        },
        {
          "q": "يفهم Agent …",
          "answers": [
            {
              "text": "الكود فقط",
              "correct": true
            },
            {
              "text": "الألمانية والإنجليزية",
              "correct": false
            },
            {
              "text": "كل اللغات",
              "correct": false
            }
          ]
        }
      ]
    }
  }
};
