// AUTO-GENERATED by scripts/translate.mjs — NICHT von Hand bearbeiten.
// Plan 2 Task 4/5: stations.s01 und stations.s03–s06 stehen hier vorübergehend auf Deutsch — Task 9 übersetzt sie.
// Manuell ergaenzt 03.09.2026 (Plan 2 Task 3): ui.bossCheckHeading/Hint + etappen.*.badge — de.js
// ist gewachsen, die volle Neuuebersetzung folgt erst in Plan 2 Task 9 (`translate.mjs --lang all`
// nach den neuen Stationen); bis dahin haelt dieser Handeintrag i18n-complete.test.js gruen.
// Source: src/i18n/de.js   sourceHash: 8edb57a86d18
// Language: ar   model: claude-opus-5   generated: 2026-09-03T04:40:08.933Z
// Stuetz-Ebene: Deutsch bleibt daneben sichtbar. Bei Aenderung an de.js neu erzeugen.

export default {
  "ui": {
    "appTitle": "عالم الكود",
    "tagline": "الوكيل (Agent) يفهم الكود فقط.",
    "home": "نظرة عامة",
    "station": "المحطة {n}",
    "ds": "الحصة المزدوجة {n}",
    "support": "بلغتك",
    "supportShow": "أظهر المساعدة بلغتك",
    "supportHide": "أخفِ المساعدة",
    "storyHeading": "القصة",
    "conceptHeading": "الفكرة",
    "bridgeGame": "في اللعبة",
    "bridgeCode": "في الكود",
    "blocksLabel": "هكذا يكون الشكل بالبلوكات",
    "pythonLabel": "هكذا يكون الشكل بـ Python",
    "tasksHeading": "مهامك في اللعبة",
    "taskAuftrag": "مهمة",
    "taskNochEiner": "مهمة أخرى",
    "taskRemix": "Remix",
    "tipsHeading": "سلّم التلميحات",
    "tipStep": "تلميح {n}",
    "tipSolution": "الحل",
    "tipRemixNote": "إذا أخذت الحل: غيّر بعده شيئًا واحدًا. هذا واجب.",
    "check": "اختبار",
    "checkHeading": "هل فهمت؟",
    "predictPrompt": "أين يقف الوكيل (Agent) في النهاية؟ اضغط على المربع.",
    "predictRight": "صحيح! الوكيل (Agent) يقف هناك بالضبط.",
    "predictWrong": "ليس بعد. اقرأ البرنامج من الأعلى إلى الأسفل. إلى أين يتوجّه وجهه؟",
    "parsonsPrompt": "رتّب الأسطر بالترتيب الصحيح.",
    "parsonsUp": "إلى الأعلى",
    "parsonsDown": "إلى الأسفل",
    "parsonsCheck": "تحقّق",
    "parsonsRight": "صحيح! هذا هو الترتيب.",
    "parsonsWrong": "ليس بعد. ما الذي يجب أن يفعله الوكيل (Agent) أولًا؟",
    "spielstandHeading": "حالة اللعب",
    "spielstandPrompt": "ماذا تستطيع الآن؟ اكتب ثلاث جمل قصيرة.",
    "spielstandSave": "حفظ",
    "spielstandSaved": "تمّ الحفظ. على هذا الجهاز فقط.",
    "progress": "زرت {done} من {total} محطات.",
    "next": "التالي",
    "prev": "السابق",
    "play": "قراءة بصوت عالٍ",
    "langLabel": "اللغة",
    "footer": "وحدة تعليمية من Dirk Schulenburg · CC BY 4.0 · ليس منتجًا رسميًا من Minecraft.",
    "bossCheckHeading": "اختبار الزعيم",
    "bossCheckHint": "نفّذ المهمة بدون سلّم التلميحات. سلّم Share-Link واكتب ثلاث جمل."
  },
  "glossary": {
    "befehl": {
      "term": "الأمر",
      "short": "سطر واحد من الكود. الـ Agent ينفّذه تمامًا."
    },
    "programm": {
      "term": "البرنامج",
      "short": "أوامر كثيرة، من الأعلى إلى الأسفل."
    },
    "sequenz": {
      "term": "التسلسل",
      "short": "ترتيب الأوامر."
    },
    "agent": {
      "term": "Agent",
      "short": "الروبوت في Minecraft. هو يفهم الكود فقط."
    },
    "zauberwort": {
      "term": "الكلمة السحرية",
      "short": "كلمة في الدردشة. هي تشغّل برنامجك."
    },
    "python": {
      "term": "Python",
      "short": "لغة برمجة. كودك يكون نصًّا."
    },
    "bloecke": {
      "term": "البلوكات",
      "short": "كودك على شكل قطع تسحبها."
    },
    "fehler": {
      "term": "الخطأ",
      "short": "الـ Agent فهمك بشكل خاطئ. يمكنك إصلاح ذلك."
    }
  },
  "etappen": {
    "holz": {
      "name": "خشب",
      "badge": {
        "name": "خشب",
        "description": "أكملت كل اختبارات مرحلة خشب وسلّمت اختبار الزعيم."
      }
    },
    "stein": {
      "name": "حجر",
      "badge": {
        "name": "حجر",
        "description": "أكملت كل اختبارات مرحلة حجر وسلّمت اختبار الزعيم."
      }
    },
    "eisen": {
      "name": "حديد",
      "badge": {
        "name": "حديد",
        "description": "أكملت كل اختبارات مرحلة حديد وسلّمت اختبار الزعيم."
      }
    },
    "gold": {
      "name": "ذهب",
      "badge": {
        "name": "ذهب",
        "description": "أكملت كل اختبارات مرحلة ذهب وسلّمت اختبار الزعيم."
      }
    },
    "diamant": {
      "name": "ألماس",
      "badge": {
        "name": "ألماس",
        "description": "أكملت كل اختبارات مرحلة ألماس وسلّمت اختبار الزعيم."
      }
    },
    "netherite": {
      "name": "نيذرايت",
      "badge": {
        "name": "نيذرايت",
        "description": "أكملت كل اختبارات مرحلة نيذرايت وسلّمت اختبار الزعيم."
      }
    },
    "enderdrache": {
      "name": "تنين الإندر",
      "badge": {
        "name": "تنين الإندر",
        "description": "أكملت كل اختبارات مرحلة تنين الإندر وسلّمت اختبار الزعيم."
      }
    }
  },
  "stations": {
    "s01": {
      "title": "Die neue Welt",
      "storyShort": "Der Agent ist dein Roboter in Minecraft. Er versteht kein Deutsch, nur Code. Er startet erst, wenn du ein Zauberwort in den Chat schreibst.",
      "bridge": {
        "game": "Du tippst hi in den Chat. Der Agent kommt zu dir und geht einen Schritt.",
        "code": "Ein Befehl ist eine Zeile Code. Das Zauberwort startet das ganze Programm."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Sag hi",
          "text": "Schreibe hi in den Chat. Der Agent kommt zu dir. Dann geht er einen Schritt vor."
        },
        {
          "kind": "nochEiner",
          "title": "Dein Wort",
          "text": "Ändere das Zauberwort von hi zu hallo. Ändere die Schritte von 1 auf 3. Probier es aus."
        },
        {
          "kind": "remix",
          "title": "Noch ein Wort",
          "text": "Erfinde ein zweites Zauberwort. Der Agent soll damit etwas anderes machen. Zeig es deinem Partner oder deiner Partnerin."
        }
      ],
      "tipSolution": "Schreibe agent.teleport_to_player() und darunter agent.move(FORWARD, 3). In der letzten Zeile ersetzt du \"hi\" durch \"hallo\". Nur das Wort in den Anführungszeichen. Dann tippst du hallo in den Chat.",
      "exercises": [
        {
          "prompt": "Der Agent steht unten in der Mitte. Seine Nase zeigt nach oben. Das Programm: 1 Schritt vor."
        },
        {
          "prompt": "Der Agent soll zu dir kommen und einen Schritt gehen. Die Zeile mit dem Zauberwort kommt zum Schluss."
        }
      ],
      "quiz": [
        {
          "q": "Wozu ist das Zauberwort da?",
          "answers": [
            {
              "text": "Es startet dein Programm",
              "correct": true
            },
            {
              "text": "Es öffnet den Code Builder",
              "correct": false
            },
            {
              "text": "Es speichert dein Programm",
              "correct": false
            }
          ]
        },
        {
          "q": "Welche Taste öffnet den Code Builder?",
          "answers": [
            {
              "text": "Die Taste C",
              "correct": true
            },
            {
              "text": "Die Taste E",
              "correct": false
            },
            {
              "text": "Die Taste T",
              "correct": false
            }
          ]
        },
        {
          "q": "Was macht agent.teleport_to_player()?",
          "answers": [
            {
              "text": "Der Agent kommt zu dir",
              "correct": true
            },
            {
              "text": "Der Agent geht einen Schritt vor",
              "correct": false
            },
            {
              "text": "Der Agent legt einen Block",
              "correct": false
            }
          ]
        },
        {
          "q": "Der Agent versteht …",
          "answers": [
            {
              "text": "nur Code",
              "correct": true
            },
            {
              "text": "jedes Wort im Chat",
              "correct": false
            },
            {
              "text": "Deutsch, wenn du langsam schreibst",
              "correct": false
            }
          ]
        }
      ]
    },
    "s02": {
      "title": "الترتيب مهم",
      "storyShort": "ينفّذ Agent الأوامر بالترتيب نفسه الذي تكتبه به. أن تمشي أولًا ثم تستدير ليس مثل أن تستدير أولًا ثم تمشي.",
      "bridge": {
        "game": "يمشي Agent خطوة خطوة ويضع كتلًا خلفه.",
        "code": "البرنامج قائمة من الأوامر. ينفّذها الحاسوب من الأعلى إلى الأسفل."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "الطريق",
          "text": "اكتب الكلمة السحرية weg في الدردشة. يضع Agent ثلاث كتل. انظر جيدًا: أين الزاوية؟"
        },
        {
          "kind": "nochEiner",
          "title": "أطول",
          "text": "غيّر البرنامج. يجب أن يضع Agent خمس كتل، ثم يدور عند الزاوية، ثم يضع كتلتين أخريين."
        },
        {
          "kind": "remix",
          "title": "نمطك الخاص",
          "text": "ابنِ نمطًا خاصًا بك من الكتل. مثلًا حرف Z أو حرف U. اعرضه على زميلك أو زميلتك."
        }
      ],
      "tipSolution": "لخمس كتل: اكتب agent.move(FORWARD, 1) و agent.place(BACK) خمس مرات. ثم agent.turn(LEFT_TURN). ثم move و place مرتين أخريين.",
      "exercises": [
        {
          "prompt": "يقف Agent في الأسفل في الوسط. وجهه نحو الأعلى. البرنامج: خطوتان إلى الأمام، دوران إلى اليسار، خطوة واحدة إلى الأمام."
        },
        {
          "prompt": "يجب أن يأتي Agent إليك: يمشي خطوتين، يدور إلى اليسار، ثم يمشي خطوة أخرى."
        }
      ],
      "quiz": [
        {
          "q": "يجب أن يمشي Agent ٣ خطوات ثم يدور إلى اليسار. أي ترتيب صحيح؟",
          "answers": [
            {
              "text": "أولًا agent.move(FORWARD, 3)، ثم agent.turn(LEFT_TURN)",
              "correct": true
            },
            {
              "text": "أولًا agent.turn(LEFT_TURN)، ثم agent.move(FORWARD, 3)",
              "correct": false
            },
            {
              "text": "الترتيب لا يهم",
              "correct": false
            }
          ]
        },
        {
          "q": "تكتب agent.move(FORWARD, 3) مرتين واحدة تحت الأخرى. ماذا يفعل Agent؟",
          "answers": [
            {
              "text": "يمشي ٦ خطوات",
              "correct": true
            },
            {
              "text": "يمشي ٣ خطوات",
              "correct": false
            },
            {
              "text": "يظهر رسالة خطأ",
              "correct": false
            }
          ]
        },
        {
          "q": "متى يبدأ برنامجك؟",
          "answers": [
            {
              "text": "عندما تكتب الكلمة السحرية في الدردشة",
              "correct": true
            },
            {
              "text": "فورًا عندما تفتح Code Builder",
              "correct": false
            },
            {
              "text": "عندما تنقر على Agent",
              "correct": false
            }
          ]
        },
        {
          "q": "يفهم Agent …",
          "answers": [
            {
              "text": "الكود فقط",
              "correct": true
            },
            {
              "text": "الألمانية والإنجليزية",
              "correct": false
            },
            {
              "text": "كل اللغات",
              "correct": false
            }
          ]
        }
      ]
    },
    "s03": {
      "title": "Zauberwörter",
      "storyShort": "Ein Wort im Chat ist ein Ereignis. Jedes Zauberwort startet sein eigenes Programm. Du kannst mehrere Zauberwörter haben.",
      "bridge": {
        "game": "Du tippst weg oder turm in den Chat. Der Agent baut den Weg oder den Turm.",
        "code": "Jedes Zauberwort hat einen eigenen Hut-Block. Darunter steht sein eigenes Programm."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Zwei Wörter",
          "text": "Schreibe weg in den Chat. Dann schreibe turm. Der Weg ist hier kürzer als in Station 2. Schau dir beides genau an."
        },
        {
          "kind": "nochEiner",
          "title": "Höher",
          "text": "Ändere das Programm für turm. Der Turm soll fünf Blöcke hoch werden."
        },
        {
          "kind": "remix",
          "title": "Die Brücke",
          "text": "Erfinde ein drittes Zauberwort: brücke. Der Agent baut damit einen Weg über eine Lücke."
        }
      ],
      "tipSolution": "Für fünf Blöcke schreibst du agent.place(FORWARD) und agent.move(UP, 1) abwechselnd. Am Ende kommt noch einmal agent.place(FORWARD). Zähle nach: fünf Zeilen mit place.",
      "exercises": [
        {
          "prompt": "Der Agent steht unten links. Seine Nase zeigt nach oben. Das Programm: 2 Schritte vor, rechts drehen, 2 Schritte vor."
        },
        {
          "prompt": "Der Agent kommt zu dir. Er nimmt Gras. Er geht einen Schritt und legt einen Block. Die Zeile mit dem Zauberwort kommt zum Schluss."
        }
      ],
      "quiz": [
        {
          "q": "Was ist ein Ereignis?",
          "answers": [
            {
              "text": "Etwas passiert im Spiel, zum Beispiel ein Wort im Chat",
              "correct": true
            },
            {
              "text": "Ein Fehler in deinem Programm",
              "correct": false
            },
            {
              "text": "Ein Block, den der Agent legt",
              "correct": false
            }
          ]
        },
        {
          "q": "Du hast zwei Zauberwörter. Wie viele Programme sind das?",
          "answers": [
            {
              "text": "Zwei. Jedes Wort hat sein eigenes Programm",
              "correct": true
            },
            {
              "text": "Eins. Beide Wörter starten dasselbe Programm",
              "correct": false
            },
            {
              "text": "Keins. Zwei Zauberwörter gehen nicht",
              "correct": false
            }
          ]
        },
        {
          "q": "Was macht agent.move(UP, 1)?",
          "answers": [
            {
              "text": "Der Agent geht einen Block nach oben",
              "correct": true
            },
            {
              "text": "Der Agent geht einen Schritt nach vorne",
              "correct": false
            },
            {
              "text": "Der Agent legt einen Block über sich",
              "correct": false
            }
          ]
        },
        {
          "q": "Du tippst erst weg, dann turm. Was passiert?",
          "answers": [
            {
              "text": "Erst läuft das Programm für weg, dann das für turm",
              "correct": true
            },
            {
              "text": "Beide Programme laufen gleichzeitig",
              "correct": false
            },
            {
              "text": "Nur das Programm für turm läuft",
              "correct": false
            }
          ]
        }
      ],
      "bossCheck": {
        "title": "Boss-Check Holz: Das L",
        "task": "Der Agent legt ein L: erst 4 Blöcke geradeaus, dann 2 um die Ecke. Was macht dein Programm? Warum ist die Reihenfolge wichtig? Was war schwer?"
      }
    },
    "s04": {
      "title": "Wiederholen",
      "storyShort": "Zehnmal dasselbe zu schreiben ist mühsam. Dafür gibt es die Schleife. Du schreibst die Zeilen einmal. Der Computer wiederholt sie für dich.",
      "bridge": {
        "game": "Du tippst mauer in den Chat. Der Agent legt zehn Blöcke in einer Reihe.",
        "code": "Eine Schleife wiederholt zwei Zeilen zehnmal. Du schreibst sie nur einmal."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Die Mauer",
          "text": "Schreibe mauer in den Chat. Der Agent baut eine Mauer aus zehn Blöcken. Zähle die Blöcke nach."
        },
        {
          "kind": "nochEiner",
          "title": "Länger und anders",
          "text": "Ändere die Zahl von 10 auf 20. Nimm eine andere Blockart, zum Beispiel Holz. Probier es aus."
        },
        {
          "kind": "remix",
          "title": "Zwei Mauern",
          "text": "Baue zwei Mauern mit einer Lücke dazwischen. Zeig es deinem Partner oder deiner Partnerin."
        }
      ],
      "tipSolution": "Schreibe for index in range(20): in die Schleifenzeile. Die zwei Zeilen darunter bleiben eingerückt. Für Holz nimmst du agent.set_item(PLANKS_OAK, 64, 1). Zähle nach: eine Schleife, zwei Zeilen im Bauch.",
      "exercises": [
        {
          "prompt": "Der Agent steht unten in der Mitte. Seine Nase zeigt nach oben. Das Programm: 3 Schritte vor."
        },
        {
          "prompt": "Der Agent kommt zu dir und nimmt Bruchstein. Dann wiederholt die Schleife zwei Zeilen. Die Einrückung gehört zur Zeile."
        }
      ],
      "quiz": [
        {
          "q": "Was spart die Schleife?",
          "answers": [
            {
              "text": "Viele gleiche Zeilen",
              "correct": true
            },
            {
              "text": "Blöcke im Rucksack",
              "correct": false
            },
            {
              "text": "Platz in der Welt",
              "correct": false
            }
          ]
        },
        {
          "q": "Wie oft läuft for index in range(10)?",
          "answers": [
            {
              "text": "Zehnmal",
              "correct": true
            },
            {
              "text": "Neunmal",
              "correct": false
            },
            {
              "text": "Elfmal",
              "correct": false
            }
          ]
        },
        {
          "q": "Bei welcher Zahl fängt der Computer an zu zählen?",
          "answers": [
            {
              "text": "Bei 0",
              "correct": true
            },
            {
              "text": "Bei 1",
              "correct": false
            },
            {
              "text": "Bei 10",
              "correct": false
            }
          ]
        },
        {
          "q": "Was passiert bei for index in range(0)?",
          "answers": [
            {
              "text": "Nichts. Die Schleife läuft keinmal",
              "correct": true
            },
            {
              "text": "Die Schleife läuft einmal",
              "correct": false
            },
            {
              "text": "Der Agent meldet einen Fehler",
              "correct": false
            }
          ]
        }
      ]
    },
    "s05": {
      "title": "Schleife in der Schleife",
      "storyShort": "Eine Schleife kann in einer Schleife stehen. Die innere Schleife baut eine Reihe. Die äußere Schleife wiederholt die Reihe. So wird aus der Reihe eine Wand.",
      "bridge": {
        "game": "Du tippst wand in den Chat. Der Agent baut eine Wand aus drei Reihen.",
        "code": "Eine Schleife steht im Bauch der anderen. Innen die Reihe, außen die Ebenen."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Die Wand",
          "text": "Schreibe wand in den Chat. Der Agent baut eine Wand: 6 Blöcke breit, 3 hoch."
        },
        {
          "kind": "nochEiner",
          "title": "Größer",
          "text": "Ändere die Wand auf 8 Blöcke breit und 4 hoch. Welche zwei Zahlen musst du ändern?"
        },
        {
          "kind": "remix",
          "title": "Das Fenster",
          "text": "Baue eine Wand mit einem Fenster. Eine Reihe wird dafür kürzer. Zeig es deinem Partner oder deiner Partnerin."
        }
      ],
      "tipSolution": "Schreibe for index in range(4): in die äußere Schleife. Das ist die Höhe. Schreibe for index2 in range(8): in die innere Schleife. Das ist die Breite. Zähle nach: zwei Schleifen, eine im Bauch der anderen.",
      "exercises": [
        {
          "prompt": "Der Agent steht unten links. Seine Nase zeigt nach oben. Das Programm: 2 Schritte vor, links drehen, links drehen, 1 Schritt vor."
        },
        {
          "prompt": "Der Agent hat schon Bruchstein dabei. Jetzt kommt die Wand: außen die Ebenen, innen die Reihe. Achte auf die Einrückung."
        }
      ],
      "quiz": [
        {
          "q": "Die Wand ist 6 Blöcke breit und 3 hoch. Wie viele Blöcke sind das?",
          "answers": [
            {
              "text": "18 Blöcke",
              "correct": true
            },
            {
              "text": "9 Blöcke",
              "correct": false
            },
            {
              "text": "63 Blöcke",
              "correct": false
            }
          ]
        },
        {
          "q": "Was macht die innere Schleife?",
          "answers": [
            {
              "text": "Sie baut eine Reihe",
              "correct": true
            },
            {
              "text": "Sie geht eine Ebene hoch",
              "correct": false
            },
            {
              "text": "Sie dreht den Agent um",
              "correct": false
            }
          ]
        },
        {
          "q": "Warum dreht der Agent zweimal nach links?",
          "answers": [
            {
              "text": "Damit er zurückschaut und die nächste Reihe baut",
              "correct": true
            },
            {
              "text": "Damit er schneller läuft",
              "correct": false
            },
            {
              "text": "Damit er einen Block legen kann",
              "correct": false
            }
          ]
        },
        {
          "q": "Welche Schleife läuft zuerst ganz durch?",
          "answers": [
            {
              "text": "Die innere. Sie baut erst die ganze Reihe",
              "correct": true
            },
            {
              "text": "Die äußere. Sie geht erst ganz nach oben",
              "correct": false
            },
            {
              "text": "Beide laufen gleichzeitig",
              "correct": false
            }
          ]
        }
      ]
    },
    "s06": {
      "title": "Das Haus",
      "storyShort": "Ein Haus hat vier Wände. Du kopierst die Wand nicht viermal. Du legst eine Schleife außen herum. Nach jeder Wand dreht sich der Agent.",
      "bridge": {
        "game": "Du tippst haus in den Chat. Der Agent baut einen Ring aus vier Wänden.",
        "code": "Die äußere Schleife läuft viermal. Nach jeder Wand dreht der Agent um die Ecke."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Der Ring",
          "text": "Schreibe haus in den Chat. Der Agent baut einen Ring: 5 Blöcke pro Seite."
        },
        {
          "kind": "nochEiner",
          "title": "Höher",
          "text": "Der Ring soll 3 Blöcke hoch werden. Dafür brauchst du eine dritte Schleife."
        },
        {
          "kind": "remix",
          "title": "Die Tür",
          "text": "Lass in einer Wand eine Lücke als Tür. Zeig dein Haus deinem Partner oder deiner Partnerin."
        }
      ],
      "tipSolution": "Schreibe for index3 in range(3): ganz nach außen. Der ganze Ring steht eingerückt darin. Danach kommt agent.move(UP, 1). Zähle nach: drei Schleifen, eine in der anderen.",
      "exercises": [
        {
          "prompt": "Der Agent steht unten in der Mitte. Seine Nase zeigt nach oben. Das Programm: 2 Schritte vor, links drehen. Dann noch einmal: 2 Schritte vor, links drehen. Zum Schluss 2 Schritte vor."
        },
        {
          "prompt": "Der Agent baut einen Ring. Innen die Wand, außen die vier Seiten. Die Drehung gehört zur äußeren Schleife."
        }
      ],
      "quiz": [
        {
          "q": "Wie viele Wände baut for index in range(4)?",
          "answers": [
            {
              "text": "Vier",
              "correct": true
            },
            {
              "text": "Drei",
              "correct": false
            },
            {
              "text": "Fünf",
              "correct": false
            }
          ]
        },
        {
          "q": "Wo steht agent.turn(LEFT_TURN)?",
          "answers": [
            {
              "text": "In der äußeren Schleife, nach der inneren",
              "correct": true
            },
            {
              "text": "In der inneren Schleife, bei jedem Block",
              "correct": false
            },
            {
              "text": "Ganz oben, vor beiden Schleifen",
              "correct": false
            }
          ]
        },
        {
          "q": "Warum dreht der Agent nur einmal pro Wand?",
          "answers": [
            {
              "text": "Weil eine Ecke eine Vierteldrehung ist",
              "correct": true
            },
            {
              "text": "Weil er sonst zu langsam wird",
              "correct": false
            },
            {
              "text": "Weil er sonst keine Blöcke mehr hat",
              "correct": false
            }
          ]
        },
        {
          "q": "Der Ring hat 4 Seiten mit je 5 Blöcken. Wie viele Blöcke sind das?",
          "answers": [
            {
              "text": "20 Blöcke",
              "correct": true
            },
            {
              "text": "9 Blöcke",
              "correct": false
            },
            {
              "text": "45 Blöcke",
              "correct": false
            }
          ]
        }
      ],
      "bossCheck": {
        "title": "Boss-Check Stein: Der Zaun",
        "task": "Baue einen Zaun um dich herum: ein Ring aus 8×8 Blöcken. Was spart die Schleife? Wie viele Befehle wären es ohne Schleife?"
      }
    }
  }
};
