// AUTO-GENERATED by scripts/translate.mjs — NICHT von Hand bearbeiten.
// Manuell ergaenzt 03.09.2026 (Plan 2 Task 3): ui.bossCheckHeading/Hint + etappen.*.badge — de.js
// ist gewachsen, die volle Neuuebersetzung folgt erst in Plan 2 Task 9 (`translate.mjs --lang all`
// nach den neuen Stationen); bis dahin haelt dieser Handeintrag i18n-complete.test.js gruen.
// Source: src/i18n/de.js   sourceHash: 8edb57a86d18
// Language: en   model: claude-opus-5   generated: 2026-09-03T04:38:47.784Z
// Stuetz-Ebene: Deutsch bleibt daneben sichtbar. Bei Aenderung an de.js neu erzeugen.

export default {
  "ui": {
    "appTitle": "Code World",
    "tagline": "The Agent only understands code.",
    "home": "Overview",
    "station": "Station {n}",
    "ds": "Double lesson {n}",
    "support": "In your language",
    "supportShow": "Show help in your language",
    "supportHide": "Hide help",
    "storyHeading": "The story",
    "conceptHeading": "The idea",
    "bridgeGame": "In the game",
    "bridgeCode": "In the code",
    "blocksLabel": "This is how it looks as blocks",
    "pythonLabel": "This is how it looks as Python",
    "tasksHeading": "Your tasks in the game",
    "taskAuftrag": "Task",
    "taskNochEiner": "One more",
    "taskRemix": "Remix",
    "tipsHeading": "Hint ladder",
    "tipStep": "Hint {n}",
    "tipSolution": "Solution",
    "tipRemixNote": "If you use the solution: change one thing afterwards. That is a must.",
    "check": "Check",
    "checkHeading": "Got it?",
    "predictPrompt": "Where does the Agent stand at the end? Click on the square.",
    "predictRight": "Correct! The Agent stands exactly there.",
    "predictWrong": "Not yet. Read the program from top to bottom. Which way is it facing?",
    "parsonsPrompt": "Put the lines in the right order.",
    "parsonsUp": "move up",
    "parsonsDown": "move down",
    "parsonsCheck": "Check",
    "parsonsRight": "Correct! That is the order.",
    "parsonsWrong": "Not yet. What must the Agent do first?",
    "spielstandHeading": "Save point",
    "spielstandPrompt": "What can you do now? Write three short sentences.",
    "spielstandSave": "Save",
    "spielstandSaved": "Saved. Only on this device.",
    "progress": "You have visited {done} of {total} stations.",
    "next": "Next",
    "prev": "Back",
    "play": "Read aloud",
    "langLabel": "Language",
    "footer": "A learning module by Dirk Schulenburg · CC BY 4.0 · Not an official Minecraft product.",
    "bossCheckHeading": "Boss check",
    "bossCheckHint": "Solve the task without the hint ladder. Hand in the Share-Link and write three sentences."
  },
  "glossary": {
    "befehl": {
      "term": "Command",
      "short": "One line of code. The Agent does exactly that."
    },
    "programm": {
      "term": "Program",
      "short": "Many commands, from top to bottom."
    },
    "sequenz": {
      "term": "Sequence",
      "short": "The order of the commands."
    },
    "agent": {
      "term": "Agent",
      "short": "The robot in Minecraft. It only understands code."
    },
    "zauberwort": {
      "term": "Magic word",
      "short": "A word in the chat. It starts your program."
    },
    "python": {
      "term": "Python",
      "short": "A programming language. Your code as text."
    },
    "bloecke": {
      "term": "Blocks",
      "short": "Your code as building bricks you can drag."
    },
    "fehler": {
      "term": "Error",
      "short": "The Agent understood you wrong. You can fix it."
    }
  },
  "etappen": {
    "holz": {
      "name": "Wood",
      "badge": {
        "name": "Wood",
        "description": "You have passed all checks of the Wood stage and handed in the boss check."
      }
    },
    "stein": {
      "name": "Stone",
      "badge": {
        "name": "Stone",
        "description": "You have passed all checks of the Stone stage and handed in the boss check."
      }
    },
    "eisen": {
      "name": "Iron",
      "badge": {
        "name": "Iron",
        "description": "You have passed all checks of the Iron stage and handed in the boss check."
      }
    },
    "gold": {
      "name": "Gold",
      "badge": {
        "name": "Gold",
        "description": "You have passed all checks of the Gold stage and handed in the boss check."
      }
    },
    "diamant": {
      "name": "Diamond",
      "badge": {
        "name": "Diamond",
        "description": "You have passed all checks of the Diamond stage and handed in the boss check."
      }
    },
    "netherite": {
      "name": "Netherite",
      "badge": {
        "name": "Netherite",
        "description": "You have passed all checks of the Netherite stage and handed in the boss check."
      }
    },
    "enderdrache": {
      "name": "Ender Dragon",
      "badge": {
        "name": "Ender Dragon",
        "description": "You have passed all checks of the Ender Dragon stage and handed in the boss check."
      }
    }
  },
  "stations": {
    "s02": {
      "title": "Order matters",
      "storyShort": "The Agent does commands exactly in the order you write them. First move, then turn is not the same as first turn, then move.",
      "bridge": {
        "game": "The Agent moves step by step and places blocks behind itself.",
        "code": "A program is a list of commands. The computer does them from top to bottom."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "The path",
          "text": "Type the magic word weg in the chat. The Agent places three blocks. Look closely: where is the corner?"
        },
        {
          "kind": "nochEiner",
          "title": "Longer",
          "text": "Change the program. The Agent should place five blocks, then turn the corner, then two more."
        },
        {
          "kind": "remix",
          "title": "Your pattern",
          "text": "Build your own pattern out of blocks. For example a Z or a U. Show it to your partner."
        }
      ],
      "tipSolution": "For five blocks: write agent.move(FORWARD, 1) and agent.place(BACK) five times. Then agent.turn(LEFT_TURN). Then move and place two more times.",
      "exercises": [
        {
          "prompt": "The Agent stands at the bottom in the middle. Its nose points up. The program: 2 steps forward, turn left, 1 step forward."
        },
        {
          "prompt": "The Agent should come to you: move two steps, turn left and move one more step."
        }
      ],
      "quiz": [
        {
          "q": "The Agent should move 3 steps and then turn left. Which order is correct?",
          "answers": [
            {
              "text": "First agent.move(FORWARD, 3), then agent.turn(LEFT_TURN)",
              "correct": true
            },
            {
              "text": "First agent.turn(LEFT_TURN), then agent.move(FORWARD, 3)",
              "correct": false
            },
            {
              "text": "The order does not matter",
              "correct": false
            }
          ]
        },
        {
          "q": "You write agent.move(FORWARD, 3) twice, one line under the other. What does the Agent do?",
          "answers": [
            {
              "text": "It moves 6 steps",
              "correct": true
            },
            {
              "text": "It moves 3 steps",
              "correct": false
            },
            {
              "text": "It shows an error",
              "correct": false
            }
          ]
        },
        {
          "q": "When does your program start?",
          "answers": [
            {
              "text": "When you type the magic word in the chat",
              "correct": true
            },
            {
              "text": "Right away, when you open the Code Builder",
              "correct": false
            },
            {
              "text": "When you click on the Agent",
              "correct": false
            }
          ]
        },
        {
          "q": "The Agent understands …",
          "answers": [
            {
              "text": "only code",
              "correct": true
            },
            {
              "text": "German and English",
              "correct": false
            },
            {
              "text": "every language",
              "correct": false
            }
          ]
        }
      ]
    }
  }
};
