// AUTO-GENERATED by scripts/translate.mjs — NICHT von Hand bearbeiten.
// Source: src/i18n/de.js   sourceHash: c7de4d5be70a
// chunkHashes: {"ui":"48b164a63157","glossary":"5e6ca7f76272","etappen":"29e40128f71f","stations.s01":"c37b979d7d58","stations.s02":"63074802c205","stations.s03":"46eb47fc72b0","stations.s04":"8ed8fda3f3c3","stations.s05":"def7d38db5cd","stations.s06":"d4b61513c098","stations.s07":"242bf36d69d3","stations.s08":"2afc4366e9a0","stations.s09":"4478badd8d82"}
// Language: en   model: claude-opus-5   generated: 2026-09-16T17:10:01.225Z
// Stuetz-Ebene: Deutsch bleibt daneben sichtbar. Bei Aenderung an de.js neu erzeugen.

export default {
  "ui": {
    "appTitle": "Code World",
    "tagline": "The Agent only understands code.",
    "home": "Overview",
    "station": "Station {n}",
    "ds": "Double lesson {n}",
    "support": "In your language",
    "supportShow": "Show help in your language",
    "supportHide": "Hide help",
    "storyHeading": "The story",
    "conceptHeading": "The idea",
    "bridgeGame": "In the game",
    "bridgeCode": "In the code",
    "blocksLabel": "This is how it looks as blocks",
    "pythonLabel": "This is how it looks as Python",
    "tasksHeading": "Your tasks in the game",
    "taskAuftrag": "Task",
    "taskNochEiner": "One more",
    "taskRemix": "Remix",
    "tipsHeading": "Hint ladder",
    "tipStep": "Hint {n}",
    "tipSolution": "Solution",
    "tipRemixNote": "If you take the solution: change one thing afterwards. That is a must.",
    "check": "Check",
    "checkHeading": "Got it?",
    "predictPrompt": "Where does the Agent stand at the end? Click on the square.",
    "predictRight": "Correct! The Agent stands exactly there.",
    "predictWrong": "Not yet. Read the program from top to bottom. Which way is the nose pointing?",
    "parsonsPrompt": "Put the lines in the right order.",
    "parsonsUp": "move up",
    "parsonsDown": "move down",
    "parsonsCheck": "Check",
    "parsonsRight": "Correct! That is the order.",
    "parsonsWrong": "Not yet. What does the Agent have to do first?",
    "checkButton": "Check",
    "matchPrompt": "Which block belongs to which line? First the block, then the line.",
    "matchRight": "Correct! Every block has its line.",
    "matchWrong": "Not yet. Look at the numbers and names in the blocks.",
    "fillPrompt": "Choose the right answer for every gap.",
    "fillRight": "Correct! The code runs.",
    "fillWrong": "Not yet. One gap does not fit.",
    "findbugPrompt": "One line is wrong. Which one?",
    "findbugRight": "Correct! That is the mistake.",
    "findbugWrong": "No, this line is right. Look again.",
    "spielstandHeading": "Save point",
    "spielstandPrompt": "What can you do now? Write three short sentences.",
    "spielstandSave": "Save",
    "spielstandSaved": "Saved. Only on this device.",
    "progress": "You have visited {done} of {total} stations.",
    "next": "Next",
    "prev": "Back",
    "play": "Read aloud",
    "langLabel": "Language",
    "footer": "A learning module by Dirk Schulenburg · CC BY 4.0 · Not an official Minecraft product.",
    // Handkorrektur 2026-09-04 (Plan 3 Task 9): "Boss-Check" ist der Produktbegriff des Kurses und
    // steht so in den Etappen-Badges und den Boss-Check-Titeln der uebrigen Etappen. Der Lauf lieferte
    // eine Variante; Kanon BOSSCHECK_CANON in scripts/translate.mjs haelt sie kuenftig fest.
    "bossCheckHeading": "Boss-Check",
    "bossCheckHint": "Solve the task without the hint ladder. Hand in the share link and write three sentences."
  },
  "glossary": {
    "befehl": {
      "term": "Command",
      "short": "One line of code. The Agent does exactly that."
    },
    "programm": {
      "term": "Program",
      "short": "Many commands, from top to bottom."
    },
    "sequenz": {
      "term": "Sequence",
      "short": "The order of the commands."
    },
    "agent": {
      "term": "Agent",
      "short": "The robot in Minecraft. It only understands code."
    },
    "zauberwort": {
      "term": "Magic word",
      "short": "A word in the chat. It starts your program."
    },
    "python": {
      "term": "Python",
      "short": "A programming language. Your code as text."
    },
    "bloecke": {
      "term": "Blocks",
      "short": "Your code as building bricks you drag."
    },
    "fehler": {
      "term": "Error",
      "short": "The Agent understood you wrong. You can fix it."
    },
    "variable": {
      "term": "Variable",
      "short": "A number with a name. You set it once at the top."
    },
    "koordinaten": {
      "term": "Coordinates",
      "short": "Three numbers x, y, z say where a block is."
    },
    "fill": {
      "term": "fill",
      "short": "Fills everything between two corners with one block."
    },
    "zaehler": {
      "term": "Counter",
      "short": "The loop counts along: index is 0, 1, 2 …"
    }
  },
  "etappen": {
    "holz": {
      "name": "Wood",
      "badge": {
        "name": "Wood",
        // Handkorrektur 2026-09-04 (Re-Review T9): "the Boss-Check" als feststehender Begriff (Grossschreibung), nicht "the boss check".
        "description": "You passed all checks in the Wood stage and handed in the Boss-Check."
      }
    },
    "stein": {
      "name": "Stone",
      "badge": {
        "name": "Stone",
        // Handkorrektur 2026-09-04 (Re-Review T9): "the Boss-Check" als feststehender Begriff (Grossschreibung), nicht "the boss check".
        "description": "You passed all checks in the Stone stage and handed in the Boss-Check."
      }
    },
    "eisen": {
      "name": "Iron",
      "badge": {
        "name": "Iron",
        // Handkorrektur 2026-09-04 (Re-Review T9): "the Boss-Check" als feststehender Begriff (Grossschreibung), nicht "the boss check".
        "description": "You passed all checks in the Iron stage and handed in the Boss-Check."
      }
    },
    "gold": {
      "name": "Gold",
      "badge": {
        "name": "Gold",
        // Handkorrektur 2026-09-04 (Re-Review T9): "the Boss-Check" als feststehender Begriff (Grossschreibung), nicht "the boss check".
        "description": "You passed all checks in the Gold stage and handed in the Boss-Check."
      }
    },
    "diamant": {
      "name": "Diamond",
      "badge": {
        "name": "Diamond",
        // Handkorrektur 2026-09-04 (Re-Review T9): "the Boss-Check" als feststehender Begriff (Grossschreibung), nicht "the boss check".
        "description": "You passed all checks in the Diamond stage and handed in the Boss-Check."
      }
    },
    "netherite": {
      "name": "Netherite",
      "badge": {
        "name": "Netherite",
        // Handkorrektur 2026-09-04 (Re-Review T9): "the Boss-Check" als feststehender Begriff (Grossschreibung), nicht "the boss check".
        "description": "You passed all checks in the Netherite stage and handed in the Boss-Check."
      }
    },
    "enderdrache": {
      "name": "Ender Dragon",
      "badge": {
        "name": "Ender Dragon",
        // Handkorrektur 2026-09-04 (Re-Review T9): "the Boss-Check" als feststehender Begriff (Grossschreibung), nicht "the boss check".
        "description": "You passed all checks in the Ender Dragon stage and handed in the Boss-Check."
      }
    }
  },
  "stations": {
    "s01": {
      "title": "The New World",
      // Handkorrektur 2026-09-03 (Review T9): "Deutsch" bleibt der Name der deutschen Sprache — die SuS lernen Deutsch, nicht Englisch.
      // Vorher: "does not understand English".
      "storyShort": "The Agent is your robot in Minecraft. It does not understand German, only code. It only starts when you type a magic word in the chat.",
      "bridge": {
        "game": "You type hi in the chat. The Agent comes to you and walks one step.",
        "code": "A command is one line of code. The magic word starts the whole program."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Say hi",
          "text": "Type hi in the chat. The Agent comes to you. Then it walks one step forward."
        },
        {
          "kind": "nochEiner",
          "title": "Your word",
          "text": "Change the magic word from hi to hallo. Change the steps from 1 to 3. Try it out."
        },
        {
          "kind": "remix",
          "title": "One more word",
          "text": "Invent a second magic word. The Agent should do something different with it. Show it to your partner."
        }
      ],
      "tipSolution": "Write agent.teleport_to_player() and below it agent.move(FORWARD, 3). In the last line you replace “hi” with “hallo”. Only the word inside the quotation marks. Then you type hallo in the chat.",
      "exercises": [
        {
          "prompt": "The Agent stands at the bottom in the middle. Its nose points up. The program: 1 step forward."
        },
        {
          "prompt": "The Agent should come to you and walk one step. The line with the magic word comes last."
        }
      ],
      "quiz": [
        {
          "q": "What is the magic word for?",
          "answers": [
            {
              "text": "It starts your program",
              "correct": true
            },
            {
              "text": "It opens the Code Builder",
              "correct": false
            },
            {
              "text": "It saves your program",
              "correct": false
            }
          ]
        },
        {
          // Handkorrektur 2026-09-03 (Review T9): "The C/E/T key" statt "The key C/E/T" — gilt fuer alle drei Antworten dieser Frage.
          "q": "Which key opens the Code Builder?",
          "answers": [
            {
              "text": "The C key",
              "correct": true
            },
            {
              "text": "The E key",
              "correct": false
            },
            {
              "text": "The T key",
              "correct": false
            }
          ]
        },
        {
          "q": "What does agent.teleport_to_player() do?",
          "answers": [
            {
              "text": "The Agent comes to you",
              "correct": true
            },
            {
              "text": "The Agent walks one step forward",
              "correct": false
            },
            {
              "text": "The Agent places a block",
              "correct": false
            }
          ]
        },
        {
          "q": "The Agent understands …",
          "answers": [
            {
              "text": "only code",
              "correct": true
            },
            {
              "text": "every word in the chat",
              "correct": false
            },
            {
              // Handkorrektur 2026-09-03 (Review T9): "Deutsch" bleibt Deutsch (siehe storyShort). Vorher: "English, if you type slowly".
              "text": "German, if you type slowly",
              "correct": false
            }
          ]
        }
      ]
    },
    "s02": {
      "title": "Order matters",
      "storyShort": "The Agent does commands exactly in the order you write them. Move first, then turn is not the same as turn first, then move.",
      "bridge": {
        "game": "The Agent walks step by step and places blocks behind itself.",
        "code": "A program is a list of commands. The computer does them from top to bottom."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "The path",
          "text": "Type the magic word weg in the chat. The Agent places four blocks. Look closely: where is the corner?"
        },
        {
          "kind": "nochEiner",
          "title": "Longer",
          "text": "Change the program. The Agent places five blocks straight ahead, then the corner, then two more."
        },
        {
          "kind": "remix",
          "title": "Your pattern",
          "text": "Build your own pattern out of blocks. For example a Z or a U. Show it to your partner."
        }
      ],
      "tipSolution": "For five blocks: write agent.move(FORWARD, 1) and agent.place(BACK) five times. Then agent.turn(LEFT_TURN). After that come three more pairs of move and place. The first pair places the corner block.",
      "exercises": [
        {
          "prompt": "The Agent stands at the bottom in the middle. Its nose points up. The program: 2 steps forward, turn left, 1 step forward."
        },
        {
          "prompt": "The Agent should come to you, walk two steps, turn left and walk one more step."
        }
      ],
      "quiz": [
        {
          "q": "The Agent should walk 3 steps and then turn left. Which order is correct?",
          "answers": [
            {
              "text": "First agent.move(FORWARD, 3), then agent.turn(LEFT_TURN)",
              "correct": true
            },
            {
              "text": "First agent.turn(LEFT_TURN), then agent.move(FORWARD, 3)",
              "correct": false
            },
            {
              "text": "The order does not matter",
              "correct": false
            }
          ]
        },
        {
          "q": "You write agent.move(FORWARD, 3) twice, one line under the other. What does the Agent do?",
          "answers": [
            {
              "text": "It walks 6 steps",
              "correct": true
            },
            {
              "text": "It walks 3 steps",
              "correct": false
            },
            {
              "text": "It shows an error",
              "correct": false
            }
          ]
        },
        {
          "q": "When does your program start?",
          "answers": [
            {
              "text": "When you type the magic word in the chat",
              "correct": true
            },
            {
              "text": "Right away, when you open the Code Builder",
              "correct": false
            },
            {
              "text": "When you click on the Agent",
              "correct": false
            }
          ]
        },
        {
          "q": "The Agent understands …",
          "answers": [
            {
              "text": "only code",
              "correct": true
            },
            {
              "text": "German and English",
              "correct": false
            },
            {
              "text": "every language",
              "correct": false
            }
          ]
        }
      ]
    },
    "s03": {
      "title": "Magic Words",
      "storyShort": "A word in the chat is an event. Every magic word starts its own program. You can have several magic words.",
      "bridge": {
        "game": "You type weg or turm in the chat. The Agent builds the path or the tower.",
        "code": "Every magic word has its own hat block. Its own program sits under it."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Two words",
          "text": "Type weg in the chat. Then type turm. The path here is shorter than in Station 2. Look at both closely."
        },
        {
          "kind": "nochEiner",
          "title": "Higher",
          "text": "Change the program for turm. The tower should be five blocks high."
        },
        {
          "kind": "remix",
          "title": "The bridge",
          "text": "Invent a third magic word: bruecke. Magic words have no umlauts. With it the Agent builds a path over a gap."
        }
      ],
      "tipSolution": "For five blocks you write agent.place(FORWARD) and agent.move(UP, 1) one after the other. At the end comes agent.place(FORWARD) one more time. Count them: five lines with place.",
      "exercises": [
        {
          "prompt": "The Agent stands at the bottom left. Its nose points up. The program: 2 steps forward, turn right, 2 steps forward."
        },
        {
          "prompt": "The Agent comes to you. It takes grass. It walks one step and places a block. The line with the magic word comes last."
        }
      ],
      "quiz": [
        {
          "q": "What is an event?",
          "answers": [
            {
              "text": "Something happens in the game, for example a word in the chat",
              "correct": true
            },
            {
              "text": "A mistake in your program",
              "correct": false
            },
            {
              "text": "A block that the Agent places",
              "correct": false
            }
          ]
        },
        {
          "q": "You have two magic words. How many programs is that?",
          "answers": [
            {
              "text": "Two. Every word has its own program",
              "correct": true
            },
            {
              "text": "One. Both words start the same program",
              "correct": false
            },
            {
              "text": "None. Two magic words are not possible",
              "correct": false
            }
          ]
        },
        {
          "q": "What does agent.move(UP, 1) do?",
          "answers": [
            {
              "text": "The Agent moves one block up",
              "correct": true
            },
            {
              "text": "The Agent takes one step forward",
              "correct": false
            },
            {
              "text": "The Agent places a block above itself",
              "correct": false
            }
          ]
        },
        {
          "q": "You type weg first, then turm. What happens?",
          "answers": [
            {
              "text": "First the program for weg runs, then the one for turm",
              "correct": true
            },
            {
              "text": "Both programs run at the same time",
              "correct": false
            },
            {
              "text": "Only the program for turm runs",
              "correct": false
            }
          ]
        }
      ],
      "bossCheck": {
        // Handkorrektur 2026-09-03 (Review T9): Schreibweise "Boss-Check" wie im Deutschen, Etappenname gross. Vorher: "Boss Check wood".
        "title": "Boss-Check Wood",
        "subtitle": "The L",
        "task": "The Agent places an L: first 4 blocks straight ahead, then 2 around the corner. What does your program do? Why is the order important? What was hard?"
      }
    },
    "s04": {
      "title": "Repeat",
      "storyShort": "Writing the same thing ten times is tiring. That is what a loop is for. You write the lines once. The computer repeats them for you.",
      "bridge": {
        "game": "You type mauer in the chat. The Agent places ten blocks in a row.",
        "code": "A loop repeats two lines ten times. You only write them once."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "The wall",
          "text": "Type mauer in the chat. The Agent builds a wall of ten blocks. Count the blocks."
        },
        {
          "kind": "nochEiner",
          "title": "Longer and different",
          "text": "Change the number from 10 to 20. Use another kind of block, for example wood. Try it out."
        },
        {
          "kind": "remix",
          "title": "Two walls",
          "text": "Build two walls with a gap between them. Show it to your partner."
        }
      ],
      "tipSolution": "Write for index in range(20): in the loop line. The two lines under it stay indented. For wood you use agent.set_item(PLANKS_OAK, 64, 1). Count it: one loop, two lines inside it.",
      "exercises": [
        {
          "prompt": "The Agent stands at the bottom in the middle. Its nose points up. The program: 3 steps forward."
        },
        {
          "prompt": "The Agent comes to you and takes cobblestone. Then the loop repeats two lines. The indent belongs to the line."
        }
      ],
      "quiz": [
        {
          "q": "What does the loop save you?",
          "answers": [
            {
              "text": "Many identical lines",
              "correct": true
            },
            {
              "text": "Blocks in the backpack",
              "correct": false
            },
            {
              "text": "Space in the world",
              "correct": false
            }
          ]
        },
        {
          "q": "How often does a loop with range(10) run?",
          "answers": [
            {
              "text": "Ten times",
              "correct": true
            },
            {
              "text": "Nine times",
              "correct": false
            },
            {
              "text": "Eleven times",
              "correct": false
            }
          ]
        },
        {
          "q": "At which number does the computer start counting?",
          "answers": [
            {
              "text": "At 0",
              "correct": true
            },
            {
              "text": "At 1",
              "correct": false
            },
            {
              "text": "At 10",
              "correct": false
            }
          ]
        },
        {
          "q": "What happens with range(0)?",
          "answers": [
            {
              "text": "Nothing. The loop runs zero times",
              "correct": true
            },
            {
              "text": "The loop runs once",
              "correct": false
            },
            {
              "text": "The Agent reports an error",
              "correct": false
            }
          ]
        }
      ]
    },
    "s05": {
      "title": "A loop inside a loop",
      "storyShort": "A loop can sit inside another loop. The inner loop builds one row. The outer loop repeats the row. That turns the row into a wall.",
      "bridge": {
        "game": "You type wand into the chat. The Agent builds a wall out of three rows.",
        "code": "One loop sits inside the other. Inside is the row, outside are the layers."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "The wall",
          "text": "Type wand into the chat. The Agent builds a wall: 6 blocks wide, 3 high."
        },
        {
          "kind": "nochEiner",
          "title": "Bigger",
          "text": "Change the wall to 8 blocks wide and 4 high. Which two numbers do you have to change?"
        },
        {
          "kind": "remix",
          "title": "The battlement",
          "text": "Make the top row shorter. What does the wall look like now? Show it to your partner."
        }
      ],
      "tipSolution": "Write for index in range(4): in the outer loop. That is the height. Write for index2 in range(8): in the inner loop. That is the width. After the two turns comes one step forward. That way the Agent stands above the row again. Count them: two loops, one inside the other.",
      "exercises": [
        {
          "prompt": "The Agent stands at the bottom left. Its nose points up. The program: 2 steps forward, turn left, turn left, 1 step forward."
        },
        {
          "prompt": "The Agent already has cobblestone with it. Now comes the wall: the layers outside, the row inside. The turns and the step after them are missing here. Watch the indentation."
        }
      ],
      "quiz": [
        {
          "q": "The wall is 6 blocks wide and 3 high. How many blocks is that?",
          "answers": [
            {
              "text": "18 blocks",
              "correct": true
            },
            {
              "text": "9 blocks",
              "correct": false
            },
            {
              "text": "24 blocks",
              "correct": false
            }
          ]
        },
        {
          "q": "What does the inner loop do?",
          "answers": [
            {
              "text": "It builds one row",
              "correct": true
            },
            {
              "text": "It goes up one layer",
              "correct": false
            },
            {
              "text": "It turns the Agent around",
              "correct": false
            }
          ]
        },
        {
          "q": "Why does the Agent turn left twice?",
          "answers": [
            {
              "text": "So it looks back and builds the next row",
              "correct": true
            },
            {
              "text": "So it walks faster",
              "correct": false
            },
            {
              "text": "So it can place a block",
              "correct": false
            }
          ]
        },
        {
          "q": "Which loop runs all the way through first?",
          "answers": [
            {
              "text": "The inner one. It builds the whole row first",
              "correct": true
            },
            {
              "text": "The outer one. It goes all the way up first",
              "correct": false
            },
            {
              "text": "Both run at the same time",
              "correct": false
            }
          ]
        }
      ]
    },
    "s06": {
      "title": "The House",
      "storyShort": "A house has four walls. You do not copy the wall four times. You put a loop around it. After each side, the Agent turns.",
      "bridge": {
        "game": "You type haus in the chat. The Agent builds a ring of four sides.",
        "code": "The outer loop runs four times. After each side, the Agent turns the corner."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "The Ring",
          "text": "Type haus in the chat. The Agent builds a ring: 5 blocks per side."
        },
        {
          "kind": "nochEiner",
          "title": "Higher",
          "text": "The ring should be 3 blocks high. For that you need a third loop."
        },
        {
          // Handkorrektur 2026-09-04 (Welle C): Praeposition korrigiert (on, nicht in).
          "kind": "remix",
          "title": "The Door",
          "text": "Leave a gap on one side as a door. Show your house to your partner."
        }
      ],
      // Handkorrektur 2026-09-04 (Final Review): matches de.js — agent.move(UP, 1) sits inside
      // the third loop, right after the ring, not after the whole block.
      "tipSolution": "Write for index3 in range(3): all the way outside. The whole ring sits indented inside it. agent.move(UP, 1) sits inside it too, right after the ring. Count them: three loops, one inside the other.",
      "exercises": [
        {
          "prompt": "The Agent stands at the bottom in the middle. Its nose points up. The program: 2 steps forward, turn left. Then again: 2 steps forward, turn left. At the end 2 steps forward."
        },
        {
          "prompt": "The Agent builds a ring. Inside one side, outside the four sides. The turn belongs to the outer loop."
        }
      ],
      "quiz": [
        {
          "q": "How many sides does range(4) build?",
          "answers": [
            {
              "text": "Four",
              "correct": true
            },
            {
              "text": "Three",
              "correct": false
            },
            {
              "text": "Five",
              "correct": false
            }
          ]
        },
        {
          "q": "Where does agent.turn(LEFT_TURN) go?",
          "answers": [
            {
              "text": "In the outer loop, after the inner one",
              "correct": true
            },
            {
              "text": "In the inner loop, at every block",
              "correct": false
            },
            {
              "text": "Right at the top, before both loops",
              "correct": false
            }
          ]
        },
        {
          "q": "Why does the Agent turn only once per wall?",
          "answers": [
            {
              "text": "Because a corner is a quarter turn",
              "correct": true
            },
            {
              "text": "Because otherwise it gets too slow",
              "correct": false
            },
            {
              "text": "Because otherwise it runs out of blocks",
              "correct": false
            }
          ]
        },
        {
          "q": "The ring has 4 sides with 5 blocks each. How many blocks is that?",
          "answers": [
            {
              "text": "20 blocks",
              "correct": true
            },
            {
              "text": "16 blocks",
              "correct": false
            },
            {
              "text": "25 blocks",
              "correct": false
            }
          ]
        }
      ],
      "bossCheck": {
        // Handkorrektur 2026-09-03 (Review T9): Schreibweise "Boss-Check" wie im Deutschen, Etappenname gross. Vorher: "Boss Check stone".
        "title": "Boss-Check Stone",
        "subtitle": "The Fence",
        "task": "Build a fence around yourself. The ring has 8 blocks per side. What does the loop save you? How many commands would it be without a loop?"
      }
    },
    "s07": {
      "title": "Numbers with names",
      "storyShort": "A variable is a number with a name. You set it once, and the loop uses it everywhere. Change only the number, not the whole program.",
      "bridge": {
        "game": "You type bruecke. The Agent builds a bridge across the river.",
        "code": "laenge sits at the top once. The loop uses that number."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "The bridge",
          "text": "Stand on the gold block at spot A. Type bruecke. Walk across the bridge. Switch to Python at the top. Find the line laenge = 5."
        },
        {
          "kind": "nochEiner",
          "title": "Spot B",
          "text": "Go to the gold block at spot B. The river is 8 wide. Change only one number. Type bruecke."
        },
        {
          "kind": "remix",
          "title": "Your bridge",
          "text": "Build the bridge out of a different block. Or make it two blocks wide. Show it to your partner."
        }
      ],
      "tipSolution": "Set laenge = 8. Change only this one line. range(laenge) then builds eight move-place pairs.",
      "exercises": [
        {
          "prompt": "Match each block to its Python line."
        },
        {
          "prompt": "The river at spot B is 8 blocks wide. Which number goes in the gap?"
        }
      ],
      "quiz": [
        {
          "q": "What is laenge?",
          "answers": [
            {
              "text": "A number with a name",
              "correct": true
            },
            {
              "text": "A magic word",
              "correct": false
            },
            {
              "text": "A block",
              "correct": false
            }
          ]
        },
        {
          "q": "The bridge should be 8 long. What do you change?",
          "answers": [
            {
              "text": "Only the line laenge = 5",
              "correct": true
            },
            {
              "text": "Every line with a 5 in it",
              "correct": false
            },
            {
              "text": "The magic word",
              "correct": false
            }
          ]
        },
        {
          "q": "laenge = 5. How many times does range(laenge) run?",
          "answers": [
            {
              "text": "5 times",
              "correct": true
            },
            {
              "text": "4 times",
              "correct": false
            },
            {
              "text": "6 times",
              "correct": false
            }
          ]
        },
        {
          "q": "Where do you see your program as Python?",
          "answers": [
            {
              "text": "With the switch at the top of the editor",
              "correct": true
            },
            {
              "text": "In the chat",
              "correct": false
            },
            {
              "text": "In the world",
              "correct": false
            }
          ]
        }
      ]
    },
    "s08": {
      "title": "Where am I?",
      "storyShort": "Every block has three coordinates: x, y and z. pos counts from your feet, y is the height. fill fills a whole box with one command.",
      "bridge": {
        "game": "You read off x, y, z. You type plattform. The platform lies over the ravine.",
        "code": "fill fills everything between two corners. pos counts from your feet."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "The platform",
          "text": "Turn the coordinates on. Stand on the gold block at the ravine. Read off x, y, z and write them down. Write plattform. Walk across the platform. Switch to Python: find the two corners."
        },
        {
          "kind": "nochEiner",
          "title": "Wider",
          "text": "Make the platform twice as wide. Wider means here: in the x direction. Which number do you change?"
        },
        {
          "kind": "remix",
          "title": "The roof",
          "text": "Build a roof over the platform. Tip: y = 2. Show it to your partner."
        }
      ],
      "tipSolution": "The second corner becomes pos(9, -1, 7) instead of pos(4, -1, 7). 0 to 9 is ten blocks. Only the x number gets bigger.",
      "exercises": [
        {
          "prompt": "Three fill blocks, three lines. Watch the y and the block."
        },
        {
          "prompt": "The platform has turned into a thick wall. Which line is wrong?",
          "explain": "The second corner has y = 1. fill fills from y = -1 up to y = 1. That is three blocks high. The platform needs y = -1 in both corners."
        }
      ],
      "quiz": [
        {
          "q": "What does y mean?",
          "answers": [
            {
              "text": "The height",
              "correct": true
            },
            {
              "text": "Left and right",
              "correct": false
            },
            {
              "text": "Front and back",
              "correct": false
            }
          ]
        },
        {
          "q": "Where is pos(0, -1, 1)?",
          "answers": [
            {
              "text": "One block below you, one block further in the z direction",
              "correct": true
            },
            {
              "text": "Above you",
              "correct": false
            },
            {
              "text": "Far away",
              "correct": false
            }
          ]
        },
        {
          "q": "What does fill do?",
          "answers": [
            {
              "text": "Fills everything between two corners",
              "correct": true
            },
            {
              "text": "Places one block",
              "correct": false
            },
            {
              "text": "Moves the Agent",
              "correct": false
            }
          ]
        },
        {
          "q": "The display in the game shows x, y, z. What are these?",
          "answers": [
            {
              "text": "World coordinates, the same for everyone",
              "correct": true
            },
            {
              "text": "Distances from you",
              "correct": false
            },
            {
              "text": "Random numbers",
              "correct": false
            }
          ]
        }
      ]
    },
    "s09": {
      "title": "Counting",
      "storyShort": "The loop counts by itself: index is 0, then 1, then 2. Use index as the height. That turns one line into a whole staircase.",
      "bridge": {
        "game": "You type treppe. The staircase grows step by step up to the plateau.",
        "code": "index counts 0, 1, 2 … The loop uses index as the height."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "The staircase",
          "text": "Stand on the gold block in front of the cliff. Write treppe. Walk up the staircase. Switch to Python: where does index appear twice?"
        },
        {
          "kind": "nochEiner",
          "title": "Wider",
          "text": "Make every step 5 wide. Change the last number in pos, the z number."
        },
        {
          "kind": "remix",
          "title": "Your staircase",
          "text": "Build the staircase out of oak wood. Or build it down into the ravine. Show it to your partner."
        }
      ],
      "tipSolution": "Step index goes from pos(index, 0, 1) to pos(index, index, 3). stufen = 6 gives six steps.",
      "exercises": [
        {
          "prompt": "The cliff is 6 high. Every step is as high as its counter plus 1."
        },
        {
          "prompt": "The staircase has become a wall. Which line is wrong?",
          "explain": "In pos there is stufen instead of index. Then every step is 7 high. You get a wall, not a staircase."
        }
      ],
      "quiz": [
        {
          "q": "What is index?",
          "answers": [
            {
              "text": "The counter of the loop",
              "correct": true
            },
            {
              "text": "The height of the cliff",
              "correct": false
            },
            {
              "text": "A magic word",
              "correct": false
            }
          ]
        },
        {
          "q": "range(6): which values does index get?",
          "answers": [
            {
              "text": "0 to 5",
              "correct": true
            },
            {
              "text": "1 to 6",
              "correct": false
            },
            {
              "text": "0 to 6",
              "correct": false
            }
          ]
        },
        {
          "q": "Why does every step get higher?",
          "answers": [
            {
              "text": "index gets bigger with every run",
              "correct": true
            },
            {
              "text": "fill counts by itself",
              "correct": false
            },
            {
              "text": "stufen gets bigger",
              "correct": false
            }
          ]
        },
        {
          "q": "The cliff is 9 high. What do you set?",
          "answers": [
            {
              "text": "stufen = 9",
              "correct": true
            },
            {
              "text": "index = 9",
              "correct": false
            },
            {
              "text": "range(8)",
              "correct": false
            }
          ]
        }
      ],
      "bossCheck": {
        // Handkorrektur 2026-09-04 (Plan 3 Task 9): "Boss-Check" ist der Produktbegriff des Kurses und
        // steht so in den Etappen-Badges und den Boss-Check-Titeln der uebrigen Etappen. Der Lauf lieferte
        // eine Variante; Kanon BOSSCHECK_CANON in scripts/translate.mjs haelt sie kuenftig fest.
        "title": "Boss-Check Iron",
        "subtitle": "The second cliff",
        "task": "Stand on the gold block in front of the second cliff. Read off y at the bottom. Climb up the ladder and read off y at the top. Set stufen. Build the staircase. Write three sentences: where does your number come from? What does index do? What do you change for a higher cliff?"
      }
    }
  }
};
