// AUTO-GENERATED by scripts/translate.mjs — NICHT von Hand bearbeiten.
// Source: src/i18n/de.js   sourceHash: 8114d96e4319
// Language: en   model: claude-opus-5   generated: 2026-09-03T21:20:32.316Z
// Stuetz-Ebene: Deutsch bleibt daneben sichtbar. Bei Aenderung an de.js neu erzeugen.

export default {
  "ui": {
    "appTitle": "Code World",
    "tagline": "The Agent only understands code.",
    "home": "Overview",
    "station": "Station {n}",
    "ds": "Double lesson {n}",
    "support": "In your language",
    "supportShow": "Show help in your language",
    "supportHide": "Hide help",
    "storyHeading": "The story",
    "conceptHeading": "The idea",
    "bridgeGame": "In the game",
    "bridgeCode": "In the code",
    "blocksLabel": "This is how it looks as blocks",
    "pythonLabel": "This is how it looks as Python",
    "tasksHeading": "Your tasks in the game",
    "taskAuftrag": "Task",
    "taskNochEiner": "One more",
    "taskRemix": "Remix",
    "tipsHeading": "Hint ladder",
    "tipStep": "Hint {n}",
    "tipSolution": "Solution",
    "tipRemixNote": "If you take the solution: change one thing afterwards. That is a must.",
    "check": "Check",
    "checkHeading": "Got it?",
    "predictPrompt": "Where does the Agent stand at the end? Click on the square.",
    "predictRight": "Correct! The Agent stands exactly there.",
    "predictWrong": "Not yet. Read the program from top to bottom. Where is the nose pointing?",
    "parsonsPrompt": "Put the lines in the right order.",
    "parsonsUp": "move up",
    "parsonsDown": "move down",
    "parsonsCheck": "Check",
    "parsonsRight": "Correct! That is the order.",
    "parsonsWrong": "Not yet. What does the Agent have to do first?",
    "spielstandHeading": "Save point",
    "spielstandPrompt": "What can you do now? Write three short sentences.",
    "spielstandSave": "Save",
    "spielstandSaved": "Saved. Only on this device.",
    "progress": "You have visited {done} of {total} stations.",
    "next": "Next",
    "prev": "Back",
    "play": "Read aloud",
    "langLabel": "Language",
    "footer": "A learning module by Dirk Schulenburg · CC BY 4.0 · Not an official Minecraft product.",
    // Handkorrektur 2026-09-03 (Review T9): Produktbegriff "Boss-Check" wie im Deutschen und wie in den beiden bossCheck-Titeln unten.
    "bossCheckHeading": "Boss-Check",
    "bossCheckHint": "Solve the task without the hint ladder. Hand in the share link and write three sentences."
  },
  "glossary": {
    "befehl": {
      "term": "Command",
      "short": "One line of code. The Agent does exactly that."
    },
    "programm": {
      "term": "Program",
      "short": "Many commands, from top to bottom."
    },
    "sequenz": {
      "term": "Sequence",
      "short": "The order of the commands."
    },
    "agent": {
      "term": "Agent",
      "short": "The robot in Minecraft. It only understands code."
    },
    "zauberwort": {
      "term": "Magic word",
      "short": "A word in the chat. It starts your program."
    },
    "python": {
      "term": "Python",
      "short": "A programming language. Your code as text."
    },
    "bloecke": {
      "term": "Blocks",
      "short": "Your code as building bricks you can drag."
    },
    "fehler": {
      "term": "Error",
      "short": "The Agent understood you wrong. You can fix it."
    }
  },
  "etappen": {
    "holz": {
      "name": "Wood",
      "badge": {
        "name": "Wood",
        // Handkorrektur 2026-09-04 (Re-Review T9): "the Boss-Check" als feststehender Begriff (Grossschreibung), nicht "the boss check".
        "description": "You passed all checks in the Wood stage and handed in the Boss-Check."
      }
    },
    "stein": {
      "name": "Stone",
      "badge": {
        "name": "Stone",
        // Handkorrektur 2026-09-04 (Re-Review T9): "the Boss-Check" als feststehender Begriff (Grossschreibung), nicht "the boss check".
        "description": "You passed all checks in the Stone stage and handed in the Boss-Check."
      }
    },
    "eisen": {
      "name": "Iron",
      "badge": {
        "name": "Iron",
        // Handkorrektur 2026-09-04 (Re-Review T9): "the Boss-Check" als feststehender Begriff (Grossschreibung), nicht "the boss check".
        "description": "You passed all checks in the Iron stage and handed in the Boss-Check."
      }
    },
    "gold": {
      "name": "Gold",
      "badge": {
        "name": "Gold",
        // Handkorrektur 2026-09-04 (Re-Review T9): "the Boss-Check" als feststehender Begriff (Grossschreibung), nicht "the boss check".
        "description": "You passed all checks in the Gold stage and handed in the Boss-Check."
      }
    },
    "diamant": {
      "name": "Diamond",
      "badge": {
        "name": "Diamond",
        // Handkorrektur 2026-09-04 (Re-Review T9): "the Boss-Check" als feststehender Begriff (Grossschreibung), nicht "the boss check".
        "description": "You passed all checks in the Diamond stage and handed in the Boss-Check."
      }
    },
    "netherite": {
      "name": "Netherite",
      "badge": {
        "name": "Netherite",
        // Handkorrektur 2026-09-04 (Re-Review T9): "the Boss-Check" als feststehender Begriff (Grossschreibung), nicht "the boss check".
        "description": "You passed all checks in the Netherite stage and handed in the Boss-Check."
      }
    },
    "enderdrache": {
      "name": "Ender Dragon",
      "badge": {
        "name": "Ender Dragon",
        // Handkorrektur 2026-09-04 (Re-Review T9): "the Boss-Check" als feststehender Begriff (Grossschreibung), nicht "the boss check".
        "description": "You passed all checks in the Ender Dragon stage and handed in the Boss-Check."
      }
    }
  },
  "stations": {
    "s01": {
      "title": "The New World",
      // Handkorrektur 2026-09-03 (Review T9): "Deutsch" bleibt der Name der deutschen Sprache — die SuS lernen Deutsch, nicht Englisch.
      // Vorher: "does not understand English".
      "storyShort": "The Agent is your robot in Minecraft. It does not understand German, only code. It only starts when you type a magic word in the chat.",
      "bridge": {
        "game": "You type hi in the chat. The Agent comes to you and walks one step.",
        "code": "A command is one line of code. The magic word starts the whole program."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Say hi",
          "text": "Type hi in the chat. The Agent comes to you. Then it walks one step forward."
        },
        {
          "kind": "nochEiner",
          "title": "Your word",
          "text": "Change the magic word from hi to hallo. Change the steps from 1 to 3. Try it out."
        },
        {
          "kind": "remix",
          "title": "One more word",
          "text": "Invent a second magic word. The Agent should do something different with it. Show it to your partner."
        }
      ],
      "tipSolution": "Write agent.teleport_to_player() and below it agent.move(FORWARD, 3). In the last line you replace “hi” with “hallo”. Only the word inside the quotation marks. Then you type hallo in the chat.",
      "exercises": [
        {
          "prompt": "The Agent stands at the bottom in the middle. Its nose points up. The program: 1 step forward."
        },
        {
          "prompt": "The Agent should come to you and walk one step. The line with the magic word comes last."
        }
      ],
      "quiz": [
        {
          "q": "What is the magic word for?",
          "answers": [
            {
              "text": "It starts your program",
              "correct": true
            },
            {
              "text": "It opens the Code Builder",
              "correct": false
            },
            {
              "text": "It saves your program",
              "correct": false
            }
          ]
        },
        {
          // Handkorrektur 2026-09-03 (Review T9): "The C/E/T key" statt "The key C/E/T" — gilt fuer alle drei Antworten dieser Frage.
          "q": "Which key opens the Code Builder?",
          "answers": [
            {
              "text": "The C key",
              "correct": true
            },
            {
              "text": "The E key",
              "correct": false
            },
            {
              "text": "The T key",
              "correct": false
            }
          ]
        },
        {
          "q": "What does agent.teleport_to_player() do?",
          "answers": [
            {
              "text": "The Agent comes to you",
              "correct": true
            },
            {
              "text": "The Agent walks one step forward",
              "correct": false
            },
            {
              "text": "The Agent places a block",
              "correct": false
            }
          ]
        },
        {
          "q": "The Agent understands …",
          "answers": [
            {
              "text": "only code",
              "correct": true
            },
            {
              "text": "every word in the chat",
              "correct": false
            },
            {
              // Handkorrektur 2026-09-03 (Review T9): "Deutsch" bleibt Deutsch (siehe storyShort). Vorher: "English, if you type slowly".
              "text": "German, if you type slowly",
              "correct": false
            }
          ]
        }
      ]
    },
    "s02": {
      "title": "Order matters",
      "storyShort": "The Agent does commands exactly in the order you write them. Move first, then turn is not the same as turn first, then move.",
      "bridge": {
        "game": "The Agent walks step by step and places blocks behind itself.",
        "code": "A program is a list of commands. The computer does them from top to bottom."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "The path",
          "text": "Type the magic word weg in the chat. The Agent places four blocks. Look closely: where is the corner?"
        },
        {
          "kind": "nochEiner",
          "title": "Longer",
          "text": "Change the program. The Agent places five blocks straight ahead, then the corner, then two more."
        },
        {
          "kind": "remix",
          "title": "Your pattern",
          "text": "Build your own pattern out of blocks. For example a Z or a U. Show it to your partner."
        }
      ],
      "tipSolution": "For five blocks: write agent.move(FORWARD, 1) and agent.place(BACK) five times. Then agent.turn(LEFT_TURN). After that come three more pairs of move and place. The first pair places the corner block.",
      "exercises": [
        {
          "prompt": "The Agent stands at the bottom in the middle. Its nose points up. The program: 2 steps forward, turn left, 1 step forward."
        },
        {
          "prompt": "The Agent should come to you, walk two steps, turn left and walk one more step."
        }
      ],
      "quiz": [
        {
          "q": "The Agent should walk 3 steps and then turn left. Which order is correct?",
          "answers": [
            {
              "text": "First agent.move(FORWARD, 3), then agent.turn(LEFT_TURN)",
              "correct": true
            },
            {
              "text": "First agent.turn(LEFT_TURN), then agent.move(FORWARD, 3)",
              "correct": false
            },
            {
              "text": "The order does not matter",
              "correct": false
            }
          ]
        },
        {
          "q": "You write agent.move(FORWARD, 3) twice, one line under the other. What does the Agent do?",
          "answers": [
            {
              "text": "It walks 6 steps",
              "correct": true
            },
            {
              "text": "It walks 3 steps",
              "correct": false
            },
            {
              "text": "It shows an error",
              "correct": false
            }
          ]
        },
        {
          "q": "When does your program start?",
          "answers": [
            {
              "text": "When you type the magic word in the chat",
              "correct": true
            },
            {
              "text": "Right away, when you open the Code Builder",
              "correct": false
            },
            {
              "text": "When you click on the Agent",
              "correct": false
            }
          ]
        },
        {
          "q": "The Agent understands …",
          "answers": [
            {
              "text": "only code",
              "correct": true
            },
            {
              "text": "German and English",
              "correct": false
            },
            {
              "text": "every language",
              "correct": false
            }
          ]
        }
      ]
    },
    "s03": {
      "title": "Magic Words",
      "storyShort": "A word in the chat is an event. Every magic word starts its own program. You can have several magic words.",
      "bridge": {
        "game": "You type weg or turm in the chat. The Agent builds the path or the tower.",
        "code": "Every magic word has its own hat block. Its own program sits under it."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Two words",
          "text": "Type weg in the chat. Then type turm. The path here is shorter than in Station 2. Look at both closely."
        },
        {
          "kind": "nochEiner",
          "title": "Higher",
          "text": "Change the program for turm. The tower should be five blocks high."
        },
        {
          "kind": "remix",
          "title": "The bridge",
          "text": "Invent a third magic word: bruecke. Magic words have no umlauts. With it the Agent builds a path over a gap."
        }
      ],
      "tipSolution": "For five blocks you write agent.place(FORWARD) and agent.move(UP, 1) one after the other. At the end comes agent.place(FORWARD) one more time. Count them: five lines with place.",
      "exercises": [
        {
          "prompt": "The Agent stands at the bottom left. Its nose points up. The program: 2 steps forward, turn right, 2 steps forward."
        },
        {
          "prompt": "The Agent comes to you. It takes grass. It walks one step and places a block. The line with the magic word comes last."
        }
      ],
      "quiz": [
        {
          "q": "What is an event?",
          "answers": [
            {
              "text": "Something happens in the game, for example a word in the chat",
              "correct": true
            },
            {
              "text": "A mistake in your program",
              "correct": false
            },
            {
              "text": "A block that the Agent places",
              "correct": false
            }
          ]
        },
        {
          "q": "You have two magic words. How many programs is that?",
          "answers": [
            {
              "text": "Two. Every word has its own program",
              "correct": true
            },
            {
              "text": "One. Both words start the same program",
              "correct": false
            },
            {
              "text": "None. Two magic words are not possible",
              "correct": false
            }
          ]
        },
        {
          "q": "What does agent.move(UP, 1) do?",
          "answers": [
            {
              "text": "The Agent moves one block up",
              "correct": true
            },
            {
              "text": "The Agent takes one step forward",
              "correct": false
            },
            {
              "text": "The Agent places a block above itself",
              "correct": false
            }
          ]
        },
        {
          "q": "You type weg first, then turm. What happens?",
          "answers": [
            {
              "text": "First the program for weg runs, then the one for turm",
              "correct": true
            },
            {
              "text": "Both programs run at the same time",
              "correct": false
            },
            {
              "text": "Only the program for turm runs",
              "correct": false
            }
          ]
        }
      ],
      "bossCheck": {
        // Handkorrektur 2026-09-03 (Review T9): Schreibweise "Boss-Check" wie im Deutschen, Etappenname gross. Vorher: "Boss Check wood".
        "title": "Boss-Check Wood",
        "subtitle": "The L",
        "task": "The Agent places an L: first 4 blocks straight ahead, then 2 around the corner. What does your program do? Why is the order important? What was hard?"
      }
    },
    "s04": {
      "title": "Repeat",
      "storyShort": "Writing the same thing ten times is tiring. That is what a loop is for. You write the lines once. The computer repeats them for you.",
      "bridge": {
        "game": "You type mauer in the chat. The Agent places ten blocks in a row.",
        "code": "A loop repeats two lines ten times. You only write them once."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "The wall",
          "text": "Type mauer in the chat. The Agent builds a wall of ten blocks. Count the blocks."
        },
        {
          "kind": "nochEiner",
          "title": "Longer and different",
          "text": "Change the number from 10 to 20. Use another kind of block, for example wood. Try it out."
        },
        {
          "kind": "remix",
          "title": "Two walls",
          "text": "Build two walls with a gap between them. Show it to your partner."
        }
      ],
      "tipSolution": "Write for index in range(20): in the loop line. The two lines under it stay indented. For wood you use agent.set_item(PLANKS_OAK, 64, 1). Count it: one loop, two lines inside it.",
      "exercises": [
        {
          "prompt": "The Agent stands at the bottom in the middle. Its nose points up. The program: 3 steps forward."
        },
        {
          "prompt": "The Agent comes to you and takes cobblestone. Then the loop repeats two lines. The indent belongs to the line."
        }
      ],
      "quiz": [
        {
          "q": "What does the loop save you?",
          "answers": [
            {
              "text": "Many identical lines",
              "correct": true
            },
            {
              "text": "Blocks in the backpack",
              "correct": false
            },
            {
              "text": "Space in the world",
              "correct": false
            }
          ]
        },
        {
          "q": "How often does a loop with range(10) run?",
          "answers": [
            {
              "text": "Ten times",
              "correct": true
            },
            {
              "text": "Nine times",
              "correct": false
            },
            {
              "text": "Eleven times",
              "correct": false
            }
          ]
        },
        {
          "q": "At which number does the computer start counting?",
          "answers": [
            {
              "text": "At 0",
              "correct": true
            },
            {
              "text": "At 1",
              "correct": false
            },
            {
              "text": "At 10",
              "correct": false
            }
          ]
        },
        {
          "q": "What happens with range(0)?",
          "answers": [
            {
              "text": "Nothing. The loop runs zero times",
              "correct": true
            },
            {
              "text": "The loop runs once",
              "correct": false
            },
            {
              "text": "The Agent reports an error",
              "correct": false
            }
          ]
        }
      ]
    },
    "s05": {
      "title": "A loop inside a loop",
      "storyShort": "A loop can sit inside another loop. The inner loop builds one row. The outer loop repeats the row. That turns the row into a wall.",
      "bridge": {
        "game": "You type wand into the chat. The Agent builds a wall out of three rows.",
        "code": "One loop sits inside the other. Inside is the row, outside are the layers."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "The wall",
          "text": "Type wand into the chat. The Agent builds a wall: 6 blocks wide, 3 high."
        },
        {
          "kind": "nochEiner",
          "title": "Bigger",
          "text": "Change the wall to 8 blocks wide and 4 high. Which two numbers do you have to change?"
        },
        {
          "kind": "remix",
          "title": "The battlement",
          "text": "Make the top row shorter. What does the wall look like now? Show it to your partner."
        }
      ],
      "tipSolution": "Write for index in range(4): in the outer loop. That is the height. Write for index2 in range(8): in the inner loop. That is the width. After the two turns comes one step forward. That way the Agent stands above the row again. Count them: two loops, one inside the other.",
      "exercises": [
        {
          "prompt": "The Agent stands at the bottom left. Its nose points up. The program: 2 steps forward, turn left, turn left, 1 step forward."
        },
        {
          "prompt": "The Agent already has cobblestone with it. Now comes the wall: the layers outside, the row inside. The turns and the step after them are missing here. Watch the indentation."
        }
      ],
      "quiz": [
        {
          "q": "The wall is 6 blocks wide and 3 high. How many blocks is that?",
          "answers": [
            {
              "text": "18 blocks",
              "correct": true
            },
            {
              "text": "9 blocks",
              "correct": false
            },
            {
              "text": "24 blocks",
              "correct": false
            }
          ]
        },
        {
          "q": "What does the inner loop do?",
          "answers": [
            {
              "text": "It builds one row",
              "correct": true
            },
            {
              "text": "It goes up one layer",
              "correct": false
            },
            {
              "text": "It turns the Agent around",
              "correct": false
            }
          ]
        },
        {
          "q": "Why does the Agent turn left twice?",
          "answers": [
            {
              "text": "So it looks back and builds the next row",
              "correct": true
            },
            {
              "text": "So it walks faster",
              "correct": false
            },
            {
              "text": "So it can place a block",
              "correct": false
            }
          ]
        },
        {
          "q": "Which loop runs all the way through first?",
          "answers": [
            {
              "text": "The inner one. It builds the whole row first",
              "correct": true
            },
            {
              "text": "The outer one. It goes all the way up first",
              "correct": false
            },
            {
              "text": "Both run at the same time",
              "correct": false
            }
          ]
        }
      ]
    },
    "s06": {
      "title": "The House",
      "storyShort": "A house has four walls. You do not copy the wall four times. You put a loop around it. After each side, the Agent turns.",
      "bridge": {
        "game": "You type haus in the chat. The Agent builds a ring of four sides.",
        "code": "The outer loop runs four times. After each side, the Agent turns the corner."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "The Ring",
          "text": "Type haus in the chat. The Agent builds a ring: 5 blocks per side."
        },
        {
          "kind": "nochEiner",
          "title": "Higher",
          "text": "The ring should be 3 blocks high. For that you need a third loop."
        },
        {
          "kind": "remix",
          "title": "The Door",
          "text": "Leave a gap in one side as a door. Show your house to your partner."
        }
      ],
      // Handkorrektur 2026-09-04 (Final Review): matches de.js — agent.move(UP, 1) sits inside
      // the third loop, right after the ring, not after the whole block.
      "tipSolution": "Write for index3 in range(3): all the way outside. The whole ring sits indented inside it. agent.move(UP, 1) sits inside it too, right after the ring. Count them: three loops, one inside the other.",
      "exercises": [
        {
          "prompt": "The Agent stands at the bottom in the middle. Its nose points up. The program: 2 steps forward, turn left. Then again: 2 steps forward, turn left. At the end 2 steps forward."
        },
        {
          "prompt": "The Agent builds a ring. Inside one side, outside the four sides. The turn belongs to the outer loop."
        }
      ],
      "quiz": [
        {
          "q": "How many sides does range(4) build?",
          "answers": [
            {
              "text": "Four",
              "correct": true
            },
            {
              "text": "Three",
              "correct": false
            },
            {
              "text": "Five",
              "correct": false
            }
          ]
        },
        {
          "q": "Where does agent.turn(LEFT_TURN) go?",
          "answers": [
            {
              "text": "In the outer loop, after the inner one",
              "correct": true
            },
            {
              "text": "In the inner loop, at every block",
              "correct": false
            },
            {
              "text": "Right at the top, before both loops",
              "correct": false
            }
          ]
        },
        {
          "q": "Why does the Agent turn only once per wall?",
          "answers": [
            {
              "text": "Because a corner is a quarter turn",
              "correct": true
            },
            {
              "text": "Because otherwise it gets too slow",
              "correct": false
            },
            {
              "text": "Because otherwise it runs out of blocks",
              "correct": false
            }
          ]
        },
        {
          "q": "The ring has 4 sides with 5 blocks each. How many blocks is that?",
          "answers": [
            {
              "text": "20 blocks",
              "correct": true
            },
            {
              "text": "16 blocks",
              "correct": false
            },
            {
              "text": "25 blocks",
              "correct": false
            }
          ]
        }
      ],
      "bossCheck": {
        // Handkorrektur 2026-09-03 (Review T9): Schreibweise "Boss-Check" wie im Deutschen, Etappenname gross. Vorher: "Boss Check stone".
        "title": "Boss-Check Stone",
        "subtitle": "The Fence",
        "task": "Build a fence around yourself. The ring has 8 blocks per side. What does the loop save you? How many commands would it be without a loop?"
      }
    }
  }
};
