// AUTO-GENERATED by scripts/translate.mjs — NICHT von Hand bearbeiten.
// Plan 2 Task 4: stations.s01 und stations.s03 stehen hier vorübergehend auf Deutsch — Task 9 übersetzt sie.
// Manuell korrigiert 03.09.2026 (Review Task 8): glossary.*.term (DE-Reste -> ES) — bei Regeneration mit --force erneut pruefen.
// Manuell ergaenzt 03.09.2026 (Plan 2 Task 3): ui.bossCheckHeading/Hint + etappen.*.badge — de.js
// ist gewachsen, die volle Neuuebersetzung folgt erst in Plan 2 Task 9 (`translate.mjs --lang all`
// nach den neuen Stationen); bis dahin haelt dieser Handeintrag i18n-complete.test.js gruen.
// Source: src/i18n/de.js   sourceHash: 8edb57a86d18
// Language: es   model: claude-opus-5   generated: 2026-09-03T04:40:36.924Z
// Stuetz-Ebene: Deutsch bleibt daneben sichtbar. Bei Aenderung an de.js neu erzeugen.

export default {
  "ui": {
    "appTitle": "Mundo de código",
    "tagline": "El Agent solo entiende código.",
    "home": "Vista general",
    "station": "Estación {n}",
    "ds": "Clase doble {n}",
    "support": "En tu idioma",
    "supportShow": "Mostrar ayuda en tu idioma",
    "supportHide": "Ocultar ayuda",
    "storyHeading": "La historia",
    "conceptHeading": "La idea",
    "bridgeGame": "En el juego",
    "bridgeCode": "En el código",
    "blocksLabel": "Así se ve con bloques",
    "pythonLabel": "Así se ve en Python",
    "tasksHeading": "Tus tareas en el juego",
    "taskAuftrag": "Misión",
    "taskNochEiner": "Una más",
    "taskRemix": "Remix",
    "tipsHeading": "Escalera de pistas",
    "tipStep": "Pista {n}",
    "tipSolution": "Solución",
    "tipRemixNote": "Si usas la solución: después cambia una cosa. Es obligatorio.",
    "check": "Check",
    "checkHeading": "¿Lo entendiste?",
    "predictPrompt": "¿Dónde está el Agent al final? Haz clic en la casilla.",
    "predictRight": "¡Correcto! El Agent está justo ahí.",
    "predictWrong": "Todavía no. Lee el programa de arriba abajo. ¿Hacia dónde mira?",
    "parsonsPrompt": "Pon las líneas en el orden correcto.",
    "parsonsUp": "hacia arriba",
    "parsonsDown": "hacia abajo",
    "parsonsCheck": "Comprobar",
    "parsonsRight": "¡Correcto! Ese es el orden.",
    "parsonsWrong": "Todavía no. ¿Qué tiene que hacer el Agent primero?",
    "spielstandHeading": "Punto de partida",
    "spielstandPrompt": "¿Qué sabes hacer ahora? Escribe tres frases cortas.",
    "spielstandSave": "Guardar",
    "spielstandSaved": "Guardado. Solo en este dispositivo.",
    "progress": "Has visitado {done} de {total} estaciones.",
    "next": "Siguiente",
    "prev": "Atrás",
    "play": "Leer en voz alta",
    "langLabel": "Idioma",
    "footer": "Un módulo de aprendizaje de Dirk Schulenburg · CC BY 4.0 · No es un producto oficial de Minecraft.",
    "bossCheckHeading": "Boss Check",
    "bossCheckHint": "Resuelve la tarea sin la escalera de pistas. Entrega el Share-Link y escribe tres frases."
  },
  "glossary": {
    "befehl": {
      "term": "Orden",
      "short": "Una línea de código. El Agente hace exactamente eso."
    },
    "programm": {
      "term": "Programa",
      "short": "Muchas órdenes, de arriba hacia abajo."
    },
    "sequenz": {
      "term": "Secuencia",
      "short": "El orden de las órdenes."
    },
    "agent": {
      "term": "Agent",
      "short": "El robot en Minecraft. Solo entiende código."
    },
    "zauberwort": {
      "term": "Palabra mágica",
      "short": "Una palabra en el chat. Inicia tu programa."
    },
    "python": {
      "term": "Python",
      "short": "Un lenguaje de programación. Tu código como texto."
    },
    "bloecke": {
      "term": "Bloques",
      "short": "Tu código como bloques para arrastrar."
    },
    "fehler": {
      "term": "Error",
      "short": "El Agente te entendió mal. Lo puedes arreglar."
    }
  },
  "etappen": {
    "holz": {
      "name": "Madera",
      "badge": {
        "name": "Madera",
        "description": "Has superado todas las comprobaciones de la etapa Madera y entregaste el Boss Check."
      }
    },
    "stein": {
      "name": "Piedra",
      "badge": {
        "name": "Piedra",
        "description": "Has superado todas las comprobaciones de la etapa Piedra y entregaste el Boss Check."
      }
    },
    "eisen": {
      "name": "Hierro",
      "badge": {
        "name": "Hierro",
        "description": "Has superado todas las comprobaciones de la etapa Hierro y entregaste el Boss Check."
      }
    },
    "gold": {
      "name": "Oro",
      "badge": {
        "name": "Oro",
        "description": "Has superado todas las comprobaciones de la etapa Oro y entregaste el Boss Check."
      }
    },
    "diamant": {
      "name": "Diamante",
      "badge": {
        "name": "Diamante",
        "description": "Has superado todas las comprobaciones de la etapa Diamante y entregaste el Boss Check."
      }
    },
    "netherite": {
      "name": "Netherita",
      "badge": {
        "name": "Netherita",
        "description": "Has superado todas las comprobaciones de la etapa Netherita y entregaste el Boss Check."
      }
    },
    "enderdrache": {
      "name": "Dragón del End",
      "badge": {
        "name": "Dragón del End",
        "description": "Has superado todas las comprobaciones de la etapa Dragón del End y entregaste el Boss Check."
      }
    }
  },
  "stations": {
    "s01": {
      "title": "Die neue Welt",
      "storyShort": "Der Agent ist dein Roboter in Minecraft. Er versteht kein Deutsch, nur Code. Er startet erst, wenn du ein Zauberwort in den Chat schreibst.",
      "bridge": {
        "game": "Du tippst hi in den Chat. Der Agent kommt zu dir und geht einen Schritt.",
        "code": "Ein Befehl ist eine Zeile Code. Das Zauberwort startet das ganze Programm."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Sag hi",
          "text": "Schreibe hi in den Chat. Der Agent kommt zu dir. Dann geht er einen Schritt vor."
        },
        {
          "kind": "nochEiner",
          "title": "Dein Wort",
          "text": "Ändere das Zauberwort von hi zu hallo. Ändere die Schritte von 1 auf 3. Probier es aus."
        },
        {
          "kind": "remix",
          "title": "Noch ein Wort",
          "text": "Erfinde ein zweites Zauberwort. Der Agent soll damit etwas anderes machen. Zeig es deinem Partner oder deiner Partnerin."
        }
      ],
      "tipSolution": "Schreibe agent.teleport_to_player() und darunter agent.move(FORWARD, 3). In der letzten Zeile ersetzt du hi durch hallo. Dann tippst du hallo in den Chat.",
      "exercises": [
        {
          "prompt": "Der Agent steht unten in der Mitte. Seine Nase zeigt nach oben. Das Programm: 1 Schritt vor."
        },
        {
          "prompt": "Der Agent soll zu dir kommen und einen Schritt gehen. Die Zeile mit dem Zauberwort kommt zum Schluss."
        }
      ],
      "quiz": [
        {
          "q": "Wozu ist das Zauberwort da?",
          "answers": [
            {
              "text": "Es startet dein Programm",
              "correct": true
            },
            {
              "text": "Es öffnet den Code Builder",
              "correct": false
            },
            {
              "text": "Es speichert dein Programm",
              "correct": false
            }
          ]
        },
        {
          "q": "Welche Taste öffnet den Code Builder?",
          "answers": [
            {
              "text": "Die Taste C",
              "correct": true
            },
            {
              "text": "Die Taste E",
              "correct": false
            },
            {
              "text": "Die Taste T",
              "correct": false
            }
          ]
        },
        {
          "q": "Was macht agent.teleport_to_player()?",
          "answers": [
            {
              "text": "Der Agent kommt zu dir",
              "correct": true
            },
            {
              "text": "Der Agent geht einen Schritt vor",
              "correct": false
            },
            {
              "text": "Der Agent legt einen Block",
              "correct": false
            }
          ]
        },
        {
          "q": "Der Agent versteht …",
          "answers": [
            {
              "text": "nur Code",
              "correct": true
            },
            {
              "text": "jedes Wort im Chat",
              "correct": false
            },
            {
              "text": "Deutsch, wenn du langsam schreibst",
              "correct": false
            }
          ]
        }
      ]
    },
    "s02": {
      "title": "El orden importa",
      "storyShort": "El Agent hace las órdenes justo en el orden en que las escribes. Primero caminar y después girar no es lo mismo que primero girar y después caminar.",
      "bridge": {
        "game": "El Agent camina paso a paso y deja bloques detrás de sí.",
        "code": "Un programa es una lista de órdenes. La computadora las hace de arriba hacia abajo."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "El camino",
          "text": "Escribe la palabra mágica weg en el chat. El Agent coloca tres bloques. Mira bien: ¿dónde está la esquina?"
        },
        {
          "kind": "nochEiner",
          "title": "Más largo",
          "text": "Cambia el programa. El Agent debe colocar cinco bloques, después girar en la esquina y después dos más."
        },
        {
          "kind": "remix",
          "title": "Tu propio patrón",
          "text": "Construye tu propio patrón con bloques. Por ejemplo una Z o una U. Muéstralo a tu compañero o compañera."
        }
      ],
      "tipSolution": "Para cinco bloques: escribe agent.move(FORWARD, 1) y agent.place(BACK) cinco veces. Después agent.turn(LEFT_TURN). Después otras dos veces move y place.",
      "exercises": [
        {
          "prompt": "El Agent está abajo, en el medio. Su nariz apunta hacia arriba. El programa: 2 pasos adelante, girar a la izquierda, 1 paso adelante."
        },
        {
          "prompt": "El Agent debe venir hacia ti, caminar dos pasos, girar a la izquierda y caminar un paso más."
        }
      ],
      "quiz": [
        {
          "q": "El Agent debe caminar 3 pasos y después girar a la izquierda. ¿Cuál orden es correcto?",
          "answers": [
            {
              "text": "Primero agent.move(FORWARD, 3), después agent.turn(LEFT_TURN)",
              "correct": true
            },
            {
              "text": "Primero agent.turn(LEFT_TURN), después agent.move(FORWARD, 3)",
              "correct": false
            },
            {
              "text": "El orden no importa",
              "correct": false
            }
          ]
        },
        {
          "q": "Escribes agent.move(FORWARD, 3) dos veces, una debajo de la otra. ¿Qué hace el Agent?",
          "answers": [
            {
              "text": "Camina 6 pasos",
              "correct": true
            },
            {
              "text": "Camina 3 pasos",
              "correct": false
            },
            {
              "text": "Muestra un error",
              "correct": false
            }
          ]
        },
        {
          "q": "¿Cuándo empieza tu programa?",
          "answers": [
            {
              "text": "Cuando escribes la palabra mágica en el chat",
              "correct": true
            },
            {
              "text": "De inmediato, cuando abres el Code Builder",
              "correct": false
            },
            {
              "text": "Cuando haces clic en el Agent",
              "correct": false
            }
          ]
        },
        {
          "q": "El Agent entiende …",
          "answers": [
            {
              "text": "solo código",
              "correct": true
            },
            {
              "text": "alemán e inglés",
              "correct": false
            },
            {
              "text": "cualquier idioma",
              "correct": false
            }
          ]
        }
      ]
    },
    "s03": {
      "title": "Zauberwörter",
      "storyShort": "Ein Wort im Chat ist ein Ereignis. Jedes Zauberwort startet sein eigenes Programm. Du kannst mehrere Zauberwörter haben.",
      "bridge": {
        "game": "Du tippst weg oder turm in den Chat. Der Agent baut das, was zu dem Wort gehört.",
        "code": "Jedes Zauberwort hat einen eigenen Hut-Block. Darunter steht sein eigenes Programm."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Zwei Wörter",
          "text": "Schreibe weg in den Chat. Dann schreibe turm. Schau dir beide Bauten genau an."
        },
        {
          "kind": "nochEiner",
          "title": "Höher",
          "text": "Ändere das Programm für turm. Der Turm soll fünf Blöcke hoch werden."
        },
        {
          "kind": "remix",
          "title": "Die Brücke",
          "text": "Erfinde ein drittes Zauberwort: brücke. Der Agent baut damit einen Weg über eine Lücke."
        }
      ],
      "tipSolution": "Für fünf Blöcke schreibst du agent.place(FORWARD) und agent.move(UP, 1) abwechselnd. Am Ende kommt noch einmal agent.place(FORWARD). Zähle nach: fünf Zeilen mit place.",
      "exercises": [
        {
          "prompt": "Der Agent steht unten links. Seine Nase zeigt nach oben. Das Programm: 2 Schritte vor, rechts drehen, 2 Schritte vor."
        },
        {
          "prompt": "Der Agent kommt zu dir. Er nimmt Gras. Er geht einen Schritt und legt einen Block. Die Zeile mit dem Zauberwort kommt zum Schluss."
        }
      ],
      "quiz": [
        {
          "q": "Was ist ein Ereignis?",
          "answers": [
            {
              "text": "Etwas passiert im Spiel, zum Beispiel ein Wort im Chat",
              "correct": true
            },
            {
              "text": "Ein Fehler in deinem Programm",
              "correct": false
            },
            {
              "text": "Ein Block, den der Agent legt",
              "correct": false
            }
          ]
        },
        {
          "q": "Du hast zwei Zauberwörter. Wie viele Programme sind das?",
          "answers": [
            {
              "text": "Zwei. Jedes Wort hat sein eigenes Programm",
              "correct": true
            },
            {
              "text": "Eins. Beide Wörter starten dasselbe Programm",
              "correct": false
            },
            {
              "text": "Keins. Zwei Zauberwörter gehen nicht",
              "correct": false
            }
          ]
        },
        {
          "q": "Was macht agent.move(UP, 1)?",
          "answers": [
            {
              "text": "Der Agent geht einen Block nach oben",
              "correct": true
            },
            {
              "text": "Der Agent geht einen Schritt nach vorne",
              "correct": false
            },
            {
              "text": "Der Agent legt einen Block über sich",
              "correct": false
            }
          ]
        },
        {
          "q": "Du tippst erst weg, dann turm. Was passiert?",
          "answers": [
            {
              "text": "Erst läuft das Programm für weg, dann das für turm",
              "correct": true
            },
            {
              "text": "Beide Programme laufen gleichzeitig",
              "correct": false
            },
            {
              "text": "Nur das Programm für turm läuft",
              "correct": false
            }
          ]
        }
      ],
      "bossCheck": {
        "title": "Boss-Check Holz: Das L",
        "task": "Der Agent legt ein L aus Blöcken: 4 Blöcke geradeaus, dann Ecke, dann 2 Blöcke. Ohne Tipp-Leiter. Gib den Share-Link ab und schreibe drei Sätze: Was macht dein Programm? Warum ist die Reihenfolge wichtig? Was war schwer?"
      }
    }
  }
};
