// AUTO-GENERATED by scripts/translate.mjs — NICHT von Hand bearbeiten.
// Source: src/i18n/de.js   sourceHash: 8edb57a86d18
// Language: es   model: claude-opus-5   generated: 2026-09-03T04:40:36.924Z
// Stuetz-Ebene: Deutsch bleibt daneben sichtbar. Bei Aenderung an de.js neu erzeugen.

export default {
  "ui": {
    "appTitle": "Mundo de código",
    "tagline": "El Agent solo entiende código.",
    "home": "Vista general",
    "station": "Estación {n}",
    "ds": "Clase doble {n}",
    "support": "En tu idioma",
    "supportShow": "Mostrar ayuda en tu idioma",
    "supportHide": "Ocultar ayuda",
    "storyHeading": "La historia",
    "conceptHeading": "La idea",
    "bridgeGame": "En el juego",
    "bridgeCode": "En el código",
    "blocksLabel": "Así se ve con bloques",
    "pythonLabel": "Así se ve en Python",
    "tasksHeading": "Tus tareas en el juego",
    "taskAuftrag": "Misión",
    "taskNochEiner": "Una más",
    "taskRemix": "Remix",
    "tipsHeading": "Escalera de pistas",
    "tipStep": "Pista {n}",
    "tipSolution": "Solución",
    "tipRemixNote": "Si usas la solución: después cambia una cosa. Es obligatorio.",
    "check": "Check",
    "checkHeading": "¿Lo entendiste?",
    "predictPrompt": "¿Dónde está el Agent al final? Haz clic en la casilla.",
    "predictRight": "¡Correcto! El Agent está justo ahí.",
    "predictWrong": "Todavía no. Lee el programa de arriba abajo. ¿Hacia dónde mira?",
    "parsonsPrompt": "Pon las líneas en el orden correcto.",
    "parsonsUp": "hacia arriba",
    "parsonsDown": "hacia abajo",
    "parsonsCheck": "Comprobar",
    "parsonsRight": "¡Correcto! Ese es el orden.",
    "parsonsWrong": "Todavía no. ¿Qué tiene que hacer el Agent primero?",
    "spielstandHeading": "Punto de partida",
    "spielstandPrompt": "¿Qué sabes hacer ahora? Escribe tres frases cortas.",
    "spielstandSave": "Guardar",
    "spielstandSaved": "Guardado. Solo en este dispositivo.",
    "progress": "Has visitado {done} de {total} estaciones.",
    "next": "Siguiente",
    "prev": "Atrás",
    "play": "Leer en voz alta",
    "langLabel": "Idioma",
    "footer": "Un módulo de aprendizaje de Dirk Schulenburg · CC BY 4.0 · No es un producto oficial de Minecraft."
  },
  "glossary": {
    "befehl": {
      "term": "Befehl",
      "short": "Una línea de código. El Agente hace exactamente eso."
    },
    "programm": {
      "term": "Programm",
      "short": "Muchas órdenes, de arriba hacia abajo."
    },
    "sequenz": {
      "term": "Sequenz",
      "short": "El orden de las órdenes."
    },
    "agent": {
      "term": "Agent",
      "short": "El robot en Minecraft. Solo entiende código."
    },
    "zauberwort": {
      "term": "Zauberwort",
      "short": "Una palabra en el chat. Inicia tu programa."
    },
    "python": {
      "term": "Python",
      "short": "Un lenguaje de programación. Tu código como texto."
    },
    "bloecke": {
      "term": "Blöcke",
      "short": "Tu código como bloques para arrastrar."
    },
    "fehler": {
      "term": "Fehler",
      "short": "El Agente te entendió mal. Lo puedes arreglar."
    }
  },
  "etappen": {
    "holz": {
      "name": "Madera"
    },
    "stein": {
      "name": "Piedra"
    },
    "eisen": {
      "name": "Hierro"
    },
    "gold": {
      "name": "Oro"
    },
    "diamant": {
      "name": "Diamante"
    },
    "netherite": {
      "name": "Netherita"
    },
    "enderdrache": {
      "name": "Dragón del End"
    }
  },
  "stations": {
    "s02": {
      "title": "El orden importa",
      "storyShort": "El Agent hace las órdenes justo en el orden en que las escribes. Primero caminar y después girar no es lo mismo que primero girar y después caminar.",
      "bridge": {
        "game": "El Agent camina paso a paso y deja bloques detrás de sí.",
        "code": "Un programa es una lista de órdenes. La computadora las hace de arriba hacia abajo."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "El camino",
          "text": "Escribe la palabra mágica weg en el chat. El Agent coloca tres bloques. Mira bien: ¿dónde está la esquina?"
        },
        {
          "kind": "nochEiner",
          "title": "Más largo",
          "text": "Cambia el programa. El Agent debe colocar cinco bloques, después girar en la esquina y después dos más."
        },
        {
          "kind": "remix",
          "title": "Tu propio patrón",
          "text": "Construye tu propio patrón con bloques. Por ejemplo una Z o una U. Muéstralo a tu compañero o compañera."
        }
      ],
      "tipSolution": "Para cinco bloques: escribe agent.move(FORWARD, 1) y agent.place(BACK) cinco veces. Después agent.turn(LEFT_TURN). Después otras dos veces move y place.",
      "exercises": [
        {
          "prompt": "El Agent está abajo, en el medio. Su nariz apunta hacia arriba. El programa: 2 pasos adelante, girar a la izquierda, 1 paso adelante."
        },
        {
          "prompt": "El Agent debe venir hacia ti, caminar dos pasos, girar a la izquierda y caminar un paso más."
        }
      ],
      "quiz": [
        {
          "q": "El Agent debe caminar 3 pasos y después girar a la izquierda. ¿Cuál orden es correcto?",
          "answers": [
            {
              "text": "Primero agent.move(FORWARD, 3), después agent.turn(LEFT_TURN)",
              "correct": true
            },
            {
              "text": "Primero agent.turn(LEFT_TURN), después agent.move(FORWARD, 3)",
              "correct": false
            },
            {
              "text": "El orden no importa",
              "correct": false
            }
          ]
        },
        {
          "q": "Escribes agent.move(FORWARD, 3) dos veces, una debajo de la otra. ¿Qué hace el Agent?",
          "answers": [
            {
              "text": "Camina 6 pasos",
              "correct": true
            },
            {
              "text": "Camina 3 pasos",
              "correct": false
            },
            {
              "text": "Muestra un error",
              "correct": false
            }
          ]
        },
        {
          "q": "¿Cuándo empieza tu programa?",
          "answers": [
            {
              "text": "Cuando escribes la palabra mágica en el chat",
              "correct": true
            },
            {
              "text": "De inmediato, cuando abres el Code Builder",
              "correct": false
            },
            {
              "text": "Cuando haces clic en el Agent",
              "correct": false
            }
          ]
        },
        {
          "q": "El Agent entiende …",
          "answers": [
            {
              "text": "solo código",
              "correct": true
            },
            {
              "text": "alemán e inglés",
              "correct": false
            },
            {
              "text": "cualquier idioma",
              "correct": false
            }
          ]
        }
      ]
    }
  }
};
