// AUTO-GENERATED by scripts/translate.mjs — NICHT von Hand bearbeiten.
// Plan 2 Task 4/5: stations.s01 und stations.s03–s06 stehen hier vorübergehend auf Deutsch — Task 9 übersetzt sie.
// Manuell korrigiert 03.09.2026 (Review Task 8): glossary.*.term (DE-Reste -> ES) — bei Regeneration mit --force erneut pruefen.
// Manuell ergaenzt 03.09.2026 (Plan 2 Task 3): ui.bossCheckHeading/Hint + etappen.*.badge — de.js
// ist gewachsen, die volle Neuuebersetzung folgt erst in Plan 2 Task 9 (`translate.mjs --lang all`
// nach den neuen Stationen); bis dahin haelt dieser Handeintrag i18n-complete.test.js gruen.
// Source: src/i18n/de.js   sourceHash: 8edb57a86d18
// Language: es   model: claude-opus-5   generated: 2026-09-03T04:40:36.924Z
// Stuetz-Ebene: Deutsch bleibt daneben sichtbar. Bei Aenderung an de.js neu erzeugen.

export default {
  "ui": {
    "appTitle": "Mundo de código",
    "tagline": "El Agent solo entiende código.",
    "home": "Vista general",
    "station": "Estación {n}",
    "ds": "Clase doble {n}",
    "support": "En tu idioma",
    "supportShow": "Mostrar ayuda en tu idioma",
    "supportHide": "Ocultar ayuda",
    "storyHeading": "La historia",
    "conceptHeading": "La idea",
    "bridgeGame": "En el juego",
    "bridgeCode": "En el código",
    "blocksLabel": "Así se ve con bloques",
    "pythonLabel": "Así se ve en Python",
    "tasksHeading": "Tus tareas en el juego",
    "taskAuftrag": "Misión",
    "taskNochEiner": "Una más",
    "taskRemix": "Remix",
    "tipsHeading": "Escalera de pistas",
    "tipStep": "Pista {n}",
    "tipSolution": "Solución",
    "tipRemixNote": "Si usas la solución: después cambia una cosa. Es obligatorio.",
    "check": "Check",
    "checkHeading": "¿Lo entendiste?",
    "predictPrompt": "¿Dónde está el Agent al final? Haz clic en la casilla.",
    "predictRight": "¡Correcto! El Agent está justo ahí.",
    "predictWrong": "Todavía no. Lee el programa de arriba abajo. ¿Hacia dónde mira?",
    "parsonsPrompt": "Pon las líneas en el orden correcto.",
    "parsonsUp": "hacia arriba",
    "parsonsDown": "hacia abajo",
    "parsonsCheck": "Comprobar",
    "parsonsRight": "¡Correcto! Ese es el orden.",
    "parsonsWrong": "Todavía no. ¿Qué tiene que hacer el Agent primero?",
    "spielstandHeading": "Punto de partida",
    "spielstandPrompt": "¿Qué sabes hacer ahora? Escribe tres frases cortas.",
    "spielstandSave": "Guardar",
    "spielstandSaved": "Guardado. Solo en este dispositivo.",
    "progress": "Has visitado {done} de {total} estaciones.",
    "next": "Siguiente",
    "prev": "Atrás",
    "play": "Leer en voz alta",
    "langLabel": "Idioma",
    "footer": "Un módulo de aprendizaje de Dirk Schulenburg · CC BY 4.0 · No es un producto oficial de Minecraft.",
    "bossCheckHeading": "Boss Check",
    "bossCheckHint": "Resuelve la tarea sin la escalera de pistas. Entrega el Share-Link y escribe tres frases."
  },
  "glossary": {
    "befehl": {
      "term": "Orden",
      "short": "Una línea de código. El Agente hace exactamente eso."
    },
    "programm": {
      "term": "Programa",
      "short": "Muchas órdenes, de arriba hacia abajo."
    },
    "sequenz": {
      "term": "Secuencia",
      "short": "El orden de las órdenes."
    },
    "agent": {
      "term": "Agent",
      "short": "El robot en Minecraft. Solo entiende código."
    },
    "zauberwort": {
      "term": "Palabra mágica",
      "short": "Una palabra en el chat. Inicia tu programa."
    },
    "python": {
      "term": "Python",
      "short": "Un lenguaje de programación. Tu código como texto."
    },
    "bloecke": {
      "term": "Bloques",
      "short": "Tu código como bloques para arrastrar."
    },
    "fehler": {
      "term": "Error",
      "short": "El Agente te entendió mal. Lo puedes arreglar."
    }
  },
  "etappen": {
    "holz": {
      "name": "Madera",
      "badge": {
        "name": "Madera",
        "description": "Has superado todas las comprobaciones de la etapa Madera y entregaste el Boss Check."
      }
    },
    "stein": {
      "name": "Piedra",
      "badge": {
        "name": "Piedra",
        "description": "Has superado todas las comprobaciones de la etapa Piedra y entregaste el Boss Check."
      }
    },
    "eisen": {
      "name": "Hierro",
      "badge": {
        "name": "Hierro",
        "description": "Has superado todas las comprobaciones de la etapa Hierro y entregaste el Boss Check."
      }
    },
    "gold": {
      "name": "Oro",
      "badge": {
        "name": "Oro",
        "description": "Has superado todas las comprobaciones de la etapa Oro y entregaste el Boss Check."
      }
    },
    "diamant": {
      "name": "Diamante",
      "badge": {
        "name": "Diamante",
        "description": "Has superado todas las comprobaciones de la etapa Diamante y entregaste el Boss Check."
      }
    },
    "netherite": {
      "name": "Netherita",
      "badge": {
        "name": "Netherita",
        "description": "Has superado todas las comprobaciones de la etapa Netherita y entregaste el Boss Check."
      }
    },
    "enderdrache": {
      "name": "Dragón del End",
      "badge": {
        "name": "Dragón del End",
        "description": "Has superado todas las comprobaciones de la etapa Dragón del End y entregaste el Boss Check."
      }
    }
  },
  "stations": {
    "s01": {
      "title": "Die neue Welt",
      "storyShort": "Der Agent ist dein Roboter in Minecraft. Er versteht kein Deutsch, nur Code. Er startet erst, wenn du ein Zauberwort in den Chat schreibst.",
      "bridge": {
        "game": "Du tippst hi in den Chat. Der Agent kommt zu dir und geht einen Schritt.",
        "code": "Ein Befehl ist eine Zeile Code. Das Zauberwort startet das ganze Programm."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Sag hi",
          "text": "Schreibe hi in den Chat. Der Agent kommt zu dir. Dann geht er einen Schritt vor."
        },
        {
          "kind": "nochEiner",
          "title": "Dein Wort",
          "text": "Ändere das Zauberwort von hi zu hallo. Ändere die Schritte von 1 auf 3. Probier es aus."
        },
        {
          "kind": "remix",
          "title": "Noch ein Wort",
          "text": "Erfinde ein zweites Zauberwort. Der Agent soll damit etwas anderes machen. Zeig es deinem Partner oder deiner Partnerin."
        }
      ],
      "tipSolution": "Schreibe agent.teleport_to_player() und darunter agent.move(FORWARD, 3). In der letzten Zeile ersetzt du \"hi\" durch \"hallo\". Nur das Wort in den Anführungszeichen. Dann tippst du hallo in den Chat.",
      "exercises": [
        {
          "prompt": "Der Agent steht unten in der Mitte. Seine Nase zeigt nach oben. Das Programm: 1 Schritt vor."
        },
        {
          "prompt": "Der Agent soll zu dir kommen und einen Schritt gehen. Die Zeile mit dem Zauberwort kommt zum Schluss."
        }
      ],
      "quiz": [
        {
          "q": "Wozu ist das Zauberwort da?",
          "answers": [
            {
              "text": "Es startet dein Programm",
              "correct": true
            },
            {
              "text": "Es öffnet den Code Builder",
              "correct": false
            },
            {
              "text": "Es speichert dein Programm",
              "correct": false
            }
          ]
        },
        {
          "q": "Welche Taste öffnet den Code Builder?",
          "answers": [
            {
              "text": "Die Taste C",
              "correct": true
            },
            {
              "text": "Die Taste E",
              "correct": false
            },
            {
              "text": "Die Taste T",
              "correct": false
            }
          ]
        },
        {
          "q": "Was macht agent.teleport_to_player()?",
          "answers": [
            {
              "text": "Der Agent kommt zu dir",
              "correct": true
            },
            {
              "text": "Der Agent geht einen Schritt vor",
              "correct": false
            },
            {
              "text": "Der Agent legt einen Block",
              "correct": false
            }
          ]
        },
        {
          "q": "Der Agent versteht …",
          "answers": [
            {
              "text": "nur Code",
              "correct": true
            },
            {
              "text": "jedes Wort im Chat",
              "correct": false
            },
            {
              "text": "Deutsch, wenn du langsam schreibst",
              "correct": false
            }
          ]
        }
      ]
    },
    "s02": {
      "title": "El orden importa",
      "storyShort": "El Agent hace las órdenes justo en el orden en que las escribes. Primero caminar y después girar no es lo mismo que primero girar y después caminar.",
      "bridge": {
        "game": "El Agent camina paso a paso y deja bloques detrás de sí.",
        "code": "Un programa es una lista de órdenes. La computadora las hace de arriba hacia abajo."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "El camino",
          "text": "Escribe la palabra mágica weg en el chat. El Agent coloca tres bloques. Mira bien: ¿dónde está la esquina?"
        },
        {
          "kind": "nochEiner",
          "title": "Más largo",
          "text": "Cambia el programa. El Agent debe colocar cinco bloques, después girar en la esquina y después dos más."
        },
        {
          "kind": "remix",
          "title": "Tu propio patrón",
          "text": "Construye tu propio patrón con bloques. Por ejemplo una Z o una U. Muéstralo a tu compañero o compañera."
        }
      ],
      "tipSolution": "Para cinco bloques: escribe agent.move(FORWARD, 1) y agent.place(BACK) cinco veces. Después agent.turn(LEFT_TURN). Después otras dos veces move y place.",
      "exercises": [
        {
          "prompt": "El Agent está abajo, en el medio. Su nariz apunta hacia arriba. El programa: 2 pasos adelante, girar a la izquierda, 1 paso adelante."
        },
        {
          "prompt": "El Agent debe venir hacia ti, caminar dos pasos, girar a la izquierda y caminar un paso más."
        }
      ],
      "quiz": [
        {
          "q": "El Agent debe caminar 3 pasos y después girar a la izquierda. ¿Cuál orden es correcto?",
          "answers": [
            {
              "text": "Primero agent.move(FORWARD, 3), después agent.turn(LEFT_TURN)",
              "correct": true
            },
            {
              "text": "Primero agent.turn(LEFT_TURN), después agent.move(FORWARD, 3)",
              "correct": false
            },
            {
              "text": "El orden no importa",
              "correct": false
            }
          ]
        },
        {
          "q": "Escribes agent.move(FORWARD, 3) dos veces, una debajo de la otra. ¿Qué hace el Agent?",
          "answers": [
            {
              "text": "Camina 6 pasos",
              "correct": true
            },
            {
              "text": "Camina 3 pasos",
              "correct": false
            },
            {
              "text": "Muestra un error",
              "correct": false
            }
          ]
        },
        {
          "q": "¿Cuándo empieza tu programa?",
          "answers": [
            {
              "text": "Cuando escribes la palabra mágica en el chat",
              "correct": true
            },
            {
              "text": "De inmediato, cuando abres el Code Builder",
              "correct": false
            },
            {
              "text": "Cuando haces clic en el Agent",
              "correct": false
            }
          ]
        },
        {
          "q": "El Agent entiende …",
          "answers": [
            {
              "text": "solo código",
              "correct": true
            },
            {
              "text": "alemán e inglés",
              "correct": false
            },
            {
              "text": "cualquier idioma",
              "correct": false
            }
          ]
        }
      ]
    },
    "s03": {
      "title": "Zauberwörter",
      "storyShort": "Ein Wort im Chat ist ein Ereignis. Jedes Zauberwort startet sein eigenes Programm. Du kannst mehrere Zauberwörter haben.",
      "bridge": {
        "game": "Du tippst weg oder turm in den Chat. Der Agent baut den Weg oder den Turm.",
        "code": "Jedes Zauberwort hat einen eigenen Hut-Block. Darunter steht sein eigenes Programm."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Zwei Wörter",
          "text": "Schreibe weg in den Chat. Dann schreibe turm. Der Weg ist hier kürzer als in Station 2. Schau dir beides genau an."
        },
        {
          "kind": "nochEiner",
          "title": "Höher",
          "text": "Ändere das Programm für turm. Der Turm soll fünf Blöcke hoch werden."
        },
        {
          "kind": "remix",
          "title": "Die Brücke",
          "text": "Erfinde ein drittes Zauberwort: brücke. Der Agent baut damit einen Weg über eine Lücke."
        }
      ],
      "tipSolution": "Für fünf Blöcke schreibst du agent.place(FORWARD) und agent.move(UP, 1) abwechselnd. Am Ende kommt noch einmal agent.place(FORWARD). Zähle nach: fünf Zeilen mit place.",
      "exercises": [
        {
          "prompt": "Der Agent steht unten links. Seine Nase zeigt nach oben. Das Programm: 2 Schritte vor, rechts drehen, 2 Schritte vor."
        },
        {
          "prompt": "Der Agent kommt zu dir. Er nimmt Gras. Er geht einen Schritt und legt einen Block. Die Zeile mit dem Zauberwort kommt zum Schluss."
        }
      ],
      "quiz": [
        {
          "q": "Was ist ein Ereignis?",
          "answers": [
            {
              "text": "Etwas passiert im Spiel, zum Beispiel ein Wort im Chat",
              "correct": true
            },
            {
              "text": "Ein Fehler in deinem Programm",
              "correct": false
            },
            {
              "text": "Ein Block, den der Agent legt",
              "correct": false
            }
          ]
        },
        {
          "q": "Du hast zwei Zauberwörter. Wie viele Programme sind das?",
          "answers": [
            {
              "text": "Zwei. Jedes Wort hat sein eigenes Programm",
              "correct": true
            },
            {
              "text": "Eins. Beide Wörter starten dasselbe Programm",
              "correct": false
            },
            {
              "text": "Keins. Zwei Zauberwörter gehen nicht",
              "correct": false
            }
          ]
        },
        {
          "q": "Was macht agent.move(UP, 1)?",
          "answers": [
            {
              "text": "Der Agent geht einen Block nach oben",
              "correct": true
            },
            {
              "text": "Der Agent geht einen Schritt nach vorne",
              "correct": false
            },
            {
              "text": "Der Agent legt einen Block über sich",
              "correct": false
            }
          ]
        },
        {
          "q": "Du tippst erst weg, dann turm. Was passiert?",
          "answers": [
            {
              "text": "Erst läuft das Programm für weg, dann das für turm",
              "correct": true
            },
            {
              "text": "Beide Programme laufen gleichzeitig",
              "correct": false
            },
            {
              "text": "Nur das Programm für turm läuft",
              "correct": false
            }
          ]
        }
      ],
      "bossCheck": {
        "title": "Boss-Check Holz",
        "subtitle": "Das L",
        "task": "Der Agent legt ein L: erst 4 Blöcke geradeaus, dann 2 um die Ecke. Was macht dein Programm? Warum ist die Reihenfolge wichtig? Was war schwer?"
      }
    },
    "s04": {
      "title": "Wiederholen",
      "storyShort": "Zehnmal dasselbe zu schreiben ist mühsam. Dafür gibt es die Schleife. Du schreibst die Zeilen einmal. Der Computer wiederholt sie für dich.",
      "bridge": {
        "game": "Du tippst mauer in den Chat. Der Agent legt zehn Blöcke in einer Reihe.",
        "code": "Eine Schleife wiederholt zwei Zeilen zehnmal. Du schreibst sie nur einmal."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Die Mauer",
          "text": "Schreibe mauer in den Chat. Der Agent baut eine Mauer aus zehn Blöcken. Zähle die Blöcke nach."
        },
        {
          "kind": "nochEiner",
          "title": "Länger und anders",
          "text": "Ändere die Zahl von 10 auf 20. Nimm eine andere Blockart, zum Beispiel Holz. Probier es aus."
        },
        {
          "kind": "remix",
          "title": "Zwei Mauern",
          "text": "Baue zwei Mauern mit einer Lücke dazwischen. Zeig es deinem Partner oder deiner Partnerin."
        }
      ],
      "tipSolution": "Schreibe for index in range(20): in die Schleifenzeile. Die zwei Zeilen darunter bleiben eingerückt. Für Holz nimmst du agent.set_item(PLANKS_OAK, 64, 1). Zähle nach: eine Schleife, zwei Zeilen im Bauch.",
      "exercises": [
        {
          "prompt": "Der Agent steht unten in der Mitte. Seine Nase zeigt nach oben. Das Programm: 3 Schritte vor."
        },
        {
          "prompt": "Der Agent kommt zu dir und nimmt Bruchstein. Dann wiederholt die Schleife zwei Zeilen. Die Einrückung gehört zur Zeile."
        }
      ],
      "quiz": [
        {
          "q": "Was spart die Schleife?",
          "answers": [
            {
              "text": "Viele gleiche Zeilen",
              "correct": true
            },
            {
              "text": "Blöcke im Rucksack",
              "correct": false
            },
            {
              "text": "Platz in der Welt",
              "correct": false
            }
          ]
        },
        {
          "q": "Wie oft läuft eine Schleife mit range(10)?",
          "answers": [
            {
              "text": "Zehnmal",
              "correct": true
            },
            {
              "text": "Neunmal",
              "correct": false
            },
            {
              "text": "Elfmal",
              "correct": false
            }
          ]
        },
        {
          "q": "Bei welcher Zahl fängt der Computer an zu zählen?",
          "answers": [
            {
              "text": "Bei 0",
              "correct": true
            },
            {
              "text": "Bei 1",
              "correct": false
            },
            {
              "text": "Bei 10",
              "correct": false
            }
          ]
        },
        {
          "q": "Was passiert bei range(0)?",
          "answers": [
            {
              "text": "Nichts. Die Schleife läuft keinmal",
              "correct": true
            },
            {
              "text": "Die Schleife läuft einmal",
              "correct": false
            },
            {
              "text": "Der Agent meldet einen Fehler",
              "correct": false
            }
          ]
        }
      ]
    },
    "s05": {
      "title": "Schleife in der Schleife",
      "storyShort": "Eine Schleife kann in einer Schleife stehen. Die innere Schleife baut eine Reihe. Die äußere Schleife wiederholt die Reihe. So wird aus der Reihe eine Wand.",
      "bridge": {
        "game": "Du tippst wand in den Chat. Der Agent baut eine Wand aus drei Reihen.",
        "code": "Eine Schleife steht im Bauch der anderen. Innen die Reihe, außen die Ebenen."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Die Wand",
          "text": "Schreibe wand in den Chat. Der Agent baut eine Wand: 6 Blöcke breit, 3 hoch."
        },
        {
          "kind": "nochEiner",
          "title": "Größer",
          "text": "Ändere die Wand auf 8 Blöcke breit und 4 hoch. Welche zwei Zahlen musst du ändern?"
        },
        {
          "kind": "remix",
          "title": "Das Fenster",
          "text": "Baue eine Wand mit einem Fenster. Eine Reihe wird dafür kürzer. Zeig es deinem Partner oder deiner Partnerin."
        }
      ],
      "tipSolution": "Schreibe for index in range(4): in die äußere Schleife. Das ist die Höhe. Schreibe for index2 in range(8): in die innere Schleife. Das ist die Breite. Nach den zwei Drehungen kommt ein Schritt vor. So steht der Agent wieder über der Reihe. Zähle nach: zwei Schleifen, eine im Bauch der anderen.",
      "exercises": [
        {
          "prompt": "Der Agent steht unten links. Seine Nase zeigt nach oben. Das Programm: 2 Schritte vor, links drehen, links drehen, 1 Schritt vor."
        },
        {
          "prompt": "Der Agent hat schon Bruchstein dabei. Jetzt kommt die Wand: außen die Ebenen, innen die Reihe. Die Drehungen und der Schritt danach fehlen hier. Achte auf die Einrückung."
        }
      ],
      "quiz": [
        {
          "q": "Die Wand ist 6 Blöcke breit und 3 hoch. Wie viele Blöcke sind das?",
          "answers": [
            {
              "text": "18 Blöcke",
              "correct": true
            },
            {
              "text": "9 Blöcke",
              "correct": false
            },
            {
              "text": "24 Blöcke",
              "correct": false
            }
          ]
        },
        {
          "q": "Was macht die innere Schleife?",
          "answers": [
            {
              "text": "Sie baut eine Reihe",
              "correct": true
            },
            {
              "text": "Sie geht eine Ebene hoch",
              "correct": false
            },
            {
              "text": "Sie dreht den Agenten um",
              "correct": false
            }
          ]
        },
        {
          "q": "Warum dreht der Agent zweimal nach links?",
          "answers": [
            {
              "text": "Damit er zurückschaut und die nächste Reihe baut",
              "correct": true
            },
            {
              "text": "Damit er schneller läuft",
              "correct": false
            },
            {
              "text": "Damit er einen Block legen kann",
              "correct": false
            }
          ]
        },
        {
          "q": "Welche Schleife läuft zuerst ganz durch?",
          "answers": [
            {
              "text": "Die innere. Sie baut erst die ganze Reihe",
              "correct": true
            },
            {
              "text": "Die äußere. Sie geht erst ganz nach oben",
              "correct": false
            },
            {
              "text": "Beide laufen gleichzeitig",
              "correct": false
            }
          ]
        }
      ]
    },
    "s06": {
      "title": "Das Haus",
      "storyShort": "Ein Haus hat vier Wände. Du kopierst die Wand nicht viermal. Du legst eine Schleife außen herum. Nach jeder Seite dreht sich der Agent.",
      "bridge": {
        "game": "Du tippst haus in den Chat. Der Agent baut einen Ring aus vier Seiten.",
        "code": "Die äußere Schleife läuft viermal. Nach jeder Seite dreht der Agent um die Ecke."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Der Ring",
          "text": "Schreibe haus in den Chat. Der Agent baut einen Ring: 5 Blöcke pro Seite."
        },
        {
          "kind": "nochEiner",
          "title": "Höher",
          "text": "Der Ring soll 3 Blöcke hoch werden. Dafür brauchst du eine dritte Schleife."
        },
        {
          "kind": "remix",
          "title": "Die Tür",
          "text": "Lass in einer Wand eine Lücke als Tür. Zeig dein Haus deinem Partner oder deiner Partnerin."
        }
      ],
      "tipSolution": "Schreibe for index3 in range(3): ganz nach außen. Der ganze Ring steht eingerückt darin. Danach kommt agent.move(UP, 1). Zähle nach: drei Schleifen, eine in der anderen.",
      "exercises": [
        {
          "prompt": "Der Agent steht unten in der Mitte. Seine Nase zeigt nach oben. Das Programm: 2 Schritte vor, links drehen. Dann noch einmal: 2 Schritte vor, links drehen. Zum Schluss 2 Schritte vor."
        },
        {
          "prompt": "Der Agent baut einen Ring. Innen eine Seite, außen die vier Seiten. Die Drehung gehört zur äußeren Schleife."
        }
      ],
      "quiz": [
        {
          "q": "Wie viele Seiten baut range(4)?",
          "answers": [
            {
              "text": "Vier",
              "correct": true
            },
            {
              "text": "Drei",
              "correct": false
            },
            {
              "text": "Fünf",
              "correct": false
            }
          ]
        },
        {
          "q": "Wo steht agent.turn(LEFT_TURN)?",
          "answers": [
            {
              "text": "In der äußeren Schleife, nach der inneren",
              "correct": true
            },
            {
              "text": "In der inneren Schleife, bei jedem Block",
              "correct": false
            },
            {
              "text": "Ganz oben, vor beiden Schleifen",
              "correct": false
            }
          ]
        },
        {
          "q": "Warum dreht der Agent nur einmal pro Wand?",
          "answers": [
            {
              "text": "Weil eine Ecke eine Vierteldrehung ist",
              "correct": true
            },
            {
              "text": "Weil er sonst zu langsam wird",
              "correct": false
            },
            {
              "text": "Weil er sonst keine Blöcke mehr hat",
              "correct": false
            }
          ]
        },
        {
          "q": "Der Ring hat 4 Seiten mit je 5 Blöcken. Wie viele Blöcke sind das?",
          "answers": [
            {
              "text": "20 Blöcke",
              "correct": true
            },
            {
              "text": "16 Blöcke",
              "correct": false
            },
            {
              "text": "25 Blöcke",
              "correct": false
            }
          ]
        }
      ],
      "bossCheck": {
        "title": "Boss-Check Stein",
        "subtitle": "Der Zaun",
        "task": "Baue einen Zaun um dich herum. Der Ring hat 8 Blöcke pro Seite. Was spart die Schleife? Wie viele Befehle wären es ohne Schleife?"
      }
    }
  }
};
