// AUTO-GENERATED by scripts/translate.mjs — NICHT von Hand bearbeiten.
// Source: src/i18n/de.js   sourceHash: 8114d96e4319
// Language: it   model: claude-opus-5   generated: 2026-09-03T21:28:33.003Z
// Stuetz-Ebene: Deutsch bleibt daneben sichtbar. Bei Aenderung an de.js neu erzeugen.
// Handkorrektur 2026-09-03 (Review T9): zwei durchgaengige Korrekturen, deshalb hier gebuendelt
// statt an jeder Zeile: (1) "Agente" statt "Agent" an 17 Stellen (Kanon AGENT_CANON in
// scripts/translate.mjs), (2) "nella chat" statt "nel chat" an 4 Stellen in s03 (chat ist
// feminin). Einzelkorrekturen sind unten in der Zeile davor markiert.

export default {
  "ui": {
    "appTitle": "Mondo del codice",
    "tagline": "L'Agente capisce solo il codice.",
    "home": "Panoramica",
    "station": "Stazione {n}",
    "ds": "Lezione doppia {n}",
    "support": "Nella tua lingua",
    "supportShow": "Mostra l'aiuto nella tua lingua",
    "supportHide": "Nascondi l'aiuto",
    "storyHeading": "La storia",
    "conceptHeading": "L'idea",
    "bridgeGame": "Nel gioco",
    "bridgeCode": "Nel codice",
    "blocksLabel": "Ecco come appare a blocchi",
    "pythonLabel": "Ecco come appare in Python",
    "tasksHeading": "I tuoi compiti nel gioco",
    "taskAuftrag": "Compito",
    "taskNochEiner": "Un altro",
    "taskRemix": "Remix",
    "tipsHeading": "Scala dei suggerimenti",
    "tipStep": "Suggerimento {n}",
    "tipSolution": "Soluzione",
    "tipRemixNote": "Se prendi la soluzione: dopo devi cambiare una cosa. È obbligatorio.",
    "check": "Check",
    "checkHeading": "Hai capito?",
    "predictPrompt": "Dove si trova l'Agente alla fine? Clicca sulla casella.",
    "predictRight": "Giusto! L'Agente è proprio lì.",
    "predictWrong": "Non ancora. Leggi il programma dall'alto verso il basso. Da che parte guarda?",
    "parsonsPrompt": "Metti le righe nell'ordine giusto.",
    "parsonsUp": "in su",
    "parsonsDown": "in giù",
    "parsonsCheck": "Verifica",
    "parsonsRight": "Giusto! Questo è l'ordine.",
    "parsonsWrong": "Non ancora. Che cosa deve fare per primo l'Agente?",
    "spielstandHeading": "Punto della situazione",
    "spielstandPrompt": "Che cosa sai fare adesso? Scrivi tre frasi brevi.",
    "spielstandSave": "Salva",
    "spielstandSaved": "Salvato. Solo su questo dispositivo.",
    "progress": "Hai visitato {done} stazioni su {total}.",
    "next": "Avanti",
    "prev": "Indietro",
    "play": "Leggi ad alta voce",
    "langLabel": "Lingua",
    "footer": "Un modulo didattico di Dirk Schulenburg · CC BY 4.0 · Non è un prodotto ufficiale Minecraft.",
    // Handkorrektur 2026-09-03 (Review T9): Produktbegriff "Boss-Check" wie in den bossCheck-Titeln. Vorher: "Check del boss".
    "bossCheckHeading": "Boss-Check",
    "bossCheckHint": "Risolvi il compito senza la scala dei suggerimenti. Consegna il link di condivisione e scrivi tre frasi."
  },
  "glossary": {
    "befehl": {
      "term": "Comando",
      "short": "Una riga di codice. L'Agente fa esattamente questo."
    },
    "programm": {
      "term": "Programma",
      "short": "Tanti comandi, dall'alto verso il basso."
    },
    "sequenz": {
      "term": "Sequenza",
      "short": "L'ordine dei comandi."
    },
    "agent": {
      "term": "Agente",
      "short": "Il robot in Minecraft. Capisce solo il codice."
    },
    "zauberwort": {
      "term": "Parola magica",
      "short": "Una parola nella chat. Fa partire il tuo programma."
    },
    "python": {
      "term": "Python",
      "short": "Un linguaggio di programmazione. Il tuo codice come testo."
    },
    "bloecke": {
      "term": "Blocchi",
      "short": "Il tuo codice come mattoncini da trascinare."
    },
    "fehler": {
      "term": "Errore",
      "short": "L'Agente ti ha capito male. Puoi sistemarlo."
    }
  },
  "etappen": {
    "holz": {
      "name": "Legno",
      "badge": {
        "name": "Legno",
        // Handkorrektur 2026-09-04 (Re-Review T9): "il Boss-Check" als feststehender Begriff (Grossschreibung), nicht "il boss-check".
        "description": "Hai superato tutti i check della tappa Legno e hai consegnato il Boss-Check."
      }
    },
    "stein": {
      "name": "Pietra",
      "badge": {
        "name": "Pietra",
        // Handkorrektur 2026-09-04 (Re-Review T9): "il Boss-Check" als feststehender Begriff (Grossschreibung), nicht "il boss-check".
        "description": "Hai superato tutti i check della tappa Pietra e hai consegnato il Boss-Check."
      }
    },
    "eisen": {
      "name": "Ferro",
      "badge": {
        "name": "Ferro",
        // Handkorrektur 2026-09-04 (Re-Review T9): "il Boss-Check" als feststehender Begriff (Grossschreibung), nicht "il boss-check".
        "description": "Hai superato tutti i check della tappa Ferro e hai consegnato il Boss-Check."
      }
    },
    "gold": {
      "name": "Oro",
      "badge": {
        "name": "Oro",
        // Handkorrektur 2026-09-04 (Re-Review T9): "il Boss-Check" als feststehender Begriff (Grossschreibung), nicht "il boss-check".
        "description": "Hai superato tutti i check della tappa Oro e hai consegnato il Boss-Check."
      }
    },
    "diamant": {
      "name": "Diamante",
      "badge": {
        "name": "Diamante",
        // Handkorrektur 2026-09-04 (Re-Review T9): "il Boss-Check" als feststehender Begriff (Grossschreibung), nicht "il boss-check".
        "description": "Hai superato tutti i check della tappa Diamante e hai consegnato il Boss-Check."
      }
    },
    "netherite": {
      "name": "Netherite",
      "badge": {
        "name": "Netherite",
        // Handkorrektur 2026-09-04 (Re-Review T9): "il Boss-Check" als feststehender Begriff (Grossschreibung), nicht "il boss-check".
        "description": "Hai superato tutti i check della tappa Netherite e hai consegnato il Boss-Check."
      }
    },
    "enderdrache": {
      "name": "Drago dell'End",
      "badge": {
        "name": "Drago dell'End",
        // Handkorrektur 2026-09-04 (Re-Review T9): "il Boss-Check" als feststehender Begriff (Grossschreibung), nicht "il boss-check".
        "description": "Hai superato tutti i check della tappa Drago dell'End e hai consegnato il Boss-Check."
      }
    }
  },
  "stations": {
    "s01": {
      "title": "Il mondo nuovo",
      "storyShort": "L'Agente è il tuo robot in Minecraft. Non capisce il tedesco, solo il codice. Parte solo quando scrivi una parola magica nella chat.",
      "bridge": {
        "game": "Scrivi hi nella chat. L'Agente viene da te e fa un passo.",
        "code": "Un comando è una riga di codice. La parola magica avvia tutto il programma."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Di' hi",
          "text": "Scrivi hi nella chat. L'Agente viene da te. Poi fa un passo avanti."
        },
        {
          "kind": "nochEiner",
          "title": "La tua parola",
          "text": "Cambia la parola magica da hi a hallo. Cambia i passi da 1 a 3. Prova."
        },
        {
          "kind": "remix",
          "title": "Un'altra parola",
          "text": "Inventa una seconda parola magica. Con questa l'Agente deve fare qualcosa di diverso. Mostralo al tuo compagno o alla tua compagna."
        }
      ],
      "tipSolution": "Scrivi agent.teleport_to_player() e sotto agent.move(FORWARD, 3). Nell'ultima riga sostituisci «hi» con «hallo». Solo la parola tra virgolette. Poi scrivi hallo nella chat.",
      "exercises": [
        {
          "prompt": "L'Agente sta in basso al centro. Il suo naso guarda in alto. Il programma: 1 passo avanti."
        },
        {
          "prompt": "L'Agente deve venire da te e fare un passo. La riga con la parola magica va alla fine."
        }
      ],
      "quiz": [
        {
          "q": "A cosa serve la parola magica?",
          "answers": [
            {
              "text": "Avvia il tuo programma",
              "correct": true
            },
            {
              "text": "Apre il Code Builder",
              "correct": false
            },
            {
              "text": "Salva il tuo programma",
              "correct": false
            }
          ]
        },
        {
          "q": "Quale tasto apre il Code Builder?",
          "answers": [
            {
              "text": "Il tasto C",
              "correct": true
            },
            {
              "text": "Il tasto E",
              "correct": false
            },
            {
              "text": "Il tasto T",
              "correct": false
            }
          ]
        },
        {
          "q": "Che cosa fa agent.teleport_to_player()?",
          "answers": [
            {
              "text": "L'Agente viene da te",
              "correct": true
            },
            {
              "text": "L'Agente fa un passo avanti",
              "correct": false
            },
            {
              "text": "L'Agente posa un blocco",
              "correct": false
            }
          ]
        },
        {
          "q": "L'Agente capisce …",
          "answers": [
            {
              "text": "solo il codice",
              "correct": true
            },
            {
              "text": "ogni parola nella chat",
              "correct": false
            },
            {
              "text": "il tedesco, se scrivi lentamente",
              "correct": false
            }
          ]
        }
      ]
    },
    "s02": {
      "title": "L'ordine conta",
      "storyShort": "L'Agente esegue i comandi esattamente nell'ordine in cui li scrivi. Prima camminare e poi girare non è la stessa cosa che prima girare e poi camminare.",
      "bridge": {
        "game": "L'Agente avanza passo dopo passo e posa blocchi dietro di sé.",
        "code": "Un programma è una lista di comandi. Il computer li esegue dall'alto verso il basso."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Il percorso",
          "text": "Scrivi la parola magica weg nella chat. L'Agente posa quattro blocchi. Guarda bene: dov'è l'angolo?"
        },
        {
          "kind": "nochEiner",
          "title": "Più lungo",
          "text": "Cambia il programma. L'Agente posa cinque blocchi dritti, poi fa l'angolo, poi altri due."
        },
        {
          "kind": "remix",
          "title": "Il tuo disegno",
          "text": "Costruisci un tuo disegno con i blocchi. Per esempio una Z o una U. Mostralo al tuo compagno o alla tua compagna."
        }
      ],
      "tipSolution": "Per cinque blocchi: scrivi agent.move(FORWARD, 1) e agent.place(BACK) cinque volte. Poi agent.turn(LEFT_TURN). Dopo servono ancora tre coppie di move e place. La prima coppia posa il blocco dell'angolo.",
      "exercises": [
        {
          "prompt": "L'Agente sta in basso al centro. Il suo naso punta verso l'alto. Il programma: 2 passi avanti, gira a sinistra, 1 passo avanti."
        },
        {
          "prompt": "L'Agente deve venire da te, fare due passi, girare a sinistra e fare ancora un passo."
        }
      ],
      "quiz": [
        {
          "q": "L'Agente deve fare 3 passi e poi girare a sinistra. Quale ordine è corretto?",
          "answers": [
            {
              "text": "Prima agent.move(FORWARD, 3), poi agent.turn(LEFT_TURN)",
              "correct": true
            },
            {
              "text": "Prima agent.turn(LEFT_TURN), poi agent.move(FORWARD, 3)",
              "correct": false
            },
            {
              "text": "L'ordine non conta",
              "correct": false
            }
          ]
        },
        {
          "q": "Scrivi agent.move(FORWARD, 3) due volte, una sotto l'altra. Cosa fa l'Agente?",
          "answers": [
            {
              "text": "Fa 6 passi",
              "correct": true
            },
            {
              "text": "Fa 3 passi",
              "correct": false
            },
            {
              "text": "Segnala un errore",
              "correct": false
            }
          ]
        },
        {
          "q": "Quando parte il tuo programma?",
          "answers": [
            {
              "text": "Quando scrivi la parola magica nella chat",
              "correct": true
            },
            {
              "text": "Subito, quando apri il Code Builder",
              "correct": false
            },
            {
              "text": "Quando clicchi sull'Agente",
              "correct": false
            }
          ]
        },
        {
          "q": "L'Agente capisce …",
          "answers": [
            {
              "text": "solo il codice",
              "correct": true
            },
            {
              "text": "tedesco e inglese",
              "correct": false
            },
            {
              "text": "ogni lingua",
              "correct": false
            }
          ]
        }
      ]
    },
    "s03": {
      "title": "Parole magiche",
      "storyShort": "Una parola nella chat è un evento. Ogni parola magica avvia il suo programma. Puoi avere più parole magiche.",
      "bridge": {
        "game": "Tu scrivi weg oppure turm nella chat. L'Agente costruisce la strada o la torre.",
        "code": "Ogni parola magica ha il suo blocco a cappello. Sotto c'è il suo programma."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Due parole",
          "text": "Scrivi weg nella chat. Poi scrivi turm. Qui la strada è più corta che nella stazione 2. Guarda bene tutte e due le cose."
        },
        {
          "kind": "nochEiner",
          "title": "Più alta",
          "text": "Cambia il programma per turm. La torre deve diventare alta cinque blocchi."
        },
        {
          "kind": "remix",
          "title": "Il ponte",
          "text": "Inventa una terza parola magica: bruecke. Le parole magiche non hanno umlaut. Con questa parola l'Agente costruisce una strada sopra un buco."
        }
      ],
      "tipSolution": "Per cinque blocchi scrivi agent.place(FORWARD) e agent.move(UP, 1) uno dopo l'altro, alternati. Alla fine metti ancora una volta agent.place(FORWARD). Conta: cinque righe con place.",
      "exercises": [
        {
          "prompt": "L'Agente sta in basso a sinistra. Il suo naso guarda verso l'alto. Il programma: 2 passi avanti, gira a destra, 2 passi avanti."
        },
        {
          "prompt": "L'Agente viene da te. Prende erba. Fa un passo e mette un blocco. La riga con la parola magica viene per ultima."
        }
      ],
      "quiz": [
        {
          "q": "Che cos'è un evento?",
          "answers": [
            {
              "text": "Qualcosa succede nel gioco, per esempio una parola nella chat",
              "correct": true
            },
            {
              "text": "Un errore nel tuo programma",
              "correct": false
            },
            {
              "text": "Un blocco che l'Agente mette",
              "correct": false
            }
          ]
        },
        {
          "q": "Hai due parole magiche. Quanti programmi sono?",
          "answers": [
            {
              "text": "Due. Ogni parola ha il suo programma",
              "correct": true
            },
            {
              "text": "Uno. Le due parole avviano lo stesso programma",
              "correct": false
            },
            {
              "text": "Nessuno. Due parole magiche non si possono avere",
              "correct": false
            }
          ]
        },
        {
          "q": "Che cosa fa agent.move(UP, 1)?",
          "answers": [
            {
              "text": "L'Agente va su di un blocco",
              "correct": true
            },
            {
              "text": "L'Agente fa un passo avanti",
              "correct": false
            },
            {
              "text": "L'Agente mette un blocco sopra di sé",
              "correct": false
            }
          ]
        },
        {
          "q": "Prima scrivi weg, poi turm. Che cosa succede?",
          "answers": [
            {
              "text": "Prima parte il programma per weg, poi quello per turm",
              "correct": true
            },
            {
              "text": "I due programmi partono nello stesso momento",
              "correct": false
            },
            {
              "text": "Parte solo il programma per turm",
              "correct": false
            }
          ]
        }
      ],
      "bossCheck": {
        "title": "Boss-Check Legno",
        "subtitle": "La L",
        "task": "L'Agente forma una L: prima 4 blocchi dritti, poi 2 dietro l'angolo. Che cosa fa il tuo programma? Perché l'ordine è importante? Che cosa è stato difficile?"
      }
    },
    "s04": {
      "title": "Ripetere",
      "storyShort": "Scrivere dieci volte la stessa cosa è faticoso. Per questo esiste il ciclo. Tu scrivi le righe una volta sola. Il computer le ripete per te.",
      "bridge": {
        "game": "Scrivi mauer nella chat. L'Agente mette dieci blocchi in fila.",
        "code": "Un ciclo ripete due righe dieci volte. Tu le scrivi una volta sola."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Il muro",
          "text": "Scrivi mauer nella chat. L'Agente costruisce un muro di dieci blocchi. Conta i blocchi."
        },
        {
          "kind": "nochEiner",
          "title": "Più lungo e diverso",
          // Handkorrektur 2026-09-03 (Review T9): Blockart uebersetzen: "legno" statt des stehengebliebenen englischen "wood".
          "text": "Cambia il numero da 10 a 20. Usa un altro tipo di blocco, per esempio legno. Prova."
        },
        {
          "kind": "remix",
          "title": "Due muri",
          "text": "Costruisci due muri con uno spazio vuoto in mezzo. Mostralo al tuo compagno o alla tua compagna."
        }
      ],
      "tipSolution": "Scrivi for index in range(20): nella riga del ciclo. Le due righe sotto restano indentate. Per il legno usa agent.set_item(PLANKS_OAK, 64, 1). Conta: un ciclo, due righe dentro.",
      "exercises": [
        {
          "prompt": "L'Agente sta in basso al centro. Il suo naso guarda in alto. Il programma: 3 passi avanti."
        },
        {
          "prompt": "L'Agente viene da te e prende il pietrisco. Poi il ciclo ripete due righe. L'indentazione fa parte della riga."
        }
      ],
      "quiz": [
        {
          "q": "Che cosa fa risparmiare il ciclo?",
          "answers": [
            {
              "text": "Tante righe uguali",
              "correct": true
            },
            {
              "text": "Blocchi nello zaino",
              "correct": false
            },
            {
              "text": "Spazio nel mondo",
              "correct": false
            }
          ]
        },
        {
          "q": "Quante volte gira un ciclo con range(10)?",
          "answers": [
            {
              "text": "Dieci volte",
              "correct": true
            },
            {
              "text": "Nove volte",
              "correct": false
            },
            {
              "text": "Undici volte",
              "correct": false
            }
          ]
        },
        {
          "q": "Da quale numero inizia a contare il computer?",
          "answers": [
            {
              "text": "Da 0",
              "correct": true
            },
            {
              "text": "Da 1",
              "correct": false
            },
            {
              "text": "Da 10",
              "correct": false
            }
          ]
        },
        {
          "q": "Che cosa succede con range(0)?",
          "answers": [
            {
              "text": "Niente. Il ciclo non gira nemmeno una volta",
              "correct": true
            },
            {
              "text": "Il ciclo gira una volta",
              "correct": false
            },
            {
              "text": "L'Agente segnala un errore",
              "correct": false
            }
          ]
        }
      ]
    },
    "s05": {
      "title": "Un ciclo dentro un ciclo",
      "storyShort": "Un ciclo può stare dentro un altro ciclo. Il ciclo interno costruisce una fila. Il ciclo esterno ripete la fila. Così dalla fila nasce un muro.",
      "bridge": {
        "game": "Scrivi wand nella chat. L'Agente costruisce un muro con tre file.",
        "code": "Un ciclo sta dentro l'altro. Dentro la fila, fuori i livelli."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Il muro",
          "text": "Scrivi wand nella chat. L'Agente costruisce un muro: 6 blocchi di larghezza, 3 di altezza."
        },
        {
          "kind": "nochEiner",
          "title": "Più grande",
          "text": "Cambia il muro: 8 blocchi di larghezza e 4 di altezza. Quali due numeri devi cambiare?"
        },
        {
          "kind": "remix",
          "title": "I merli",
          "text": "Rendi più corta la fila in alto. Come appare adesso il muro? Mostralo al tuo compagno o alla tua compagna."
        }
      ],
      "tipSolution": "Scrivi for index in range(4): nel ciclo esterno. Questa è l'altezza. Scrivi for index2 in range(8): nel ciclo interno. Questa è la larghezza. Dopo le due rotazioni arriva un passo avanti. Così l'Agente sta di nuovo sopra la fila. Conta: due cicli, uno dentro l'altro.",
      "exercises": [
        {
          "prompt": "L'Agente sta in basso a sinistra. Il suo naso guarda verso l'alto. Il programma: 2 passi avanti, gira a sinistra, gira a sinistra, 1 passo avanti."
        },
        {
          "prompt": "L'Agente ha già con sé il pietrisco. Ora arriva il muro: fuori i livelli, dentro la fila. Qui mancano le rotazioni e il passo dopo. Fai attenzione all'indentazione."
        }
      ],
      "quiz": [
        {
          "q": "Il muro è largo 6 blocchi e alto 3. Quanti blocchi sono?",
          "answers": [
            {
              "text": "18 blocchi",
              "correct": true
            },
            {
              "text": "9 blocchi",
              "correct": false
            },
            {
              "text": "24 blocchi",
              "correct": false
            }
          ]
        },
        {
          "q": "Che cosa fa il ciclo interno?",
          "answers": [
            {
              "text": "Costruisce una fila",
              "correct": true
            },
            {
              "text": "Sale di un livello",
              "correct": false
            },
            {
              "text": "Gira l'Agente",
              "correct": false
            }
          ]
        },
        {
          "q": "Perché l'Agente gira due volte a sinistra?",
          "answers": [
            {
              "text": "Così guarda indietro e costruisce la fila successiva",
              "correct": true
            },
            {
              "text": "Così cammina più veloce",
              "correct": false
            },
            {
              "text": "Così può posare un blocco",
              "correct": false
            }
          ]
        },
        {
          "q": "Quale ciclo finisce per primo tutto il suo giro?",
          "answers": [
            {
              "text": "Quello interno. Prima costruisce tutta la fila",
              "correct": true
            },
            {
              "text": "Quello esterno. Prima sale fino in cima",
              "correct": false
            },
            {
              "text": "Corrono entrambi nello stesso momento",
              "correct": false
            }
          ]
        }
      ]
    },
    "s06": {
      "title": "La casa",
      "storyShort": "Una casa ha quattro muri. Non copi il muro quattro volte. Metti un ciclo attorno a tutto. Dopo ogni lato l'Agente gira.",
      "bridge": {
        // Handkorrektur 2026-09-03 (Review T9): Zauberwort "haus" bleibt unuebersetzt (Chat-Kommando im Spiel). Vorher: "casa".
        // Das Hausmotiv in Titel und Story bleibt "casa".
        "game": "Scrivi haus nella chat. L'Agente costruisce un anello di quattro lati.",
        "code": "Il ciclo esterno gira quattro volte. Dopo ogni lato l'Agente gira l'angolo."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "L'anello",
          // Handkorrektur 2026-09-03 (Review T9): Zauberwort "haus" bleibt unuebersetzt (Chat-Kommando im Spiel). Vorher: "casa".
          // Das Hausmotiv in Titel und Story bleibt "casa".
          "text": "Scrivi haus nella chat. L'Agente costruisce un anello: 5 blocchi per lato."
        },
        {
          "kind": "nochEiner",
          "title": "Più alto",
          "text": "L'anello deve essere alto 3 blocchi. Per questo ti serve un terzo ciclo."
        },
        {
          // Handkorrektur 2026-09-04 (Welle C): Praeposition korrigiert (su, nicht in).
          "kind": "remix",
          "title": "La porta",
          "text": "Lascia un buco su un lato come porta. Mostra la tua casa al tuo compagno o alla tua compagna."
        }
      ],
      // Handkorrektur 2026-09-04 (Final Review): entspricht de.js — agent.move(UP, 1) steht in
      // der dritten Schleife, direkt nach dem Ring, nicht danach.
      "tipSolution": "Scrivi for index3 in range(3): tutto all'esterno. Tutto l'anello sta dentro, rientrato. agent.move(UP, 1) sta anch'esso dentro, subito dopo l'anello. Conta: tre cicli, uno dentro l'altro.",
      "exercises": [
        {
          "prompt": "L'Agente sta in basso al centro. Il suo naso guarda in alto. Il programma: 2 passi avanti, gira a sinistra. Poi di nuovo: 2 passi avanti, gira a sinistra. Alla fine 2 passi avanti."
        },
        {
          "prompt": "L'Agente costruisce un anello. Dentro un lato, fuori i quattro lati. La rotazione fa parte del ciclo esterno."
        }
      ],
      "quiz": [
        {
          "q": "Quanti lati costruisce range(4)?",
          "answers": [
            {
              "text": "Quattro",
              "correct": true
            },
            {
              "text": "Tre",
              "correct": false
            },
            {
              "text": "Cinque",
              "correct": false
            }
          ]
        },
        {
          "q": "Dove sta agent.turn(LEFT_TURN)?",
          "answers": [
            {
              "text": "Nel ciclo esterno, dopo quello interno",
              "correct": true
            },
            {
              "text": "Nel ciclo interno, a ogni blocco",
              "correct": false
            },
            {
              "text": "In cima, prima dei due cicli",
              "correct": false
            }
          ]
        },
        {
          "q": "Perché l'Agente gira solo una volta per muro?",
          "answers": [
            {
              "text": "Perché un angolo è un quarto di giro",
              "correct": true
            },
            {
              "text": "Perché altrimenti diventa troppo lento",
              "correct": false
            },
            {
              "text": "Perché altrimenti resta senza blocchi",
              "correct": false
            }
          ]
        },
        {
          "q": "L'anello ha 4 lati con 5 blocchi ciascuno. Quanti blocchi sono?",
          "answers": [
            {
              "text": "20 blocchi",
              "correct": true
            },
            {
              "text": "16 blocchi",
              "correct": false
            },
            {
              "text": "25 blocchi",
              "correct": false
            }
          ]
        }
      ],
      "bossCheck": {
        // Handkorrektur 2026-09-03 (Review T9): Etappenname uebersetzt und gross. Vorher: "Boss-Check stone".
        "title": "Boss-Check Pietra",
        "subtitle": "La staccionata",
        "task": "Costruisci una staccionata attorno a te. L'anello ha 8 blocchi per lato. Cosa fa risparmiare il ciclo? Quanti comandi sarebbero senza ciclo?"
      }
    }
  }
};
