// AUTO-GENERATED by scripts/translate.mjs — NICHT von Hand bearbeiten.
// Source: src/i18n/de.js   sourceHash: 42f062fb7673
// chunkHashes: {"ui":"dd156667ce5d","glossary":"c6be4e0ef0ce","etappen":"29e40128f71f","stations.s01":"c37b979d7d58","stations.s02":"63074802c205","stations.s03":"46eb47fc72b0","stations.s04":"8ed8fda3f3c3","stations.s05":"def7d38db5cd","stations.s06":"d4b61513c098","stations.s07":"242bf36d69d3","stations.s08":"2afc4366e9a0","stations.s09":"4478badd8d82","stations.s10":"bcb21fd11d6b","stations.s11":"7fec7409f3d7","stations.s12":"cd3e1a5778b2"}
// Language: it   model: claude-opus-5   generated: 2026-09-17T15:43:48.466Z
// Stuetz-Ebene: Deutsch bleibt daneben sichtbar. Bei Aenderung an de.js neu erzeugen.
// Handkorrektur 2026-09-03 (Review T9): zwei durchgaengige Korrekturen, deshalb hier gebuendelt
// statt an jeder Zeile: (1) "Agente" statt "Agent" an 17 Stellen (Kanon AGENT_CANON in
// scripts/translate.mjs), (2) "nella chat" statt "nel chat" an 4 Stellen in s03 (chat ist
// feminin). Einzelkorrekturen sind unten in der Zeile davor markiert.

export default {
  "ui": {
    "appTitle": "Mondo del codice",
    "tagline": "L'Agente capisce solo il codice.",
    "home": "Panoramica",
    "station": "Stazione {n}",
    "ds": "Lezione doppia {n}",
    "support": "Nella tua lingua",
    "supportShow": "Mostra l'aiuto nella tua lingua",
    "supportHide": "Nascondi l'aiuto",
    "storyHeading": "La storia",
    "conceptHeading": "L'idea",
    "bridgeGame": "Nel gioco",
    "bridgeCode": "Nel codice",
    "blocksLabel": "Ecco come appare in blocchi",
    "pythonLabel": "Ecco come appare in Python",
    "tasksHeading": "I tuoi compiti nel gioco",
    "taskAuftrag": "Compito",
    "taskNochEiner": "Un altro",
    "taskRemix": "Remix",
    "tipsHeading": "Scala di suggerimenti",
    "tipStep": "Suggerimento {n}",
    "tipSolution": "Soluzione",
    "tipRemixNote": "Se prendi la soluzione: dopo cambia una cosa. È obbligatorio.",
    "check": "Check",
    "checkHeading": "Hai capito?",
    "predictPrompt": "Dove si trova l'Agente alla fine? Clicca sulla casella.",
    "predictRight": "Giusto! L'Agente è proprio lì.",
    "predictWrong": "Non ancora. Leggi il programma dall'alto verso il basso. Dove punta il naso?",
    "parsonsPrompt": "Metti le righe nell'ordine giusto.",
    "parsonsUp": "in su",
    "parsonsDown": "in giù",
    "parsonsCheck": "Controlla",
    "parsonsRight": "Giusto! Questo è l'ordine.",
    "parsonsWrong": "Non ancora. Che cosa deve fare l'Agente per primo?",
    "checkButton": "Controlla",
    "matchPrompt": "Quale blocco va con quale riga? Prima il blocco, poi la riga.",
    "matchRight": "Giusto! Ogni blocco ha la sua riga.",
    "matchWrong": "Non ancora. Guarda i numeri e i nomi nei blocchi.",
    "fillPrompt": "Scegli la risposta giusta per ogni spazio vuoto.",
    "fillRight": "Giusto! Il codice funziona.",
    "fillWrong": "Non ancora. Uno spazio vuoto non va bene.",
    "findbugPrompt": "Una riga è sbagliata. Quale?",
    "findbugRight": "Giusto! Questo è l'errore.",
    "findbugWrong": "No, questa riga è giusta. Guarda di nuovo.",
    "typePrompt": "Scrivi in ogni spazio vuoto il numero giusto o la parola giusta.",
    "typeRight": "Giusto! Così il codice funziona.",
    "typeWrong": "Non ancora. Leggi la riga un'altra volta.",
    "typeCase": "Quasi. Python distingue maiuscole e minuscole.",
    "typeGapLabel": "Spazio vuoto",
    "spielstandHeading": "Salvataggio",
    "spielstandPrompt": "Che cosa sai fare adesso? Scrivi tre frasi brevi.",
    "spielstandSave": "Salva",
    "spielstandSaved": "Salvato. Solo su questo dispositivo.",
    "progress": "Hai visitato {done} stazioni su {total}.",
    "next": "Avanti",
    "prev": "Indietro",
    "play": "Leggi ad alta voce",
    "langLabel": "Lingua",
    "footer": "Un modulo didattico di Dirk Schulenburg · CC BY 4.0 · Non è un prodotto ufficiale Minecraft.",
    "bossCheckHeading": "Boss-Check",
    "bossCheckHint": "Risolvi il compito senza la scala di suggerimenti. Consegna il link di condivisione e scrivi tre frasi."
  },
  "glossary": {
    "befehl": {
      "term": "Comando",
      "short": "Una riga di codice. L'Agente fa esattamente questo."
    },
    "programm": {
      "term": "Programma",
      "short": "Tanti comandi, dall'alto verso il basso."
    },
    "sequenz": {
      "term": "Sequenza",
      "short": "L'ordine dei comandi."
    },
    "agent": {
      "term": "Agente",
      "short": "Il robot in Minecraft. Capisce solo il codice."
    },
    "zauberwort": {
      "term": "Parola magica",
      "short": "Una parola nella chat. Avvia il tuo programma."
    },
    "python": {
      "term": "Python",
      "short": "Un linguaggio di programmazione. Il tuo codice come testo."
    },
    "bloecke": {
      "term": "Blocchi",
      "short": "Il tuo codice come mattoncini da trascinare."
    },
    "fehler": {
      "term": "Errore",
      "short": "L'Agente ti ha capito male. Puoi ripararlo."
    },
    "variable": {
      "term": "Variabile",
      "short": "Un numero con un nome. Lo imposti una volta in alto."
    },
    "koordinaten": {
      "term": "Coordinate",
      "short": "Tre numeri x, y, z dicono dov'è un blocco."
    },
    "fill": {
      "term": "fill",
      "short": "Riempie tutto tra due angoli con un blocco."
    },
    "zaehler": {
      "term": "Contatore",
      "short": "Il ciclo conta: index è 0, 1, 2 …"
    },
    "bedingung": {
      "term": "Condizione",
      "short": "Una domanda con risposta vero o falso."
    },
    "verzweigung": {
      "term": "Ramificazione",
      "short": "if e else: passa esattamente una via su due."
    },
    "solange": {
      "term": "Ciclo finché",
      "short": "while ripete finché la condizione è vera."
    },
    "detect": {
      "term": "detect",
      "short": "L'Agente controlla se davanti o sotto di lui c'è un blocco."
    }
  },
  "etappen": {
    "holz": {
      "name": "Legno",
      "badge": {
        "name": "Legno",
        // Handkorrektur 2026-09-04 (Re-Review T9): "il Boss-Check" als feststehender Begriff (Grossschreibung), nicht "il boss-check".
        "description": "Hai superato tutti i check della tappa Legno e hai consegnato il Boss-Check."
      }
    },
    "stein": {
      "name": "Pietra",
      "badge": {
        "name": "Pietra",
        // Handkorrektur 2026-09-04 (Re-Review T9): "il Boss-Check" als feststehender Begriff (Grossschreibung), nicht "il boss-check".
        "description": "Hai superato tutti i check della tappa Pietra e hai consegnato il Boss-Check."
      }
    },
    "eisen": {
      "name": "Ferro",
      "badge": {
        "name": "Ferro",
        // Handkorrektur 2026-09-04 (Re-Review T9): "il Boss-Check" als feststehender Begriff (Grossschreibung), nicht "il boss-check".
        "description": "Hai superato tutti i check della tappa Ferro e hai consegnato il Boss-Check."
      }
    },
    "gold": {
      "name": "Oro",
      "badge": {
        "name": "Oro",
        // Handkorrektur 2026-09-04 (Re-Review T9): "il Boss-Check" als feststehender Begriff (Grossschreibung), nicht "il boss-check".
        "description": "Hai superato tutti i check della tappa Oro e hai consegnato il Boss-Check."
      }
    },
    "diamant": {
      "name": "Diamante",
      "badge": {
        "name": "Diamante",
        // Handkorrektur 2026-09-04 (Re-Review T9): "il Boss-Check" als feststehender Begriff (Grossschreibung), nicht "il boss-check".
        "description": "Hai superato tutti i check della tappa Diamante e hai consegnato il Boss-Check."
      }
    },
    "netherite": {
      "name": "Netherite",
      "badge": {
        "name": "Netherite",
        // Handkorrektur 2026-09-04 (Re-Review T9): "il Boss-Check" als feststehender Begriff (Grossschreibung), nicht "il boss-check".
        "description": "Hai superato tutti i check della tappa Netherite e hai consegnato il Boss-Check."
      }
    },
    "enderdrache": {
      "name": "Drago dell'End",
      "badge": {
        "name": "Drago dell'End",
        // Handkorrektur 2026-09-04 (Re-Review T9): "il Boss-Check" als feststehender Begriff (Grossschreibung), nicht "il boss-check".
        "description": "Hai superato tutti i check della tappa Drago dell'End e hai consegnato il Boss-Check."
      }
    }
  },
  "stations": {
    "s01": {
      "title": "Il mondo nuovo",
      "storyShort": "L'Agente è il tuo robot in Minecraft. Non capisce il tedesco, solo il codice. Parte solo quando scrivi una parola magica nella chat.",
      "bridge": {
        "game": "Scrivi hi nella chat. L'Agente viene da te e fa un passo.",
        "code": "Un comando è una riga di codice. La parola magica avvia tutto il programma."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Di' hi",
          "text": "Scrivi hi nella chat. L'Agente viene da te. Poi fa un passo avanti."
        },
        {
          "kind": "nochEiner",
          "title": "La tua parola",
          "text": "Cambia la parola magica da hi a hallo. Cambia i passi da 1 a 3. Prova."
        },
        {
          "kind": "remix",
          "title": "Un'altra parola",
          "text": "Inventa una seconda parola magica. Con questa l'Agente deve fare qualcosa di diverso. Mostralo al tuo compagno o alla tua compagna."
        }
      ],
      "tipSolution": "Scrivi agent.teleport_to_player() e sotto agent.move(FORWARD, 3). Nell'ultima riga sostituisci «hi» con «hallo». Solo la parola tra virgolette. Poi scrivi hallo nella chat.",
      "exercises": [
        {
          "prompt": "L'Agente sta in basso al centro. Il suo naso guarda in alto. Il programma: 1 passo avanti."
        },
        {
          "prompt": "L'Agente deve venire da te e fare un passo. La riga con la parola magica va alla fine."
        }
      ],
      "quiz": [
        {
          "q": "A cosa serve la parola magica?",
          "answers": [
            {
              "text": "Avvia il tuo programma",
              "correct": true
            },
            {
              "text": "Apre il Code Builder",
              "correct": false
            },
            {
              "text": "Salva il tuo programma",
              "correct": false
            }
          ]
        },
        {
          "q": "Quale tasto apre il Code Builder?",
          "answers": [
            {
              "text": "Il tasto C",
              "correct": true
            },
            {
              "text": "Il tasto E",
              "correct": false
            },
            {
              "text": "Il tasto T",
              "correct": false
            }
          ]
        },
        {
          "q": "Che cosa fa agent.teleport_to_player()?",
          "answers": [
            {
              "text": "L'Agente viene da te",
              "correct": true
            },
            {
              "text": "L'Agente fa un passo avanti",
              "correct": false
            },
            {
              "text": "L'Agente posa un blocco",
              "correct": false
            }
          ]
        },
        {
          "q": "L'Agente capisce …",
          "answers": [
            {
              "text": "solo il codice",
              "correct": true
            },
            {
              "text": "ogni parola nella chat",
              "correct": false
            },
            {
              "text": "il tedesco, se scrivi lentamente",
              "correct": false
            }
          ]
        }
      ]
    },
    "s02": {
      "title": "L'ordine conta",
      "storyShort": "L'Agente esegue i comandi esattamente nell'ordine in cui li scrivi. Prima camminare e poi girare non è la stessa cosa che prima girare e poi camminare.",
      "bridge": {
        "game": "L'Agente avanza passo dopo passo e posa blocchi dietro di sé.",
        "code": "Un programma è una lista di comandi. Il computer li esegue dall'alto verso il basso."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Il percorso",
          "text": "Scrivi la parola magica weg nella chat. L'Agente posa quattro blocchi. Guarda bene: dov'è l'angolo?"
        },
        {
          "kind": "nochEiner",
          "title": "Più lungo",
          "text": "Cambia il programma. L'Agente posa cinque blocchi dritti, poi fa l'angolo, poi altri due."
        },
        {
          "kind": "remix",
          "title": "Il tuo disegno",
          "text": "Costruisci un tuo disegno con i blocchi. Per esempio una Z o una U. Mostralo al tuo compagno o alla tua compagna."
        }
      ],
      "tipSolution": "Per cinque blocchi: scrivi agent.move(FORWARD, 1) e agent.place(BACK) cinque volte. Poi agent.turn(LEFT_TURN). Dopo servono ancora tre coppie di move e place. La prima coppia posa il blocco dell'angolo.",
      "exercises": [
        {
          "prompt": "L'Agente sta in basso al centro. Il suo naso punta verso l'alto. Il programma: 2 passi avanti, gira a sinistra, 1 passo avanti."
        },
        {
          "prompt": "L'Agente deve venire da te, fare due passi, girare a sinistra e fare ancora un passo."
        }
      ],
      "quiz": [
        {
          "q": "L'Agente deve fare 3 passi e poi girare a sinistra. Quale ordine è corretto?",
          "answers": [
            {
              "text": "Prima agent.move(FORWARD, 3), poi agent.turn(LEFT_TURN)",
              "correct": true
            },
            {
              "text": "Prima agent.turn(LEFT_TURN), poi agent.move(FORWARD, 3)",
              "correct": false
            },
            {
              "text": "L'ordine non conta",
              "correct": false
            }
          ]
        },
        {
          "q": "Scrivi agent.move(FORWARD, 3) due volte, una sotto l'altra. Cosa fa l'Agente?",
          "answers": [
            {
              "text": "Fa 6 passi",
              "correct": true
            },
            {
              "text": "Fa 3 passi",
              "correct": false
            },
            {
              "text": "Segnala un errore",
              "correct": false
            }
          ]
        },
        {
          "q": "Quando parte il tuo programma?",
          "answers": [
            {
              "text": "Quando scrivi la parola magica nella chat",
              "correct": true
            },
            {
              "text": "Subito, quando apri il Code Builder",
              "correct": false
            },
            {
              "text": "Quando clicchi sull'Agente",
              "correct": false
            }
          ]
        },
        {
          "q": "L'Agente capisce …",
          "answers": [
            {
              "text": "solo il codice",
              "correct": true
            },
            {
              "text": "tedesco e inglese",
              "correct": false
            },
            {
              "text": "ogni lingua",
              "correct": false
            }
          ]
        }
      ]
    },
    "s03": {
      "title": "Parole magiche",
      "storyShort": "Una parola nella chat è un evento. Ogni parola magica avvia il suo programma. Puoi avere più parole magiche.",
      "bridge": {
        "game": "Tu scrivi weg oppure turm nella chat. L'Agente costruisce la strada o la torre.",
        "code": "Ogni parola magica ha il suo blocco a cappello. Sotto c'è il suo programma."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Due parole",
          "text": "Scrivi weg nella chat. Poi scrivi turm. Qui la strada è più corta che nella stazione 2. Guarda bene tutte e due le cose."
        },
        {
          "kind": "nochEiner",
          "title": "Più alta",
          "text": "Cambia il programma per turm. La torre deve diventare alta cinque blocchi."
        },
        {
          "kind": "remix",
          "title": "Il ponte",
          "text": "Inventa una terza parola magica: bruecke. Le parole magiche non hanno umlaut. Con questa parola l'Agente costruisce una strada sopra un buco."
        }
      ],
      "tipSolution": "Per cinque blocchi scrivi agent.place(FORWARD) e agent.move(UP, 1) uno dopo l'altro, alternati. Alla fine metti ancora una volta agent.place(FORWARD). Conta: cinque righe con place.",
      "exercises": [
        {
          "prompt": "L'Agente sta in basso a sinistra. Il suo naso guarda verso l'alto. Il programma: 2 passi avanti, gira a destra, 2 passi avanti."
        },
        {
          "prompt": "L'Agente viene da te. Prende erba. Fa un passo e mette un blocco. La riga con la parola magica viene per ultima."
        }
      ],
      "quiz": [
        {
          "q": "Che cos'è un evento?",
          "answers": [
            {
              "text": "Qualcosa succede nel gioco, per esempio una parola nella chat",
              "correct": true
            },
            {
              "text": "Un errore nel tuo programma",
              "correct": false
            },
            {
              "text": "Un blocco che l'Agente mette",
              "correct": false
            }
          ]
        },
        {
          "q": "Hai due parole magiche. Quanti programmi sono?",
          "answers": [
            {
              "text": "Due. Ogni parola ha il suo programma",
              "correct": true
            },
            {
              "text": "Uno. Le due parole avviano lo stesso programma",
              "correct": false
            },
            {
              "text": "Nessuno. Due parole magiche non si possono avere",
              "correct": false
            }
          ]
        },
        {
          "q": "Che cosa fa agent.move(UP, 1)?",
          "answers": [
            {
              "text": "L'Agente va su di un blocco",
              "correct": true
            },
            {
              "text": "L'Agente fa un passo avanti",
              "correct": false
            },
            {
              "text": "L'Agente mette un blocco sopra di sé",
              "correct": false
            }
          ]
        },
        {
          "q": "Prima scrivi weg, poi turm. Che cosa succede?",
          "answers": [
            {
              "text": "Prima parte il programma per weg, poi quello per turm",
              "correct": true
            },
            {
              "text": "I due programmi partono nello stesso momento",
              "correct": false
            },
            {
              "text": "Parte solo il programma per turm",
              "correct": false
            }
          ]
        }
      ],
      "bossCheck": {
        "title": "Boss-Check Legno",
        "subtitle": "La L",
        "task": "L'Agente forma una L: prima 4 blocchi dritti, poi 2 dietro l'angolo. Che cosa fa il tuo programma? Perché l'ordine è importante? Che cosa è stato difficile?"
      }
    },
    "s04": {
      "title": "Ripetere",
      "storyShort": "Scrivere dieci volte la stessa cosa è faticoso. Per questo esiste il ciclo. Tu scrivi le righe una volta sola. Il computer le ripete per te.",
      "bridge": {
        "game": "Scrivi mauer nella chat. L'Agente mette dieci blocchi in fila.",
        "code": "Un ciclo ripete due righe dieci volte. Tu le scrivi una volta sola."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Il muro",
          "text": "Scrivi mauer nella chat. L'Agente costruisce un muro di dieci blocchi. Conta i blocchi."
        },
        {
          "kind": "nochEiner",
          "title": "Più lungo e diverso",
          // Handkorrektur 2026-09-03 (Review T9): Blockart uebersetzen: "legno" statt des stehengebliebenen englischen "wood".
          "text": "Cambia il numero da 10 a 20. Usa un altro tipo di blocco, per esempio legno. Prova."
        },
        {
          "kind": "remix",
          "title": "Due muri",
          "text": "Costruisci due muri con uno spazio vuoto in mezzo. Mostralo al tuo compagno o alla tua compagna."
        }
      ],
      "tipSolution": "Scrivi for index in range(20): nella riga del ciclo. Le due righe sotto restano indentate. Per il legno usa agent.set_item(PLANKS_OAK, 64, 1). Conta: un ciclo, due righe dentro.",
      "exercises": [
        {
          "prompt": "L'Agente sta in basso al centro. Il suo naso guarda in alto. Il programma: 3 passi avanti."
        },
        {
          "prompt": "L'Agente viene da te e prende il pietrisco. Poi il ciclo ripete due righe. L'indentazione fa parte della riga."
        }
      ],
      "quiz": [
        {
          "q": "Che cosa fa risparmiare il ciclo?",
          "answers": [
            {
              "text": "Tante righe uguali",
              "correct": true
            },
            {
              "text": "Blocchi nello zaino",
              "correct": false
            },
            {
              "text": "Spazio nel mondo",
              "correct": false
            }
          ]
        },
        {
          "q": "Quante volte gira un ciclo con range(10)?",
          "answers": [
            {
              "text": "Dieci volte",
              "correct": true
            },
            {
              "text": "Nove volte",
              "correct": false
            },
            {
              "text": "Undici volte",
              "correct": false
            }
          ]
        },
        {
          "q": "Da quale numero inizia a contare il computer?",
          "answers": [
            {
              "text": "Da 0",
              "correct": true
            },
            {
              "text": "Da 1",
              "correct": false
            },
            {
              "text": "Da 10",
              "correct": false
            }
          ]
        },
        {
          "q": "Che cosa succede con range(0)?",
          "answers": [
            {
              "text": "Niente. Il ciclo non gira nemmeno una volta",
              "correct": true
            },
            {
              "text": "Il ciclo gira una volta",
              "correct": false
            },
            {
              "text": "L'Agente segnala un errore",
              "correct": false
            }
          ]
        }
      ]
    },
    "s05": {
      "title": "Un ciclo dentro un ciclo",
      "storyShort": "Un ciclo può stare dentro un altro ciclo. Il ciclo interno costruisce una fila. Il ciclo esterno ripete la fila. Così dalla fila nasce un muro.",
      "bridge": {
        "game": "Scrivi wand nella chat. L'Agente costruisce un muro con tre file.",
        "code": "Un ciclo sta dentro l'altro. Dentro la fila, fuori i livelli."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Il muro",
          "text": "Scrivi wand nella chat. L'Agente costruisce un muro: 6 blocchi di larghezza, 3 di altezza."
        },
        {
          "kind": "nochEiner",
          "title": "Più grande",
          "text": "Cambia il muro: 8 blocchi di larghezza e 4 di altezza. Quali due numeri devi cambiare?"
        },
        {
          "kind": "remix",
          "title": "I merli",
          "text": "Rendi più corta la fila in alto. Come appare adesso il muro? Mostralo al tuo compagno o alla tua compagna."
        }
      ],
      "tipSolution": "Scrivi for index in range(4): nel ciclo esterno. Questa è l'altezza. Scrivi for index2 in range(8): nel ciclo interno. Questa è la larghezza. Dopo le due rotazioni arriva un passo avanti. Così l'Agente sta di nuovo sopra la fila. Conta: due cicli, uno dentro l'altro.",
      "exercises": [
        {
          "prompt": "L'Agente sta in basso a sinistra. Il suo naso guarda verso l'alto. Il programma: 2 passi avanti, gira a sinistra, gira a sinistra, 1 passo avanti."
        },
        {
          "prompt": "L'Agente ha già con sé il pietrisco. Ora arriva il muro: fuori i livelli, dentro la fila. Qui mancano le rotazioni e il passo dopo. Fai attenzione all'indentazione."
        }
      ],
      "quiz": [
        {
          "q": "Il muro è largo 6 blocchi e alto 3. Quanti blocchi sono?",
          "answers": [
            {
              "text": "18 blocchi",
              "correct": true
            },
            {
              "text": "9 blocchi",
              "correct": false
            },
            {
              "text": "24 blocchi",
              "correct": false
            }
          ]
        },
        {
          "q": "Che cosa fa il ciclo interno?",
          "answers": [
            {
              "text": "Costruisce una fila",
              "correct": true
            },
            {
              "text": "Sale di un livello",
              "correct": false
            },
            {
              "text": "Gira l'Agente",
              "correct": false
            }
          ]
        },
        {
          "q": "Perché l'Agente gira due volte a sinistra?",
          "answers": [
            {
              "text": "Così guarda indietro e costruisce la fila successiva",
              "correct": true
            },
            {
              "text": "Così cammina più veloce",
              "correct": false
            },
            {
              "text": "Così può posare un blocco",
              "correct": false
            }
          ]
        },
        {
          "q": "Quale ciclo finisce per primo tutto il suo giro?",
          "answers": [
            {
              "text": "Quello interno. Prima costruisce tutta la fila",
              "correct": true
            },
            {
              "text": "Quello esterno. Prima sale fino in cima",
              "correct": false
            },
            {
              "text": "Corrono entrambi nello stesso momento",
              "correct": false
            }
          ]
        }
      ]
    },
    "s06": {
      "title": "La casa",
      "storyShort": "Una casa ha quattro muri. Non copi il muro quattro volte. Metti un ciclo attorno a tutto. Dopo ogni lato l'Agente gira.",
      "bridge": {
        // Handkorrektur 2026-09-03 (Review T9): Zauberwort "haus" bleibt unuebersetzt (Chat-Kommando im Spiel). Vorher: "casa".
        // Das Hausmotiv in Titel und Story bleibt "casa".
        "game": "Scrivi haus nella chat. L'Agente costruisce un anello di quattro lati.",
        "code": "Il ciclo esterno gira quattro volte. Dopo ogni lato l'Agente gira l'angolo."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "L'anello",
          // Handkorrektur 2026-09-03 (Review T9): Zauberwort "haus" bleibt unuebersetzt (Chat-Kommando im Spiel). Vorher: "casa".
          // Das Hausmotiv in Titel und Story bleibt "casa".
          "text": "Scrivi haus nella chat. L'Agente costruisce un anello: 5 blocchi per lato."
        },
        {
          "kind": "nochEiner",
          "title": "Più alto",
          "text": "L'anello deve essere alto 3 blocchi. Per questo ti serve un terzo ciclo."
        },
        {
          // Handkorrektur 2026-09-04 (Welle C): Praeposition korrigiert (su, nicht in).
          "kind": "remix",
          "title": "La porta",
          "text": "Lascia un buco su un lato come porta. Mostra la tua casa al tuo compagno o alla tua compagna."
        }
      ],
      // Handkorrektur 2026-09-04 (Final Review): entspricht de.js — agent.move(UP, 1) steht in
      // der dritten Schleife, direkt nach dem Ring, nicht danach.
      "tipSolution": "Scrivi for index3 in range(3): tutto all'esterno. Tutto l'anello sta dentro, rientrato. agent.move(UP, 1) sta anch'esso dentro, subito dopo l'anello. Conta: tre cicli, uno dentro l'altro.",
      "exercises": [
        {
          "prompt": "L'Agente sta in basso al centro. Il suo naso guarda in alto. Il programma: 2 passi avanti, gira a sinistra. Poi di nuovo: 2 passi avanti, gira a sinistra. Alla fine 2 passi avanti."
        },
        {
          "prompt": "L'Agente costruisce un anello. Dentro un lato, fuori i quattro lati. La rotazione fa parte del ciclo esterno."
        }
      ],
      "quiz": [
        {
          "q": "Quanti lati costruisce range(4)?",
          "answers": [
            {
              "text": "Quattro",
              "correct": true
            },
            {
              "text": "Tre",
              "correct": false
            },
            {
              "text": "Cinque",
              "correct": false
            }
          ]
        },
        {
          "q": "Dove sta agent.turn(LEFT_TURN)?",
          "answers": [
            {
              "text": "Nel ciclo esterno, dopo quello interno",
              "correct": true
            },
            {
              "text": "Nel ciclo interno, a ogni blocco",
              "correct": false
            },
            {
              "text": "In cima, prima dei due cicli",
              "correct": false
            }
          ]
        },
        {
          "q": "Perché l'Agente gira solo una volta per muro?",
          "answers": [
            {
              "text": "Perché un angolo è un quarto di giro",
              "correct": true
            },
            {
              "text": "Perché altrimenti diventa troppo lento",
              "correct": false
            },
            {
              "text": "Perché altrimenti resta senza blocchi",
              "correct": false
            }
          ]
        },
        {
          "q": "L'anello ha 4 lati con 5 blocchi ciascuno. Quanti blocchi sono?",
          "answers": [
            {
              "text": "20 blocchi",
              "correct": true
            },
            {
              "text": "16 blocchi",
              "correct": false
            },
            {
              "text": "25 blocchi",
              "correct": false
            }
          ]
        }
      ],
      "bossCheck": {
        // Handkorrektur 2026-09-03 (Review T9): Etappenname uebersetzt und gross. Vorher: "Boss-Check stone".
        "title": "Boss-Check Pietra",
        "subtitle": "La staccionata",
        "task": "Costruisci una staccionata attorno a te. L'anello ha 8 blocchi per lato. Cosa fa risparmiare il ciclo? Quanti comandi sarebbero senza ciclo?"
      }
    },
    "s07": {
      "title": "Numeri con un nome",
      "storyShort": "Una variabile è un numero con un nome. La imposti una volta, il ciclo la usa dappertutto. Cambia solo il numero, non tutto il programma.",
      "bridge": {
        "game": "Scrivi bruecke. L'Agente costruisce un ponte sopra il fiume.",
        "code": "laenge sta scritto una volta in alto. Il ciclo usa quel numero."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Il ponte",
          "text": "Mettiti sul blocco d'oro nel punto A. Scrivi bruecke. Attraversa il ponte. In alto passa a Python. Trova la riga laenge = 5."
        },
        {
          "kind": "nochEiner",
          "title": "Punto B",
          "text": "Vai al blocco d'oro nel punto B. Il fiume è largo 8. Cambia solo un numero. Scrivi bruecke."
        },
        {
          "kind": "remix",
          "title": "Il tuo ponte",
          "text": "Costruisci il ponte con un altro blocco. Oppure fallo largo due blocchi. Mostralo al tuo compagno o alla tua compagna."
        }
      ],
      "tipSolution": "Imposta laenge = 8. Cambia solo questa riga. Così range(laenge) costruisce otto coppie move-place.",
      "exercises": [
        {
          "prompt": "Abbina ogni blocco alla sua riga di Python."
        },
        {
          "prompt": "Il fiume nel punto B è largo 8 blocchi. Quale numero va nello spazio vuoto?"
        }
      ],
      "quiz": [
        {
          "q": "Che cos'è laenge?",
          "answers": [
            {
              "text": "Un numero con un nome",
              "correct": true
            },
            {
              "text": "Una parola magica",
              "correct": false
            },
            {
              "text": "Un blocco",
              "correct": false
            }
          ]
        },
        {
          "q": "Il ponte deve essere lungo 8. Che cosa cambi?",
          "answers": [
            {
              "text": "Solo la riga laenge = 5",
              "correct": true
            },
            {
              "text": "Ogni riga con un 5",
              "correct": false
            },
            {
              "text": "La parola magica",
              "correct": false
            }
          ]
        },
        {
          "q": "laenge = 5. Quante volte gira range(laenge)?",
          "answers": [
            {
              "text": "5 volte",
              "correct": true
            },
            {
              "text": "4 volte",
              "correct": false
            },
            {
              "text": "6 volte",
              "correct": false
            }
          ]
        },
        {
          "q": "Dove vedi il tuo programma in Python?",
          "answers": [
            {
              "text": "Con l'interruttore in alto nell'editor",
              "correct": true
            },
            {
              "text": "Nella chat",
              "correct": false
            },
            {
              "text": "Nel mondo",
              "correct": false
            }
          ]
        }
      ]
    },
    "s08": {
      "title": "Dove sono?",
      "storyShort": "Ogni blocco ha tre coordinate: x, y e z. pos conta dai tuoi piedi, y è l'altezza. fill riempie un intero blocco di spazio con un solo comando.",
      "bridge": {
        // Handkorrektur 2026-09-16 (Plan 3 Final-Review-Fix): "burrone" wie vor dem Neulauf s08 (der Lauf schrieb "gola").
        "game": "Leggi x, y, z. Tu digiti plattform. La piattaforma sta sopra il burrone.",
        "code": "fill riempie tutto tra due angoli. pos conta dai tuoi piedi."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "La piattaforma",
          // Handkorrektur 2026-09-16 (Plan 3 Final-Review-Fix): "burrone" wie vor dem Neulauf s08 (der Lauf schrieb "gola").
          "text": "Attiva le coordinate. Mettiti sul blocco d'oro vicino al burrone. Leggi x, y, z e scrivili. Scrivi plattform. Cammina sulla piattaforma. Passa a Python: trova i due angoli."
        },
        {
          "kind": "nochEiner",
          "title": "Più larga",
          "text": "Rendi la piattaforma due volte più larga. Più larga qui significa: in direzione x. Quale numero cambi?"
        },
        {
          "kind": "remix",
          "title": "Il tetto",
          "text": "Costruisci un tetto sopra la piattaforma. Consiglio: y = 2. Mostralo al tuo compagno o alla tua compagna."
        }
      ],
      "tipSolution": "Il secondo angolo diventa pos(9, -1, 7) invece di pos(4, -1, 7). Da 0 a 9 sono dieci blocchi. Solo il numero x diventa più grande.",
      "exercises": [
        {
          "prompt": "Tre blocchi fill, tre righe. Fai attenzione a y e al blocco."
        },
        {
          "prompt": "La piattaforma è diventata un muro spesso. Quale riga è sbagliata?",
          "explain": "Il secondo angolo ha y = 1. fill riempie da y = -1 fino a y = 1. Sono tre blocchi di altezza. La piattaforma ha bisogno di y = -1 in entrambi gli angoli."
        }
      ],
      "quiz": [
        {
          "q": "Che cosa significa y?",
          "answers": [
            {
              "text": "L'altezza",
              "correct": true
            },
            {
              "text": "Sinistra e destra",
              "correct": false
            },
            {
              "text": "Davanti e dietro",
              "correct": false
            }
          ]
        },
        {
          "q": "Dov'è pos(0, -1, 1)?",
          "answers": [
            {
              "text": "Un blocco sotto di te, un blocco più avanti in direzione z",
              "correct": true
            },
            {
              "text": "Sopra di te",
              "correct": false
            },
            {
              "text": "Molto lontano",
              "correct": false
            }
          ]
        },
        {
          "q": "Che cosa fa fill?",
          "answers": [
            {
              "text": "Riempie tutto tra due angoli",
              "correct": true
            },
            {
              "text": "Mette un blocco",
              "correct": false
            },
            {
              "text": "Muove l'Agente",
              "correct": false
            }
          ]
        },
        {
          "q": "L'indicatore nel gioco mostra x, y, z. Che cosa sono?",
          "answers": [
            {
              "text": "Coordinate del mondo, uguali per tutti",
              "correct": true
            },
            {
              "text": "Distanze da te",
              "correct": false
            },
            {
              "text": "Numeri casuali",
              "correct": false
            }
          ]
        }
      ]
    },
    "s09": {
      "title": "Contare",
      "storyShort": "Il ciclo conta da solo: index è 0, poi 1, poi 2. Usa index come altezza. Così da una riga nasce una scala intera.",
      "bridge": {
        "game": "Scrivi treppe. La scala cresce gradino dopo gradino fino al pianoro.",
        "code": "index conta 0, 1, 2 … Il ciclo usa index come altezza."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "La scala",
          "text": "Mettiti sul blocco d'oro davanti alla scogliera. Scrivi treppe. Sali la scala. Passa a Python: dove compare index due volte?"
        },
        {
          "kind": "nochEiner",
          "title": "Più larga",
          "text": "Fai ogni gradino largo 5. Cambia l'ultimo numero in pos, il numero z."
        },
        {
          "kind": "remix",
          "title": "La tua scala",
          "text": "Costruisci la scala in legno di quercia. Oppure costruiscila verso il basso, nel canyon. Mostrala al tuo compagno o alla tua compagna."
        }
      ],
      "tipSolution": "Il gradino index va da pos(index, 0, 1) a pos(index, index, 3). Con stufen = 6 hai sei gradini.",
      "exercises": [
        {
          "prompt": "La scogliera è alta 6. Ogni gradino è alto quanto il suo contatore più 1."
        },
        {
          "prompt": "La scala è diventata un muro. Quale riga è sbagliata?",
          "explain": "In pos c'è stufen al posto di index. Così ogni gradino è alto 7. Viene fuori un muro, non una scala."
        }
      ],
      "quiz": [
        {
          "q": "Che cos'è index?",
          "answers": [
            {
              "text": "Il contatore del ciclo",
              "correct": true
            },
            {
              "text": "L'altezza della scogliera",
              "correct": false
            },
            {
              "text": "Una parola magica",
              "correct": false
            }
          ]
        },
        {
          "q": "range(6): quali valori riceve index?",
          "answers": [
            {
              "text": "da 0 a 5",
              "correct": true
            },
            {
              "text": "da 1 a 6",
              "correct": false
            },
            {
              "text": "da 0 a 6",
              "correct": false
            }
          ]
        },
        {
          "q": "Perché ogni gradino diventa più alto?",
          "answers": [
            {
              "text": "index cresce a ogni giro",
              "correct": true
            },
            {
              "text": "fill conta da solo",
              "correct": false
            },
            {
              "text": "stufen diventa più grande",
              "correct": false
            }
          ]
        },
        {
          "q": "La scogliera è alta 9. Cosa imposti?",
          "answers": [
            {
              "text": "stufen = 9",
              "correct": true
            },
            {
              "text": "index = 9",
              "correct": false
            },
            {
              "text": "range(8)",
              "correct": false
            }
          ]
        }
      ],
      "bossCheck": {
        "title": "Boss-Check Ferro",
        "subtitle": "La seconda scogliera",
        "task": "Mettiti sul blocco d'oro davanti alla seconda scogliera. Leggi la y in basso. Sali la scala a pioli e leggi la y in alto. Imposta stufen. Costruisci la scala. Scrivi tre frasi: da dove viene il tuo numero? Che cosa fa index? Che cosa cambi con una scogliera più alta?"
      }
    },
    "s10": {
      "title": "Se, allora",
      "storyShort": "Il corridoio del percorso gira. L'Agente controlla con detect se davanti c'è un blocco. Con if si gira solo in quel caso.",
      "bridge": {
        "game": "Tu scrivi ecke. L'Agente corre nel corridoio e gira al muro.",
        "code": "if controlla una condizione. Solo se è vera, l'Agente si gira."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Dietro l'angolo",
          "text": "Mettiti sul blocco d'oro all'inizio del percorso Angolo. Guarda verso sud. Scrivi ecke. L'Agente si ferma sopra il secondo blocco d'oro. Passa a Python: trova la riga con if."
        },
        {
          "kind": "nochEiner",
          "title": "Verso destra",
          "text": "Costruisci un corridoio corto che gira a destra. Cambia una riga nel programma."
        },
        {
          "kind": "remix",
          "title": "Il tuo corridoio",
          "text": "Costruisci un corridoio con due angoli. Bastano 20 giri? Mostralo al tuo compagno o alla tua compagna."
        }
      ],
      "tipSolution": "Sotto if agent.detect(AgentDetection.BLOCK, FORWARD): c'è agent.turn(LEFT_TURN). agent.move(FORWARD, 1) sta fuori da if e viene eseguito ogni volta.",
      "exercises": [
        {
          "prompt": "Abbina ogni blocco alla sua riga di Python."
        },
        {
          "prompt": "L'Agente deve controllare che cosa c'è davanti a lui. Poi si gira a sinistra."
        }
      ],
      "quiz": [
        {
          "q": "Che cos'è una condizione?",
          "answers": [
            {
              "text": "Qualcosa che è vero o falso",
              "correct": true
            },
            {
              "text": "Un blocco",
              "correct": false
            },
            {
              "text": "Una parola magica",
              "correct": false
            }
          ]
        },
        {
          "q": "Davanti all'Agente c'è un muro. Quanto vale agent.detect(AgentDetection.BLOCK, FORWARD)?",
          "answers": [
            {
              "text": "vero",
              "correct": true
            },
            {
              "text": "falso",
              "correct": false
            },
            {
              "text": "20",
              "correct": false
            }
          ]
        },
        {
          "q": "Quando viene eseguita la riga sotto if?",
          "answers": [
            {
              "text": "Solo se la condizione è vera",
              "correct": true
            },
            {
              "text": "Sempre",
              "correct": false
            },
            {
              "text": "Mai",
              "correct": false
            }
          ]
        },
        {
          "q": "Perché agent.move sta fuori da if?",
          "answers": [
            {
              "text": "L'Agente deve camminare ogni volta",
              "correct": true
            },
            {
              "text": "Altrimenti non si gira",
              "correct": false
            },
            {
              "text": "Non importa",
              "correct": false
            }
          ]
        }
      ]
    },
    "s11": {
      "title": "Altrimenti",
      "storyShort": "Sul percorso ci sono dei buchi. Con if e else l'Agente decide: se c'è il terreno, cammina. Altrimenti mette un blocco. Il numero di giri lo cambi in Python.",
      "bridge": {
        "game": "Tu digiti loecher. L'Agente riempie i buchi e cammina fino al muro.",
        "code": "else significa «altrimenti». In ogni giro parte esattamente una delle due strade."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "I buchi",
          "text": "Mettiti sul blocco d'oro del percorso dei buchi. Guarda verso sud. Scrivi loecher. Dove si ferma l'Agente?"
        },
        {
          "kind": "nochEiner",
          "title": "Il numero giusto",
          "text": "Passa a Python. Cambia il numero in range. L'Agente deve arrivare fino al muro."
        },
        {
          "kind": "remix",
          "title": "Altri blocchi",
          "text": "Riempi i buchi con un altro blocco. Mostralo al tuo compagno o alla tua compagna."
        }
      ],
      "tipSolution": "Il percorso ha 10 caselle e 4 buchi. 10 passi più 4 blocchi fanno 14 giri: for index in range(14):",
      "exercises": [
        {
          "prompt": "Il percorso ha 10 caselle e 4 buchi. Quanti giri servono all'Agente per arrivare all'ultima casella?"
        },
        {
          "prompt": "L'Agente resta fermo sul blocco d'oro. Quale riga è sbagliata?",
          "explain": "La condizione controlla FORWARD invece di DOWN. Davanti è libero, quindi mette sempre un blocco. Non parte mai."
        }
      ],
      "quiz": [
        {
          "q": "Che cosa significa else?",
          "answers": [
            {
              "text": "Altrimenti",
              "correct": true
            },
            {
              "text": "Finché",
              "correct": false
            },
            {
              "text": "Ripeti",
              "correct": false
            }
          ]
        },
        {
          "q": "Sotto l'Agente c'è un buco. Che cosa fa?",
          "answers": [
            {
              "text": "Mette un blocco",
              "correct": true
            },
            {
              "text": "Fa un passo",
              "correct": false
            },
            {
              "text": "Si gira",
              "correct": false
            }
          ]
        },
        {
          "q": "Il percorso ha 10 caselle e 2 buchi. Quanti giri servono all'Agente?",
          "answers": [
            {
              "text": "12",
              "correct": true
            },
            {
              "text": "10",
              "correct": false
            },
            {
              "text": "8",
              "correct": false
            }
          ]
        },
        {
          "q": "Quante delle due strade partono in un giro?",
          "answers": [
            {
              "text": "Esattamente una",
              "correct": true
            },
            {
              "text": "Entrambe",
              "correct": false
            },
            {
              "text": "Nessuna",
              "correct": false
            }
          ]
        }
      ]
    },
    "s12": {
      "title": "Finché",
      "storyShort": "La pista lunga ha molti buchi. Con while l'Agente va avanti finché davanti non c'è un muro. Non devi più contare.",
      "bridge": {
        "game": "Digiti ziel. L'Agente cammina finché davanti c'è un muro.",
        "code": "while ripete finché la condizione è vera. not la rovescia."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Fino al muro",
          "text": "Mettiti sul blocco d'oro della pista Traguardo. Guarda verso sud. Scrivi ziel. Passa a Python: trova la riga con while."
        },
        {
          "kind": "nochEiner",
          "title": "Senza contare",
          "text": "Percorri con ziel la pista Buchi. Lì ti serve ancora un numero?"
        },
        {
          "kind": "remix",
          "title": "La tua pista",
          "text": "Costruisci una pista tua con buchi e un muro. Mostrala a chi lavora con te."
        }
      ],
      "tipSolution": "while not agent.detect(AgentDetection.BLOCK, FORWARD): l'Agente va avanti finché davanti non c'è un blocco.",
      "exercises": [
        {
          "prompt": "L'Agente deve fermarsi su un blocco di redstone. Controlla il blocco sotto di sé."
        },
        {
          "prompt": "L'Agente non parte proprio. Quale riga è sbagliata?",
          "explain": "Manca il not. Davanti è libero, quindi la condizione è falsa. while non parte nemmeno una volta."
        }
      ],
      "quiz": [
        {
          "q": "Che cosa vuol dire while?",
          "answers": [
            {
              "text": "Finché",
              "correct": true
            },
            {
              "text": "Altrimenti",
              "correct": false
            },
            {
              "text": "Se",
              "correct": false
            }
          ]
        },
        {
          "q": "Che cosa fa not?",
          "answers": [
            {
              "text": "Rovescia la condizione",
              "correct": true
            },
            {
              "text": "Ferma l'Agente",
              "correct": false
            },
            {
              "text": "Cancella un blocco",
              "correct": false
            }
          ]
        },
        {
          "q": "Quando si ferma while not agent.detect(AgentDetection.BLOCK, FORWARD)?",
          "answers": [
            {
              "text": "Quando davanti c'è un blocco",
              "correct": true
            },
            {
              "text": "Dopo 20 giri",
              "correct": false
            },
            {
              "text": "Mai",
              "correct": false
            }
          ]
        },
        {
          "q": "Che cosa succede se non arriva mai un muro?",
          "answers": [
            {
              "text": "Il programma va avanti all'infinito",
              "correct": true
            },
            {
              "text": "L'Agente costruisce un muro",
              "correct": false
            },
            {
              "text": "Si ferma dopo 10 giri",
              "correct": false
            }
          ]
        }
      ],
      "bossCheck": {
        "title": "Boss-Check Oro",
        "subtitle": "Il percorso sconosciuto",
        "task": "Mettiti sul blocco d'oro dell'ultima pista. Guarda verso sud. Scrivi ziel. L'Agente passa oltre il redstone. Cambia la condizione in Python. Deve fermarsi sul redstone. Scrivi tre frasi: che cosa controlla la tua condizione? Perché il vecchio programma passa oltre il redstone? Che cosa succede se il redstone non arriva?"
      }
    }
  }
};
