// AUTO-GENERATED by scripts/translate.mjs — NICHT von Hand bearbeiten.
// Plan 2 Task 4/5: stations.s01 und stations.s03–s06 stehen hier vorübergehend auf Deutsch — Task 9 übersetzt sie.
// Manuell ergaenzt 03.09.2026 (Plan 2 Task 3): ui.bossCheckHeading/Hint + etappen.*.badge — de.js
// ist gewachsen, die volle Neuuebersetzung folgt erst in Plan 2 Task 9 (`translate.mjs --lang all`
// nach den neuen Stationen); bis dahin haelt dieser Handeintrag i18n-complete.test.js gruen.
// Source: src/i18n/de.js   sourceHash: 8edb57a86d18
// Language: it   model: claude-opus-5   generated: 2026-09-03T14:16:34.978Z
// Stuetz-Ebene: Deutsch bleibt daneben sichtbar. Bei Aenderung an de.js neu erzeugen.

export default {
  "ui": {
    "appTitle": "Mondo del codice",
    "tagline": "L'Agent capisce solo il codice.",
    "home": "Panoramica",
    "station": "Stazione {n}",
    "ds": "Lezione doppia {n}",
    "support": "Nella tua lingua",
    "supportShow": "Mostra l'aiuto nella tua lingua",
    "supportHide": "Nascondi l'aiuto",
    "storyHeading": "La storia",
    "conceptHeading": "L'idea",
    "bridgeGame": "Nel gioco",
    "bridgeCode": "Nel codice",
    "blocksLabel": "Così appare con i blocchi",
    "pythonLabel": "Così appare in Python",
    "tasksHeading": "I tuoi compiti nel gioco",
    "taskAuftrag": "Compito",
    "taskNochEiner": "Un altro",
    "taskRemix": "Remix",
    "tipsHeading": "Scala di suggerimenti",
    "tipStep": "Suggerimento {n}",
    "tipSolution": "Soluzione",
    "tipRemixNote": "Se prendi la soluzione: dopo devi cambiare una cosa. È obbligatorio.",
    "check": "Verifica",
    "checkHeading": "Hai capito?",
    "predictPrompt": "Dove si trova l'Agent alla fine? Clicca sulla casella.",
    "predictRight": "Giusto! L'Agent è esattamente lì.",
    "predictWrong": "Non ancora. Leggi il programma dall'alto verso il basso. Dove guarda il muso?",
    "parsonsPrompt": "Metti le righe nell'ordine giusto.",
    "parsonsUp": "in su",
    "parsonsDown": "in giù",
    "parsonsCheck": "Controlla",
    "parsonsRight": "Giusto! Questo è l'ordine.",
    "parsonsWrong": "Non ancora. Che cosa deve fare l'Agent per primo?",
    "spielstandHeading": "Punto della situazione",
    "spielstandPrompt": "Che cosa sai fare adesso? Scrivi tre frasi brevi.",
    "spielstandSave": "Salva",
    "spielstandSaved": "Salvato. Solo su questo dispositivo.",
    "progress": "Hai visitato {done} stazioni su {total}.",
    "next": "Avanti",
    "prev": "Indietro",
    "play": "Leggi ad alta voce",
    "langLabel": "Lingua",
    "footer": "Un modulo didattico di Dirk Schulenburg · CC BY 4.0 · Non è un prodotto ufficiale Minecraft.",
    "bossCheckHeading": "Verifica del boss",
    "bossCheckHint": "Risolvi il compito senza la scala di suggerimenti. Consegna lo Share-Link e scrivi tre frasi."
  },
  "glossary": {
    "befehl": {
      "term": "Comando",
      "short": "Una riga di codice. L'Agent fa esattamente questo."
    },
    "programm": {
      "term": "Programma",
      "short": "Tanti comandi, dall'alto verso il basso."
    },
    "sequenz": {
      "term": "Sequenza",
      "short": "L'ordine dei comandi."
    },
    "agent": {
      "term": "Agent",
      "short": "Il robot in Minecraft. Capisce solo il codice."
    },
    "zauberwort": {
      "term": "Parola magica",
      "short": "Una parola nella chat. Fa partire il tuo programma."
    },
    "python": {
      "term": "Python",
      "short": "Un linguaggio di programmazione. Il tuo codice come testo."
    },
    "bloecke": {
      "term": "Blocchi",
      "short": "Il tuo codice come mattoncini da trascinare."
    },
    "fehler": {
      "term": "Errore",
      "short": "L'Agent ti ha capito male. Puoi sistemarlo."
    }
  },
  "etappen": {
    "holz": {
      "name": "Legno",
      "badge": {
        "name": "Legno",
        "description": "Hai superato tutte le verifiche della tappa Legno e hai consegnato la verifica del boss."
      }
    },
    "stein": {
      "name": "Pietra",
      "badge": {
        "name": "Pietra",
        "description": "Hai superato tutte le verifiche della tappa Pietra e hai consegnato la verifica del boss."
      }
    },
    "eisen": {
      "name": "Ferro",
      "badge": {
        "name": "Ferro",
        "description": "Hai superato tutte le verifiche della tappa Ferro e hai consegnato la verifica del boss."
      }
    },
    "gold": {
      "name": "Oro",
      "badge": {
        "name": "Oro",
        "description": "Hai superato tutte le verifiche della tappa Oro e hai consegnato la verifica del boss."
      }
    },
    "diamant": {
      "name": "Diamante",
      "badge": {
        "name": "Diamante",
        "description": "Hai superato tutte le verifiche della tappa Diamante e hai consegnato la verifica del boss."
      }
    },
    "netherite": {
      "name": "Netherite",
      "badge": {
        "name": "Netherite",
        "description": "Hai superato tutte le verifiche della tappa Netherite e hai consegnato la verifica del boss."
      }
    },
    "enderdrache": {
      "name": "Drago dell'End",
      "badge": {
        "name": "Drago dell'End",
        "description": "Hai superato tutte le verifiche della tappa Drago dell'End e hai consegnato la verifica del boss."
      }
    }
  },
  "stations": {
    "s01": {
      "title": "Die neue Welt",
      "storyShort": "Der Agent ist dein Roboter in Minecraft. Er versteht kein Deutsch, nur Code. Er startet erst, wenn du ein Zauberwort in den Chat schreibst.",
      "bridge": {
        "game": "Du tippst hi in den Chat. Der Agent kommt zu dir und geht einen Schritt.",
        "code": "Ein Befehl ist eine Zeile Code. Das Zauberwort startet das ganze Programm."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Sag hi",
          "text": "Schreibe hi in den Chat. Der Agent kommt zu dir. Dann geht er einen Schritt vor."
        },
        {
          "kind": "nochEiner",
          "title": "Dein Wort",
          "text": "Ändere das Zauberwort von hi zu hallo. Ändere die Schritte von 1 auf 3. Probier es aus."
        },
        {
          "kind": "remix",
          "title": "Noch ein Wort",
          "text": "Erfinde ein zweites Zauberwort. Der Agent soll damit etwas anderes machen. Zeig es deinem Partner oder deiner Partnerin."
        }
      ],
      "tipSolution": "Schreibe agent.teleport_to_player() und darunter agent.move(FORWARD, 3). In der letzten Zeile ersetzt du \"hi\" durch \"hallo\". Nur das Wort in den Anführungszeichen. Dann tippst du hallo in den Chat.",
      "exercises": [
        {
          "prompt": "Der Agent steht unten in der Mitte. Seine Nase zeigt nach oben. Das Programm: 1 Schritt vor."
        },
        {
          "prompt": "Der Agent soll zu dir kommen und einen Schritt gehen. Die Zeile mit dem Zauberwort kommt zum Schluss."
        }
      ],
      "quiz": [
        {
          "q": "Wozu ist das Zauberwort da?",
          "answers": [
            {
              "text": "Es startet dein Programm",
              "correct": true
            },
            {
              "text": "Es öffnet den Code Builder",
              "correct": false
            },
            {
              "text": "Es speichert dein Programm",
              "correct": false
            }
          ]
        },
        {
          "q": "Welche Taste öffnet den Code Builder?",
          "answers": [
            {
              "text": "Die Taste C",
              "correct": true
            },
            {
              "text": "Die Taste E",
              "correct": false
            },
            {
              "text": "Die Taste T",
              "correct": false
            }
          ]
        },
        {
          "q": "Was macht agent.teleport_to_player()?",
          "answers": [
            {
              "text": "Der Agent kommt zu dir",
              "correct": true
            },
            {
              "text": "Der Agent geht einen Schritt vor",
              "correct": false
            },
            {
              "text": "Der Agent legt einen Block",
              "correct": false
            }
          ]
        },
        {
          "q": "Der Agent versteht …",
          "answers": [
            {
              "text": "nur Code",
              "correct": true
            },
            {
              "text": "jedes Wort im Chat",
              "correct": false
            },
            {
              "text": "Deutsch, wenn du langsam schreibst",
              "correct": false
            }
          ]
        }
      ]
    },
    "s02": {
      "title": "L'ordine conta",
      "storyShort": "L'Agent esegue i comandi esattamente nell'ordine in cui li scrivi. Prima camminare e poi girare non è la stessa cosa che prima girare e poi camminare.",
      "bridge": {
        "game": "L'Agent cammina passo dopo passo e posa blocchi dietro di sé.",
        "code": "Un programma è una lista di comandi. Il computer li esegue dall'alto verso il basso."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Il sentiero",
          "text": "Scrivi la parola magica weg nella chat. L'Agent posa tre blocchi. Guarda bene: dov'è l'angolo?"
        },
        {
          "kind": "nochEiner",
          "title": "Più lungo",
          "text": "Cambia il programma. L'Agent deve posare cinque blocchi, poi girare l'angolo e poi ancora due."
        },
        {
          "kind": "remix",
          "title": "Il tuo disegno",
          "text": "Costruisci un tuo disegno con i blocchi. Per esempio una Z o una U. Mostralo al tuo compagno o alla tua compagna."
        }
      ],
      "tipSolution": "Per cinque blocchi: scrivi agent.move(FORWARD, 1) e agent.place(BACK) cinque volte. Poi agent.turn(LEFT_TURN). Poi ancora due volte move e place.",
      "exercises": [
        {
          "prompt": "L'Agent sta in basso al centro. Il suo naso punta verso l'alto. Il programma: 2 passi avanti, girare a sinistra, 1 passo avanti."
        },
        {
          "prompt": "L'Agent deve venire da te, fare due passi, girare a sinistra e fare ancora un passo."
        }
      ],
      "quiz": [
        {
          "q": "L'Agent deve fare 3 passi e poi girare a sinistra. Quale ordine è giusto?",
          "answers": [
            {
              "text": "Prima agent.move(FORWARD, 3), poi agent.turn(LEFT_TURN)",
              "correct": true
            },
            {
              "text": "Prima agent.turn(LEFT_TURN), poi agent.move(FORWARD, 3)",
              "correct": false
            },
            {
              "text": "L'ordine non conta",
              "correct": false
            }
          ]
        },
        {
          "q": "Scrivi agent.move(FORWARD, 3) due volte, una sotto l'altra. Cosa fa l'Agent?",
          "answers": [
            {
              "text": "Fa 6 passi",
              "correct": true
            },
            {
              "text": "Fa 3 passi",
              "correct": false
            },
            {
              "text": "Segnala un errore",
              "correct": false
            }
          ]
        },
        {
          "q": "Quando parte il tuo programma?",
          "answers": [
            {
              "text": "Quando scrivi la parola magica nella chat",
              "correct": true
            },
            {
              "text": "Subito, quando apri il Code Builder",
              "correct": false
            },
            {
              "text": "Quando clicchi sull'Agent",
              "correct": false
            }
          ]
        },
        {
          "q": "L'Agent capisce …",
          "answers": [
            {
              "text": "solo il codice",
              "correct": true
            },
            {
              "text": "il tedesco e l'inglese",
              "correct": false
            },
            {
              "text": "ogni lingua",
              "correct": false
            }
          ]
        }
      ]
    },
    "s03": {
      "title": "Zauberwörter",
      "storyShort": "Ein Wort im Chat ist ein Ereignis. Jedes Zauberwort startet sein eigenes Programm. Du kannst mehrere Zauberwörter haben.",
      "bridge": {
        "game": "Du tippst weg oder turm in den Chat. Der Agent baut den Weg oder den Turm.",
        "code": "Jedes Zauberwort hat einen eigenen Hut-Block. Darunter steht sein eigenes Programm."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Zwei Wörter",
          "text": "Schreibe weg in den Chat. Dann schreibe turm. Der Weg ist hier kürzer als in Station 2. Schau dir beides genau an."
        },
        {
          "kind": "nochEiner",
          "title": "Höher",
          "text": "Ändere das Programm für turm. Der Turm soll fünf Blöcke hoch werden."
        },
        {
          "kind": "remix",
          "title": "Die Brücke",
          "text": "Erfinde ein drittes Zauberwort: brücke. Der Agent baut damit einen Weg über eine Lücke."
        }
      ],
      "tipSolution": "Für fünf Blöcke schreibst du agent.place(FORWARD) und agent.move(UP, 1) abwechselnd. Am Ende kommt noch einmal agent.place(FORWARD). Zähle nach: fünf Zeilen mit place.",
      "exercises": [
        {
          "prompt": "Der Agent steht unten links. Seine Nase zeigt nach oben. Das Programm: 2 Schritte vor, rechts drehen, 2 Schritte vor."
        },
        {
          "prompt": "Der Agent kommt zu dir. Er nimmt Gras. Er geht einen Schritt und legt einen Block. Die Zeile mit dem Zauberwort kommt zum Schluss."
        }
      ],
      "quiz": [
        {
          "q": "Was ist ein Ereignis?",
          "answers": [
            {
              "text": "Etwas passiert im Spiel, zum Beispiel ein Wort im Chat",
              "correct": true
            },
            {
              "text": "Ein Fehler in deinem Programm",
              "correct": false
            },
            {
              "text": "Ein Block, den der Agent legt",
              "correct": false
            }
          ]
        },
        {
          "q": "Du hast zwei Zauberwörter. Wie viele Programme sind das?",
          "answers": [
            {
              "text": "Zwei. Jedes Wort hat sein eigenes Programm",
              "correct": true
            },
            {
              "text": "Eins. Beide Wörter starten dasselbe Programm",
              "correct": false
            },
            {
              "text": "Keins. Zwei Zauberwörter gehen nicht",
              "correct": false
            }
          ]
        },
        {
          "q": "Was macht agent.move(UP, 1)?",
          "answers": [
            {
              "text": "Der Agent geht einen Block nach oben",
              "correct": true
            },
            {
              "text": "Der Agent geht einen Schritt nach vorne",
              "correct": false
            },
            {
              "text": "Der Agent legt einen Block über sich",
              "correct": false
            }
          ]
        },
        {
          "q": "Du tippst erst weg, dann turm. Was passiert?",
          "answers": [
            {
              "text": "Erst läuft das Programm für weg, dann das für turm",
              "correct": true
            },
            {
              "text": "Beide Programme laufen gleichzeitig",
              "correct": false
            },
            {
              "text": "Nur das Programm für turm läuft",
              "correct": false
            }
          ]
        }
      ],
      "bossCheck": {
        "title": "Boss-Check Holz",
        "subtitle": "Das L",
        "task": "Der Agent legt ein L: erst 4 Blöcke geradeaus, dann 2 um die Ecke. Was macht dein Programm? Warum ist die Reihenfolge wichtig? Was war schwer?"
      }
    },
    "s04": {
      "title": "Wiederholen",
      "storyShort": "Zehnmal dasselbe zu schreiben ist mühsam. Dafür gibt es die Schleife. Du schreibst die Zeilen einmal. Der Computer wiederholt sie für dich.",
      "bridge": {
        "game": "Du tippst mauer in den Chat. Der Agent legt zehn Blöcke in einer Reihe.",
        "code": "Eine Schleife wiederholt zwei Zeilen zehnmal. Du schreibst sie nur einmal."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Die Mauer",
          "text": "Schreibe mauer in den Chat. Der Agent baut eine Mauer aus zehn Blöcken. Zähle die Blöcke nach."
        },
        {
          "kind": "nochEiner",
          "title": "Länger und anders",
          "text": "Ändere die Zahl von 10 auf 20. Nimm eine andere Blockart, zum Beispiel Holz. Probier es aus."
        },
        {
          "kind": "remix",
          "title": "Zwei Mauern",
          "text": "Baue zwei Mauern mit einer Lücke dazwischen. Zeig es deinem Partner oder deiner Partnerin."
        }
      ],
      "tipSolution": "Schreibe for index in range(20): in die Schleifenzeile. Die zwei Zeilen darunter bleiben eingerückt. Für Holz nimmst du agent.set_item(PLANKS_OAK, 64, 1). Zähle nach: eine Schleife, zwei Zeilen im Bauch.",
      "exercises": [
        {
          "prompt": "Der Agent steht unten in der Mitte. Seine Nase zeigt nach oben. Das Programm: 3 Schritte vor."
        },
        {
          "prompt": "Der Agent kommt zu dir und nimmt Bruchstein. Dann wiederholt die Schleife zwei Zeilen. Die Einrückung gehört zur Zeile."
        }
      ],
      "quiz": [
        {
          "q": "Was spart die Schleife?",
          "answers": [
            {
              "text": "Viele gleiche Zeilen",
              "correct": true
            },
            {
              "text": "Blöcke im Rucksack",
              "correct": false
            },
            {
              "text": "Platz in der Welt",
              "correct": false
            }
          ]
        },
        {
          "q": "Wie oft läuft eine Schleife mit range(10)?",
          "answers": [
            {
              "text": "Zehnmal",
              "correct": true
            },
            {
              "text": "Neunmal",
              "correct": false
            },
            {
              "text": "Elfmal",
              "correct": false
            }
          ]
        },
        {
          "q": "Bei welcher Zahl fängt der Computer an zu zählen?",
          "answers": [
            {
              "text": "Bei 0",
              "correct": true
            },
            {
              "text": "Bei 1",
              "correct": false
            },
            {
              "text": "Bei 10",
              "correct": false
            }
          ]
        },
        {
          "q": "Was passiert bei range(0)?",
          "answers": [
            {
              "text": "Nichts. Die Schleife läuft keinmal",
              "correct": true
            },
            {
              "text": "Die Schleife läuft einmal",
              "correct": false
            },
            {
              "text": "Der Agent meldet einen Fehler",
              "correct": false
            }
          ]
        }
      ]
    },
    "s05": {
      "title": "Schleife in der Schleife",
      "storyShort": "Eine Schleife kann in einer Schleife stehen. Die innere Schleife baut eine Reihe. Die äußere Schleife wiederholt die Reihe. So wird aus der Reihe eine Wand.",
      "bridge": {
        "game": "Du tippst wand in den Chat. Der Agent baut eine Wand aus drei Reihen.",
        "code": "Eine Schleife steht im Bauch der anderen. Innen die Reihe, außen die Ebenen."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Die Wand",
          "text": "Schreibe wand in den Chat. Der Agent baut eine Wand: 6 Blöcke breit, 3 hoch."
        },
        {
          "kind": "nochEiner",
          "title": "Größer",
          "text": "Ändere die Wand auf 8 Blöcke breit und 4 hoch. Welche zwei Zahlen musst du ändern?"
        },
        {
          "kind": "remix",
          "title": "Das Fenster",
          "text": "Baue eine Wand mit einem Fenster. Eine Reihe wird dafür kürzer. Zeig es deinem Partner oder deiner Partnerin."
        }
      ],
      "tipSolution": "Schreibe for index in range(4): in die äußere Schleife. Das ist die Höhe. Schreibe for index2 in range(8): in die innere Schleife. Das ist die Breite. Nach den zwei Drehungen kommt ein Schritt vor. So steht der Agent wieder über der Reihe. Zähle nach: zwei Schleifen, eine im Bauch der anderen.",
      "exercises": [
        {
          "prompt": "Der Agent steht unten links. Seine Nase zeigt nach oben. Das Programm: 2 Schritte vor, links drehen, links drehen, 1 Schritt vor."
        },
        {
          "prompt": "Der Agent hat schon Bruchstein dabei. Jetzt kommt die Wand: außen die Ebenen, innen die Reihe. Die Drehungen und der Schritt danach fehlen hier. Achte auf die Einrückung."
        }
      ],
      "quiz": [
        {
          "q": "Die Wand ist 6 Blöcke breit und 3 hoch. Wie viele Blöcke sind das?",
          "answers": [
            {
              "text": "18 Blöcke",
              "correct": true
            },
            {
              "text": "9 Blöcke",
              "correct": false
            },
            {
              "text": "24 Blöcke",
              "correct": false
            }
          ]
        },
        {
          "q": "Was macht die innere Schleife?",
          "answers": [
            {
              "text": "Sie baut eine Reihe",
              "correct": true
            },
            {
              "text": "Sie geht eine Ebene hoch",
              "correct": false
            },
            {
              "text": "Sie dreht den Agenten um",
              "correct": false
            }
          ]
        },
        {
          "q": "Warum dreht der Agent zweimal nach links?",
          "answers": [
            {
              "text": "Damit er zurückschaut und die nächste Reihe baut",
              "correct": true
            },
            {
              "text": "Damit er schneller läuft",
              "correct": false
            },
            {
              "text": "Damit er einen Block legen kann",
              "correct": false
            }
          ]
        },
        {
          "q": "Welche Schleife läuft zuerst ganz durch?",
          "answers": [
            {
              "text": "Die innere. Sie baut erst die ganze Reihe",
              "correct": true
            },
            {
              "text": "Die äußere. Sie geht erst ganz nach oben",
              "correct": false
            },
            {
              "text": "Beide laufen gleichzeitig",
              "correct": false
            }
          ]
        }
      ]
    },
    "s06": {
      "title": "Das Haus",
      "storyShort": "Ein Haus hat vier Wände. Du kopierst die Wand nicht viermal. Du legst eine Schleife außen herum. Nach jeder Seite dreht sich der Agent.",
      "bridge": {
        "game": "Du tippst haus in den Chat. Der Agent baut einen Ring aus vier Seiten.",
        "code": "Die äußere Schleife läuft viermal. Nach jeder Seite dreht der Agent um die Ecke."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Der Ring",
          "text": "Schreibe haus in den Chat. Der Agent baut einen Ring: 5 Blöcke pro Seite."
        },
        {
          "kind": "nochEiner",
          "title": "Höher",
          "text": "Der Ring soll 3 Blöcke hoch werden. Dafür brauchst du eine dritte Schleife."
        },
        {
          "kind": "remix",
          "title": "Die Tür",
          "text": "Lass in einer Wand eine Lücke als Tür. Zeig dein Haus deinem Partner oder deiner Partnerin."
        }
      ],
      "tipSolution": "Schreibe for index3 in range(3): ganz nach außen. Der ganze Ring steht eingerückt darin. Danach kommt agent.move(UP, 1). Zähle nach: drei Schleifen, eine in der anderen.",
      "exercises": [
        {
          "prompt": "Der Agent steht unten in der Mitte. Seine Nase zeigt nach oben. Das Programm: 2 Schritte vor, links drehen. Dann noch einmal: 2 Schritte vor, links drehen. Zum Schluss 2 Schritte vor."
        },
        {
          "prompt": "Der Agent baut einen Ring. Innen eine Seite, außen die vier Seiten. Die Drehung gehört zur äußeren Schleife."
        }
      ],
      "quiz": [
        {
          "q": "Wie viele Seiten baut range(4)?",
          "answers": [
            {
              "text": "Vier",
              "correct": true
            },
            {
              "text": "Drei",
              "correct": false
            },
            {
              "text": "Fünf",
              "correct": false
            }
          ]
        },
        {
          "q": "Wo steht agent.turn(LEFT_TURN)?",
          "answers": [
            {
              "text": "In der äußeren Schleife, nach der inneren",
              "correct": true
            },
            {
              "text": "In der inneren Schleife, bei jedem Block",
              "correct": false
            },
            {
              "text": "Ganz oben, vor beiden Schleifen",
              "correct": false
            }
          ]
        },
        {
          "q": "Warum dreht der Agent nur einmal pro Wand?",
          "answers": [
            {
              "text": "Weil eine Ecke eine Vierteldrehung ist",
              "correct": true
            },
            {
              "text": "Weil er sonst zu langsam wird",
              "correct": false
            },
            {
              "text": "Weil er sonst keine Blöcke mehr hat",
              "correct": false
            }
          ]
        },
        {
          "q": "Der Ring hat 4 Seiten mit je 5 Blöcken. Wie viele Blöcke sind das?",
          "answers": [
            {
              "text": "20 Blöcke",
              "correct": true
            },
            {
              "text": "16 Blöcke",
              "correct": false
            },
            {
              "text": "25 Blöcke",
              "correct": false
            }
          ]
        }
      ],
      "bossCheck": {
        "title": "Boss-Check Stein",
        "subtitle": "Der Zaun",
        "task": "Baue einen Zaun um dich herum. Der Ring hat 8 Blöcke pro Seite. Was spart die Schleife? Wie viele Befehle wären es ohne Schleife?"
      }
    }
  }
};
