// AUTO-GENERATED by scripts/translate.mjs — NICHT von Hand bearbeiten.
// Source: src/i18n/de.js   sourceHash: c7de4d5be70a
// chunkHashes: {"ui":"48b164a63157","glossary":"5e6ca7f76272","etappen":"29e40128f71f","stations.s01":"c37b979d7d58","stations.s02":"63074802c205","stations.s03":"46eb47fc72b0","stations.s04":"8ed8fda3f3c3","stations.s05":"def7d38db5cd","stations.s06":"d4b61513c098","stations.s07":"242bf36d69d3","stations.s08":"2afc4366e9a0","stations.s09":"4478badd8d82"}
// Language: uk   model: claude-opus-5   generated: 2026-09-16T17:10:17.591Z
// Stuetz-Ebene: Deutsch bleibt daneben sichtbar. Bei Aenderung an de.js neu erzeugen.
// Handkorrektur 2026-09-03 (Review T9): zwei durchgaengige Korrekturen, deshalb hier gebuendelt
// statt an jeder Zeile: (1) lateinisch "Agent" statt "Агент" an 7 Stellen in s05 — der Rest
// der Datei schreibt den Namen schon lateinisch (Kanon AGENT_CANON in scripts/translate.mjs);
// (2) alle sieben etappen.*.badge.description unpersoenlich formuliert ("Усі перевірки етапу
// … пройдено, бос-перевірку здано") statt mit maennlichem Partizip ("Ти пройшов … і здав").
// Einzelkorrekturen sind unten in der Zeile davor markiert.

export default {
  "ui": {
    "appTitle": "Світ коду",
    "tagline": "Agent розуміє тільки код.",
    "home": "Огляд",
    "station": "Станція {n}",
    "ds": "Подвійний урок {n}",
    "support": "Твоєю мовою",
    "supportShow": "Показати допомогу твоєю мовою",
    "supportHide": "Сховати допомогу",
    "storyHeading": "Історія",
    "conceptHeading": "Ідея",
    "bridgeGame": "У грі",
    "bridgeCode": "У коді",
    "blocksLabel": "Так це виглядає у блоках",
    "pythonLabel": "Так це виглядає у Python",
    "tasksHeading": "Твої завдання у грі",
    "taskAuftrag": "Завдання",
    "taskNochEiner": "Ще одне",
    "taskRemix": "Ремікс",
    "tipsHeading": "Драбинка підказок",
    "tipStep": "Підказка {n}",
    "tipSolution": "Розв'язок",
    "tipRemixNote": "Якщо береш готовий розв'язок: після цього зміни одну річ. Це обов'язково.",
    "check": "Перевірка",
    // Vermerk 2026-09-04 (Plan 3 Task 9): unpersoenliche Form, kein maennliches Partizip (der Lauf
    // vom 03.09. lieferte "Зрозумів?"). Der neue ui-Lauf hat die Fassung bestaetigt; der Vermerk
    // stand vorher an dieser Zeile und wird hier fortgeschrieben.
    "checkHeading": "Зрозуміло?",
    "predictPrompt": "Де стоїть Agent у кінці? Натисни на поле.",
    "predictRight": "Правильно! Agent стоїть саме там.",
    "predictWrong": "Ще ні. Читай програму згори вниз. Куди дивиться ніс?",
    "parsonsPrompt": "Постав рядки у правильному порядку.",
    "parsonsUp": "вгору",
    "parsonsDown": "вниз",
    "parsonsCheck": "Перевірити",
    "parsonsRight": "Правильно! Це той порядок.",
    "parsonsWrong": "Ще ні. Що Agent має зробити спочатку?",
    "checkButton": "Перевірити",
    "matchPrompt": "Який блок пасує до якого рядка? Спочатку блок, потім рядок.",
    "matchRight": "Правильно! Кожен блок має свій рядок.",
    "matchWrong": "Ще ні. Подивись на числа й назви у блоках.",
    "fillPrompt": "Обери для кожного пропуску правильну відповідь.",
    "fillRight": "Правильно! Код працює.",
    "fillWrong": "Ще ні. Один пропуск не пасує.",
    "findbugPrompt": "Один рядок неправильний. Який?",
    "findbugRight": "Правильно! Це помилка.",
    "findbugWrong": "Ні, цей рядок правильний. Подивись ще раз.",
    // Handübersetzung 17.09.2026 (Plan 4 Task 2), Task 9 ersetzt sie
    "typePrompt": "Впиши в кожен пропуск правильне число або слово.",
    "typeRight": "Правильно! Ось так працює код.",
    "typeWrong": "Ще ні. Прочитай рядок ще раз.",
    "typeCase": "Майже. Python розрізняє великі й малі літери.",
    "typeGapLabel": "Пропуск",
    "spielstandHeading": "Мій результат",
    "spielstandPrompt": "Що ти вмієш тепер? Напиши три короткі речення.",
    "spielstandSave": "Зберегти",
    "spielstandSaved": "Збережено. Тільки на цьому пристрої.",
    // Handkorrektur 2026-09-04 (Plan 3 Task 9): unpersoenliche Form statt "відвідав(ла)" — dieselbe
    // Korrektur wie in der Re-Review am 04.09. Platzhalter {done}/{total} unveraendert.
    "progress": "Пройдено {done} з {total} станцій.",
    "next": "Далі",
    "prev": "Назад",
    "play": "Прочитати вголос",
    "langLabel": "Мова",
    "footer": "Навчальний модуль від Dirk Schulenburg · CC BY 4.0 · Не є офіційним продуктом Minecraft.",
    "bossCheckHeading": "Бос-перевірка",
    "bossCheckHint": "Виконай завдання без драбинки підказок. Здай Share-Link і напиши три речення."
  },
  "glossary": {
    "befehl": {
      "term": "Команда",
      "short": "Один рядок коду. Agent робить саме це."
    },
    "programm": {
      "term": "Програма",
      "short": "Багато команд, згори вниз."
    },
    "sequenz": {
      "term": "Послідовність",
      "short": "Порядок команд."
    },
    "agent": {
      "term": "Agent",
      "short": "Робот у Minecraft. Він розуміє тільки код."
    },
    "zauberwort": {
      "term": "Чарівне слово",
      "short": "Слово в чаті. Воно запускає твою програму."
    },
    "python": {
      "term": "Python",
      "short": "Мова програмування. Твій код як текст."
    },
    "bloecke": {
      "term": "Блоки",
      "short": "Твій код як цеглинки, які можна перетягувати."
    },
    "fehler": {
      "term": "Помилка",
      "short": "Agent зрозумів тебе неправильно. Ти можеш це виправити."
    },
    "variable": {
      "term": "Змінна",
      "short": "Число з іменем. Ти задаєш його один раз угорі."
    },
    "koordinaten": {
      "term": "Координати",
      "short": "Три числа x, y, z кажуть, де є блок."
    },
    "fill": {
      "term": "fill",
      "short": "Заповнює все між двома кутами одним блоком."
    },
    "zaehler": {
      "term": "Лічильник",
      "short": "Цикл рахує разом: index — це 0, 1, 2 …"
    }
  },
  "etappen": {
    "holz": {
      "name": "Дерево",
      "badge": {
        "name": "Дерево",
        "description": "Усі перевірки етапу «Дерево» пройдено, бос-перевірку здано."
      }
    },
    "stein": {
      "name": "Камінь",
      "badge": {
        "name": "Камінь",
        "description": "Усі перевірки етапу «Камінь» пройдено, бос-перевірку здано."
      }
    },
    "eisen": {
      "name": "Залізо",
      "badge": {
        "name": "Залізо",
        "description": "Усі перевірки етапу «Залізо» пройдено, бос-перевірку здано."
      }
    },
    "gold": {
      "name": "Золото",
      "badge": {
        "name": "Золото",
        "description": "Усі перевірки етапу «Золото» пройдено, бос-перевірку здано."
      }
    },
    "diamant": {
      "name": "Алмаз",
      "badge": {
        "name": "Алмаз",
        "description": "Усі перевірки етапу «Алмаз» пройдено, бос-перевірку здано."
      }
    },
    "netherite": {
      "name": "Незерит",
      "badge": {
        "name": "Незерит",
        "description": "Усі перевірки етапу «Незерит» пройдено, бос-перевірку здано."
      }
    },
    "enderdrache": {
      "name": "Дракон Енду",
      "badge": {
        "name": "Дракон Енду",
        "description": "Усі перевірки етапу «Дракон Енду» пройдено, бос-перевірку здано."
      }
    }
  },
  "stations": {
    "s01": {
      "title": "Новий світ",
      "storyShort": "Agent — це твій робот у Minecraft. Він не розуміє німецької, лише код. Він стартує лише тоді, коли ти напишеш чарівне слово в чат.",
      "bridge": {
        "game": "Ти пишеш hi в чат. Agent приходить до тебе і робить один крок.",
        "code": "Команда — це один рядок коду. Чарівне слово запускає всю програму."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Скажи hi",
          "text": "Напиши hi в чат. Agent прийде до тебе. Потім він зробить крок вперед."
        },
        {
          "kind": "nochEiner",
          "title": "Твоє слово",
          "text": "Зміни чарівне слово з hi на hallo. Зміни кроки з 1 на 3. Спробуй."
        },
        {
          "kind": "remix",
          "title": "Ще одне слово",
          "text": "Придумай друге чарівне слово. Agent має зробити щось інше. Покажи це своєму партнеру або партнерці."
        }
      ],
      "tipSolution": "Напиши agent.teleport_to_player(), а під ним agent.move(FORWARD, 3). В останньому рядку заміни «hi» на «hallo». Тільки слово в лапках. Потім напиши hallo в чат.",
      "exercises": [
        {
          "prompt": "Agent стоїть внизу посередині. Його ніс дивиться вгору. Програма: 1 крок вперед."
        },
        {
          "prompt": "Agent має прийти до тебе і зробити крок. Рядок із чарівним словом іде в кінці."
        }
      ],
      "quiz": [
        {
          "q": "Для чого потрібне чарівне слово?",
          "answers": [
            {
              "text": "Воно запускає твою програму",
              "correct": true
            },
            {
              "text": "Воно відкриває Code Builder",
              "correct": false
            },
            {
              "text": "Воно зберігає твою програму",
              "correct": false
            }
          ]
        },
        {
          "q": "Яка клавіша відкриває Code Builder?",
          "answers": [
            {
              "text": "Клавіша C",
              "correct": true
            },
            {
              "text": "Клавіша E",
              "correct": false
            },
            {
              "text": "Клавіша T",
              "correct": false
            }
          ]
        },
        {
          "q": "Що робить agent.teleport_to_player()?",
          "answers": [
            {
              "text": "Agent приходить до тебе",
              "correct": true
            },
            {
              "text": "Agent робить крок вперед",
              "correct": false
            },
            {
              "text": "Agent ставить блок",
              "correct": false
            }
          ]
        },
        {
          "q": "Agent розуміє …",
          "answers": [
            {
              "text": "лише код",
              "correct": true
            },
            {
              "text": "кожне слово в чаті",
              "correct": false
            },
            {
              "text": "німецьку, якщо писати повільно",
              "correct": false
            }
          ]
        }
      ]
    },
    "s02": {
      "title": "Порядок має значення",
      "storyShort": "Agent виконує команди точно в тому порядку, як ти їх пишеш. Спочатку йти, потім повернути — це не те саме, що спочатку повернути, потім іти.",
      "bridge": {
        "game": "Agent іде крок за кроком і кладе за собою блоки.",
        "code": "Програма — це список команд. Компʼютер виконує їх зверху вниз."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Шлях",
          "text": "Напиши чарівне слово weg у чат. Agent покладе чотири блоки. Подивись уважно: де кут?"
        },
        {
          "kind": "nochEiner",
          "title": "Довше",
          "text": "Зміни програму. Agent кладе пʼять блоків прямо, потім кут, потім ще два."
        },
        {
          "kind": "remix",
          "title": "Твій візерунок",
          "text": "Побудуй власний візерунок із блоків. Наприклад, літеру Z або U. Покажи його своєму партнеру або партнерці."
        }
      ],
      "tipSolution": "Для пʼяти блоків: напиши agent.move(FORWARD, 1) і agent.place(BACK) пʼять разів. Потім agent.turn(LEFT_TURN). Після цього ще три пари move і place. Перша пара кладе кутовий блок.",
      "exercises": [
        {
          "prompt": "Agent стоїть знизу в центрі. Його «ніс» дивиться вгору. Програма: 2 кроки вперед, повернути ліворуч, 1 крок вперед."
        },
        {
          "prompt": "Agent має підійти до тебе: зробити два кроки, повернути ліворуч і зробити ще один крок."
        }
      ],
      "quiz": [
        {
          "q": "Agent має зробити 3 кроки, а потім повернути ліворуч. Який порядок правильний?",
          "answers": [
            {
              "text": "Спочатку agent.move(FORWARD, 3), потім agent.turn(LEFT_TURN)",
              "correct": true
            },
            {
              "text": "Спочатку agent.turn(LEFT_TURN), потім agent.move(FORWARD, 3)",
              "correct": false
            },
            {
              "text": "Порядок не має значення",
              "correct": false
            }
          ]
        },
        {
          "q": "Ти пишеш agent.move(FORWARD, 3) двічі одне під одним. Що зробить Agent?",
          "answers": [
            {
              "text": "Він пройде 6 кроків",
              "correct": true
            },
            {
              "text": "Він пройде 3 кроки",
              "correct": false
            },
            {
              "text": "Він покаже помилку",
              "correct": false
            }
          ]
        },
        {
          "q": "Коли запускається твоя програма?",
          "answers": [
            {
              "text": "Коли ти напишеш чарівне слово у чат",
              "correct": true
            },
            {
              "text": "Одразу, коли ти відкриєш Code Builder",
              "correct": false
            },
            {
              "text": "Коли ти клікнеш на Agent",
              "correct": false
            }
          ]
        },
        {
          "q": "Agent розуміє …",
          "answers": [
            {
              "text": "тільки код",
              "correct": true
            },
            {
              "text": "німецьку та англійську",
              "correct": false
            },
            {
              "text": "будь-яку мову",
              "correct": false
            }
          ]
        }
      ]
    },
    "s03": {
      "title": "Чарівні слова",
      "storyShort": "Слово в чаті — це подія. Кожне чарівне слово запускає свою програму. Ти можеш мати кілька чарівних слів.",
      "bridge": {
        "game": "Ти пишеш weg або turm у чат. Agent будує шлях або вежу.",
        "code": "Кожне чарівне слово має свій блок-капелюх. Під ним стоїть його власна програма."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Два слова",
          "text": "Напиши weg у чат. Потім напиши turm. Шлях тут коротший, ніж на Станції 2. Подивись уважно на обидва."
        },
        {
          "kind": "nochEiner",
          "title": "Вище",
          "text": "Зміни програму для turm. Вежа має бути заввишки п'ять блоків."
        },
        {
          "kind": "remix",
          "title": "Міст",
          "text": "Придумай третє чарівне слово: bruecke. Чарівні слова не мають умлаутів. Agent будує з ним шлях через прогалину."
        }
      ],
      "tipSolution": "Для п'яти блоків пиши agent.place(FORWARD) і agent.move(UP, 1) по черзі. У кінці ще раз agent.place(FORWARD). Порахуй: п'ять рядків із place.",
      "exercises": [
        {
          "prompt": "Agent стоїть унизу зліва. Його ніс дивиться вгору. Програма: 2 кроки вперед, поворот праворуч, 2 кроки вперед."
        },
        {
          "prompt": "Agent приходить до тебе. Він бере траву. Він робить один крок і кладе блок. Рядок із чарівним словом іде в кінці."
        }
      ],
      "quiz": [
        {
          "q": "Що таке подія?",
          "answers": [
            {
              "text": "Щось відбувається у грі, наприклад слово в чаті",
              "correct": true
            },
            {
              "text": "Помилка у твоїй програмі",
              "correct": false
            },
            {
              "text": "Блок, який кладе Agent",
              "correct": false
            }
          ]
        },
        {
          "q": "У тебе два чарівні слова. Скільки це програм?",
          "answers": [
            {
              "text": "Дві. Кожне слово має свою програму",
              "correct": true
            },
            {
              "text": "Одна. Обидва слова запускають ту саму програму",
              "correct": false
            },
            {
              "text": "Жодної. Два чарівні слова неможливі",
              "correct": false
            }
          ]
        },
        {
          "q": "Що робить agent.move(UP, 1)?",
          "answers": [
            {
              "text": "Agent піднімається на один блок угору",
              "correct": true
            },
            {
              "text": "Agent робить один крок уперед",
              "correct": false
            },
            {
              "text": "Agent кладе блок над собою",
              "correct": false
            }
          ]
        },
        {
          "q": "Ти пишеш спершу weg, потім turm. Що станеться?",
          "answers": [
            {
              "text": "Спершу виконається програма для weg, потім для turm",
              "correct": true
            },
            {
              "text": "Обидві програми виконаються одночасно",
              "correct": false
            },
            {
              "text": "Виконається лише програма для turm",
              "correct": false
            }
          ]
        }
      ],
      "bossCheck": {
        "title": "Бос-перевірка: Дерево",
        "subtitle": "Літера L",
        "task": "Agent кладе L: спершу 4 блоки прямо, потім 2 за ріг. Що робить твоя програма? Чому порядок важливий? Що було складно?"
      }
    },
    "s04": {
      "title": "Повторення",
      "storyShort": "Писати десять разів те саме — виснажливо. Для цього є цикл. Ти пишеш рядки один раз. Комп'ютер повторює їх за тебе.",
      "bridge": {
        "game": "Ти пишеш mauer у чат. Agent кладе десять блоків у ряд.",
        "code": "Цикл повторює два рядки десять разів. Ти пишеш їх лише один раз."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Стіна",
          "text": "Напиши mauer у чат. Agent будує стіну з десяти блоків. Порахуй блоки."
        },
        {
          "kind": "nochEiner",
          "title": "Довше й інакше",
          "text": "Зміни число з 10 на 20. Візьми інший вид блоку, наприклад Дерево. Спробуй."
        },
        {
          "kind": "remix",
          "title": "Дві стіни",
          "text": "Побудуй дві стіни з проміжком між ними. Покажи це своєму партнеру або партнерці."
        }
      ],
      "tipSolution": "Напиши for index in range(20): у рядку циклу. Два рядки під ним лишаються з відступом. Для дерева візьми agent.set_item(PLANKS_OAK, 64, 1). Порахуй: один цикл, два рядки всередині.",
      "exercises": [
        {
          "prompt": "Agent стоїть внизу посередині. Його ніс дивиться вгору. Програма: 3 кроки вперед."
        },
        {
          "prompt": "Agent підходить до тебе і бере Бруківку. Потім цикл повторює два рядки. Відступ належить до рядка."
        }
      ],
      "quiz": [
        {
          "q": "Що економить цикл?",
          "answers": [
            {
              "text": "Багато однакових рядків",
              "correct": true
            },
            {
              "text": "Блоки в рюкзаку",
              "correct": false
            },
            {
              "text": "Місце у світі",
              "correct": false
            }
          ]
        },
        {
          "q": "Скільки разів виконується цикл з range(10)?",
          "answers": [
            {
              "text": "Десять разів",
              "correct": true
            },
            {
              "text": "Дев'ять разів",
              "correct": false
            },
            {
              "text": "Одинадцять разів",
              "correct": false
            }
          ]
        },
        {
          "q": "З якого числа комп'ютер починає рахувати?",
          "answers": [
            {
              "text": "З 0",
              "correct": true
            },
            {
              "text": "З 1",
              "correct": false
            },
            {
              "text": "З 10",
              "correct": false
            }
          ]
        },
        {
          "q": "Що стається при range(0)?",
          "answers": [
            {
              "text": "Нічого. Цикл не виконується жодного разу",
              "correct": true
            },
            {
              "text": "Цикл виконується один раз",
              "correct": false
            },
            {
              "text": "Agent повідомляє про помилку",
              "correct": false
            }
          ]
        }
      ]
    },
    "s05": {
      "title": "Цикл усередині циклу",
      "storyShort": "Цикл може стояти всередині іншого циклу. Внутрішній цикл будує ряд. Зовнішній цикл повторює цей ряд. Так із ряду виходить стіна.",
      "bridge": {
        "game": "Ти пишеш wand у чат. Agent будує стіну з трьох рядів.",
        "code": "Один цикл сидить усередині іншого. Всередині — ряд, зовні — поверхи."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Стіна",
          "text": "Напиши wand у чат. Agent будує стіну: 6 блоків завширшки, 3 заввишки."
        },
        {
          "kind": "nochEiner",
          "title": "Більше",
          "text": "Зміни стіну на 8 блоків завширшки і 4 заввишки. Які два числа треба змінити?"
        },
        {
          "kind": "remix",
          "title": "Зубець",
          "text": "Зроби верхній ряд коротшим. Як тепер виглядає стіна? Покажи це своєму партнеру або партнерці."
        }
      ],
      "tipSolution": "Напиши for index in range(4): у зовнішній цикл. Це висота. Напиши for index2 in range(8): у внутрішній цикл. Це ширина. Після двох поворотів іде один крок уперед. Так Agent знову стоїть над рядом. Порахуй: два цикли, один усередині іншого.",
      "exercises": [
        {
          "prompt": "Agent стоїть унизу ліворуч. Його ніс дивиться вгору. Програма: 2 кроки вперед, поворот ліворуч, поворот ліворуч, 1 крок уперед."
        },
        {
          "prompt": "Agent уже має із собою бруківку. Тепер будуємо стіну: зовні — поверхи, всередині — ряд. Поворотів і кроку після них тут бракує. Зважай на відступ."
        }
      ],
      "quiz": [
        {
          "q": "Стіна має 6 блоків завширшки і 3 заввишки. Скільки це блоків?",
          "answers": [
            {
              "text": "18 блоків",
              "correct": true
            },
            {
              "text": "9 блоків",
              "correct": false
            },
            {
              "text": "24 блоки",
              "correct": false
            }
          ]
        },
        {
          "q": "Що робить внутрішній цикл?",
          "answers": [
            {
              "text": "Він будує один ряд",
              "correct": true
            },
            {
              "text": "Він піднімається на один поверх",
              "correct": false
            },
            {
              "text": "Він розвертає Agent",
              "correct": false
            }
          ]
        },
        {
          "q": "Чому Agent двічі повертає ліворуч?",
          "answers": [
            {
              "text": "Щоб дивитися назад і будувати наступний ряд",
              "correct": true
            },
            {
              "text": "Щоб він рухався швидше",
              "correct": false
            },
            {
              "text": "Щоб він міг покласти блок",
              "correct": false
            }
          ]
        },
        {
          "q": "Який цикл першим проходить повністю?",
          "answers": [
            {
              "text": "Внутрішній. Він спершу будує весь ряд",
              "correct": true
            },
            {
              "text": "Зовнішній. Він спершу йде аж угору",
              "correct": false
            },
            {
              "text": "Обидва працюють одночасно",
              "correct": false
            }
          ]
        }
      ]
    },
    "s06": {
      "title": "Дім",
      "storyShort": "Дім має чотири стіни. Ти не копіюєш стіну чотири рази. Ти ставиш цикл зовні. Після кожної сторони Agent повертається.",
      "bridge": {
        "game": "Ти пишеш haus у чат. Agent будує кільце з чотирьох сторін.",
        "code": "Зовнішній цикл виконується чотири рази. Після кожної сторони Agent повертає за кут."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Кільце",
          "text": "Напиши haus у чат. Agent будує кільце: 5 блоків на кожну сторону."
        },
        {
          "kind": "nochEiner",
          "title": "Вище",
          "text": "Кільце має бути 3 блоки у висоту. Для цього тобі потрібен третій цикл."
        },
        {
          // Handkorrektur 2026-09-04 (Welle C): Praeposition korrigiert (на, nicht в).
          "kind": "remix",
          "title": "Двері",
          "text": "Залиш на одній стороні отвір як двері. Покажи свій дім своєму партнеру або партнерці."
        }
      ],
      // Handkorrektur 2026-09-04 (Final Review): entspricht de.js — agent.move(UP, 1) steht in
      // der dritten Schleife, direkt nach dem Ring, nicht danach.
      "tipSolution": "Напиши for index3 in range(3): найдалі зовні. Усе кільце стоїть із відступом усередині. agent.move(UP, 1) теж стоїть усередині, одразу після кільця. Перелічи: три цикли, один в одному.",
      "exercises": [
        {
          "prompt": "Agent стоїть знизу в центрі. Його ніс дивиться вгору. Програма: 2 кроки вперед, повернути ліворуч. Потім ще раз: 2 кроки вперед, повернути ліворуч. Наостанок 2 кроки вперед."
        },
        {
          "prompt": "Agent будує кільце. Усередині — одна сторона, зовні — чотири сторони. Поворот належить до зовнішнього циклу."
        }
      ],
      "quiz": [
        {
          "q": "Скільки сторін будує range(4)?",
          "answers": [
            {
              "text": "Чотири",
              "correct": true
            },
            {
              "text": "Три",
              "correct": false
            },
            {
              "text": "П'ять",
              "correct": false
            }
          ]
        },
        {
          "q": "Де стоїть agent.turn(LEFT_TURN)?",
          "answers": [
            {
              "text": "У зовнішньому циклі, після внутрішнього",
              "correct": true
            },
            {
              "text": "У внутрішньому циклі, при кожному блоці",
              "correct": false
            },
            {
              "text": "Найвище, перед обома циклами",
              "correct": false
            }
          ]
        },
        {
          "q": "Чому Agent повертається лише один раз на стіну?",
          "answers": [
            {
              "text": "Бо кут — це поворот на чверть",
              "correct": true
            },
            {
              "text": "Бо інакше він стане надто повільним",
              "correct": false
            },
            {
              "text": "Бо інакше в нього не залишиться блоків",
              "correct": false
            }
          ]
        },
        {
          "q": "Кільце має 4 сторони по 5 блоків кожна. Скільки це блоків?",
          "answers": [
            {
              "text": "20 блоків",
              "correct": true
            },
            {
              "text": "16 блоків",
              "correct": false
            },
            {
              "text": "25 блоків",
              "correct": false
            }
          ]
        }
      ],
      "bossCheck": {
        "title": "Бос-перевірка: Камінь",
        "subtitle": "Паркан",
        "task": "Побудуй паркан навколо себе. Кільце має 8 блоків на кожну сторону. Що економить цикл? Скільки було б команд без циклу?"
      }
    },
    "s07": {
      "title": "Числа з іменем",
      "storyShort": "Змінна — це число з іменем. Ти задаєш його один раз, а цикл використовує його всюди. Зміни лише число, а не всю програму.",
      "bridge": {
        "game": "Ти пишеш bruecke. Agent будує міст через річку.",
        "code": "laenge стоїть один раз угорі. Цикл використовує це число."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Міст",
          "text": "Стань на золотий блок у місці A. Напиши bruecke. Перейди через міст. Угорі перемкнись на Python. Знайди рядок laenge = 5."
        },
        {
          "kind": "nochEiner",
          "title": "Місце B",
          "text": "Іди до золотого блоку в місці B. Річка завширшки 8. Зміни лише одне число. Напиши bruecke."
        },
        {
          "kind": "remix",
          "title": "Твій міст",
          "text": "Побудуй міст з іншого блоку. Або зроби його завширшки два блоки. Покажи це своєму партнеру або партнерці."
        }
      ],
      "tipSolution": "Постав laenge = 8. Зміни лише цей один рядок. Тоді range(laenge) побудує вісім пар move-place.",
      "exercises": [
        {
          "prompt": "Зістав кожен блок з його рядком у Python."
        },
        {
          "prompt": "Річка в місці B завширшки 8 блоків. Яке число має бути в пропуску?"
        }
      ],
      "quiz": [
        {
          "q": "Що таке laenge?",
          "answers": [
            {
              "text": "Число з іменем",
              "correct": true
            },
            {
              "text": "Чарівне слово",
              "correct": false
            },
            {
              "text": "Блок",
              "correct": false
            }
          ]
        },
        {
          "q": "Міст має бути завдовжки 8. Що ти зміниш?",
          "answers": [
            {
              "text": "Лише рядок laenge = 5",
              "correct": true
            },
            {
              "text": "Кожен рядок, де є 5",
              "correct": false
            },
            {
              "text": "Чарівне слово",
              "correct": false
            }
          ]
        },
        {
          "q": "laenge = 5. Скільки разів виконається range(laenge)?",
          "answers": [
            {
              "text": "5 разів",
              "correct": true
            },
            {
              "text": "4 рази",
              "correct": false
            },
            {
              "text": "6 разів",
              "correct": false
            }
          ]
        },
        {
          "q": "Де ти бачиш свою програму як Python?",
          "answers": [
            {
              "text": "За допомогою перемикача вгорі в редакторі",
              "correct": true
            },
            {
              "text": "У чаті",
              "correct": false
            },
            {
              "text": "У світі",
              "correct": false
            }
          ]
        }
      ]
    },
    "s08": {
      "title": "Де я?",
      "storyShort": "Кожен блок має три координати: x, y і z. pos рахує від твоїх ніг, y — це висота. fill заповнює цілий паралелепіпед однією командою.",
      "bridge": {
        "game": "Ти зчитуєш x, y, z. Ти пишеш plattform. Платформа лежить над ущелиною.",
        "code": "fill заповнює все між двома кутами. pos рахує від твоїх ніг."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Платформа",
          "text": "Увімкни координати. Стань на золотий блок біля ущелини. Зчитай x, y, z і запиши їх. Напиши plattform. Пройди по платформі. Перемкнись на Python: знайди два кути."
        },
        {
          "kind": "nochEiner",
          "title": "Ширше",
          "text": "Зроби платформу вдвічі ширшою. Ширше тут означає: у напрямку x. Яке число ти зміниш?"
        },
        {
          "kind": "remix",
          "title": "Дах",
          "text": "Побудуй дах над платформою. Підказка: y = 2. Покажи це своєму партнеру або своїй партнерці."
        }
      ],
      "tipSolution": "Другий кут стає pos(9, -1, 7) замість pos(4, -1, 7). Від 0 до 9 — це десять блоків. Більшим стає лише число x.",
      "exercises": [
        {
          "prompt": "Три блоки fill, три рядки. Зверни увагу на y і на блок."
        },
        {
          "prompt": "Платформа перетворилася на товсту стіну. Який рядок неправильний?",
          "explain": "Другий кут має y = 1. fill заповнює від y = -1 до y = 1. Це три блоки заввишки. Платформі потрібно в обох кутах y = -1."
        }
      ],
      "quiz": [
        {
          "q": "Що означає y?",
          "answers": [
            {
              "text": "Висоту",
              "correct": true
            },
            {
              "text": "Ліворуч і праворуч",
              "correct": false
            },
            {
              "text": "Спереду і ззаду",
              "correct": false
            }
          ]
        },
        {
          "q": "Де знаходиться pos(0, -1, 1)?",
          "answers": [
            {
              "text": "На один блок під тобою, на один блок далі в напрямку z",
              "correct": true
            },
            {
              "text": "Над тобою",
              "correct": false
            },
            {
              "text": "Далеко звідси",
              "correct": false
            }
          ]
        },
        {
          "q": "Що робить fill?",
          "answers": [
            {
              "text": "Заповнює все між двома кутами",
              "correct": true
            },
            {
              "text": "Ставить один блок",
              "correct": false
            },
            {
              // Handkorrektur 2026-09-16 (Plan 3 Final-Review-Fix): "Agent" lateinisch (AGENT_CANON), der Neulauf s08 schrieb "Агента".
              "text": "Рухає Agent",
              "correct": false
            }
          ]
        },
        {
          "q": "Показник у грі показує x, y, z. Що це таке?",
          "answers": [
            {
              "text": "Координати світу, однакові для всіх",
              "correct": true
            },
            {
              "text": "Відстані від тебе",
              "correct": false
            },
            {
              "text": "Випадкові числа",
              "correct": false
            }
          ]
        }
      ]
    },
    "s09": {
      "title": "Рахуємо",
      "storyShort": "Цикл рахує сам: index — це 0, потім 1, потім 2. Візьми index як висоту. Так з одного рядка виходять цілі сходи.",
      "bridge": {
        "game": "Ти пишеш treppe. Сходи ростуть сходинка за сходинкою аж до плато.",
        "code": "index рахує 0, 1, 2 … Цикл бере index як висоту."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Сходи",
          "text": "Стань на золотий блок перед скелею. Напиши treppe. Піднімись сходами. Перемкнись на Python: де index стоїть двічі?"
        },
        {
          "kind": "nochEiner",
          "title": "Ширше",
          "text": "Зроби кожну сходинку завширшки 5. Зміни останнє число в pos — число z."
        },
        {
          "kind": "remix",
          "title": "Твої сходи",
          "text": "Побудуй сходи з дубової деревини. Або побудуй їх униз, у прірву. Покажи це своєму партнеру або партнерці."
        }
      ],
      "tipSolution": "Сходинка index іде від pos(index, 0, 1) до pos(index, index, 3). stufen = 6 дає шість сходинок.",
      "exercises": [
        {
          "prompt": "Скеля має висоту 6. Кожна сходинка така висока, як її лічильник плюс 1."
        },
        {
          "prompt": "Сходи перетворилися на стіну. Який рядок неправильний?",
          "explain": "У pos стоїть stufen замість index. Тоді кожна сходинка має висоту 7. Виходить стіна, а не сходи."
        }
      ],
      "quiz": [
        {
          "q": "Що таке index?",
          "answers": [
            {
              "text": "Лічильник циклу",
              "correct": true
            },
            {
              "text": "Висота скелі",
              "correct": false
            },
            {
              "text": "Чарівне слово",
              "correct": false
            }
          ]
        },
        {
          "q": "range(6): які значення отримує index?",
          "answers": [
            {
              "text": "від 0 до 5",
              "correct": true
            },
            {
              "text": "від 1 до 6",
              "correct": false
            },
            {
              "text": "від 0 до 6",
              "correct": false
            }
          ]
        },
        {
          "q": "Чому кожна сходинка стає вищою?",
          "answers": [
            {
              "text": "index більшає з кожним проходом",
              "correct": true
            },
            {
              "text": "fill рахує сам",
              "correct": false
            },
            {
              "text": "stufen більшає",
              "correct": false
            }
          ]
        },
        {
          "q": "Скеля має висоту 9. Що ти поставиш?",
          "answers": [
            {
              "text": "stufen = 9",
              "correct": true
            },
            {
              "text": "index = 9",
              "correct": false
            },
            {
              "text": "range(8)",
              "correct": false
            }
          ]
        }
      ],
      "bossCheck": {
        "title": "Бос-перевірка: Залізо",
        "subtitle": "Друга скеля",
        "task": "Стань на золотий блок перед другою скелею. Зчитай y внизу. Піднімись драбиною і зчитай y вгорі. Постав stufen. Побудуй сходи. Напиши три речення: звідки взялося твоє число? Що робить index? Що ти зміниш при вищій скелі?"
      }
    }
  }
};
