// AUTO-GENERATED by scripts/translate.mjs — NICHT von Hand bearbeiten.
// Manuell korrigiert 03.09.2026 (Review Task 8): etappen.enderdrache.name (Дракон Едему -> Дракон Енду) + glossary.*.term (DE-Reste -> UK) — bei Regeneration mit --force erneut pruefen.
// Manuell ergaenzt 03.09.2026 (Plan 2 Task 3): ui.bossCheckHeading/Hint + etappen.*.badge — de.js
// ist gewachsen, die volle Neuuebersetzung folgt erst in Plan 2 Task 9 (`translate.mjs --lang all`
// nach den neuen Stationen); bis dahin haelt dieser Handeintrag i18n-complete.test.js gruen.
// Source: src/i18n/de.js   sourceHash: 8edb57a86d18
// Language: uk   model: claude-opus-5   generated: 2026-09-03T04:39:26.352Z
// Stuetz-Ebene: Deutsch bleibt daneben sichtbar. Bei Aenderung an de.js neu erzeugen.

export default {
  "ui": {
    "appTitle": "Світ коду",
    "tagline": "Agent розуміє тільки код.",
    "home": "Огляд",
    "station": "Станція {n}",
    "ds": "Подвійний урок {n}",
    "support": "Твоєю мовою",
    "supportShow": "Показати допомогу твоєю мовою",
    "supportHide": "Сховати допомогу",
    "storyHeading": "Історія",
    "conceptHeading": "Ідея",
    "bridgeGame": "У грі",
    "bridgeCode": "У коді",
    "blocksLabel": "Так це виглядає у блоках",
    "pythonLabel": "Так це виглядає у Python",
    "tasksHeading": "Твої завдання у грі",
    "taskAuftrag": "Завдання",
    "taskNochEiner": "Ще одне",
    "taskRemix": "Ремікс",
    "tipsHeading": "Драбинка підказок",
    "tipStep": "Підказка {n}",
    "tipSolution": "Розв'язок",
    "tipRemixNote": "Якщо береш готовий розв'язок: після цього зміни одну річ. Це обов'язково.",
    "check": "Перевірка",
    "checkHeading": "Зрозумів?",
    "predictPrompt": "Де стоїть Agent у кінці? Натисни на клітинку.",
    "predictRight": "Правильно! Agent стоїть саме там.",
    "predictWrong": "Ще ні. Читай програму згори вниз. Куди дивиться ніс?",
    "parsonsPrompt": "Постав рядки у правильному порядку.",
    "parsonsUp": "вгору",
    "parsonsDown": "вниз",
    "parsonsCheck": "Перевірити",
    "parsonsRight": "Правильно! Це і є порядок.",
    "parsonsWrong": "Ще ні. Що Agent має зробити першим?",
    "spielstandHeading": "Твій прогрес",
    "spielstandPrompt": "Що ти вже вмієш? Напиши три короткі речення.",
    "spielstandSave": "Зберегти",
    "spielstandSaved": "Збережено. Тільки на цьому пристрої.",
    "progress": "Ти відвідав {done} із {total} станцій.",
    "next": "Далі",
    "prev": "Назад",
    "play": "Прочитати вголос",
    "langLabel": "Мова",
    "footer": "Навчальний модуль від Dirk Schulenburg · CC BY 4.0 · Не є офіційним продуктом Minecraft.",
    "bossCheckHeading": "Бос-перевірка",
    "bossCheckHint": "Виконай завдання без драбинки підказок. Здай Share-Link і напиши три короткі речення."
  },
  "glossary": {
    "befehl": {
      "term": "Команда",
      "short": "Один рядок коду. Agent робить саме це."
    },
    "programm": {
      "term": "Програма",
      "short": "Багато команд, згори вниз."
    },
    "sequenz": {
      "term": "Послідовність",
      "short": "Порядок команд."
    },
    "agent": {
      "term": "Agent",
      "short": "Робот у Minecraft. Він розуміє тільки код."
    },
    "zauberwort": {
      "term": "Чарівне слово",
      "short": "Слово в чаті. Воно запускає твою програму."
    },
    "python": {
      "term": "Python",
      "short": "Мова програмування. Твій код як текст."
    },
    "bloecke": {
      "term": "Блоки",
      "short": "Твій код як блоки, які можна перетягувати."
    },
    "fehler": {
      "term": "Помилка",
      "short": "Agent зрозумів тебе неправильно. Ти можеш це виправити."
    }
  },
  "etappen": {
    "holz": {
      "name": "Дерево",
      "badge": {
        "name": "Дерево",
        "description": "Ти склав усі перевірки етапу Дерево і здав бос-перевірку."
      }
    },
    "stein": {
      "name": "Камінь",
      "badge": {
        "name": "Камінь",
        "description": "Ти склав усі перевірки етапу Камінь і здав бос-перевірку."
      }
    },
    "eisen": {
      "name": "Залізо",
      "badge": {
        "name": "Залізо",
        "description": "Ти склав усі перевірки етапу Залізо і здав бос-перевірку."
      }
    },
    "gold": {
      "name": "Золото",
      "badge": {
        "name": "Золото",
        "description": "Ти склав усі перевірки етапу Золото і здав бос-перевірку."
      }
    },
    "diamant": {
      "name": "Алмаз",
      "badge": {
        "name": "Алмаз",
        "description": "Ти склав усі перевірки етапу Алмаз і здав бос-перевірку."
      }
    },
    "netherite": {
      "name": "Незерит",
      "badge": {
        "name": "Незерит",
        "description": "Ти склав усі перевірки етапу Незерит і здав бос-перевірку."
      }
    },
    "enderdrache": {
      "name": "Дракон Енду",
      "badge": {
        "name": "Дракон Енду",
        "description": "Ти склав усі перевірки етапу Дракон Енду і здав бос-перевірку."
      }
    }
  },
  "stations": {
    "s02": {
      "title": "Порядок має значення",
      "storyShort": "Agent виконує команди саме в тому порядку, у якому ти їх пишеш. Спочатку йти, потім повернути — це не те саме, що спочатку повернути, потім йти.",
      "bridge": {
        "game": "Agent іде крок за кроком і кладе за собою блоки.",
        "code": "Програма — це список команд. Комп'ютер виконує їх зверху вниз."
      },
      "tasks": [
        {
          "kind": "auftrag",
          "title": "Шлях",
          "text": "Напиши чарівне слово weg у чат. Agent покладе три блоки. Придивись уважно: де кут?"
        },
        {
          "kind": "nochEiner",
          "title": "Довше",
          "text": "Зміни програму. Agent має покласти п'ять блоків, потім повернути за кут, потім ще два."
        },
        {
          "kind": "remix",
          "title": "Твій візерунок",
          "text": "Побудуй власний візерунок із блоків. Наприклад, літеру Z або U. Покажи його своєму партнеру або партнерці."
        }
      ],
      "tipSolution": "Для п'яти блоків: напиши agent.move(FORWARD, 1) і agent.place(BACK) п'ять разів. Потім agent.turn(LEFT_TURN). Потім ще двічі move і place.",
      "exercises": [
        {
          "prompt": "Agent стоїть унизу посередині. Його ніс дивиться вгору. Програма: 2 кроки вперед, повернути ліворуч, 1 крок вперед."
        },
        {
          "prompt": "Agent має підійти до тебе: пройти два кроки, повернути ліворуч і пройти ще один крок."
        }
      ],
      "quiz": [
        {
          "q": "Agent має пройти 3 кроки, а потім повернути ліворуч. Який порядок правильний?",
          "answers": [
            {
              "text": "Спочатку agent.move(FORWARD, 3), потім agent.turn(LEFT_TURN)",
              "correct": true
            },
            {
              "text": "Спочатку agent.turn(LEFT_TURN), потім agent.move(FORWARD, 3)",
              "correct": false
            },
            {
              "text": "Порядок не має значення",
              "correct": false
            }
          ]
        },
        {
          "q": "Ти пишеш agent.move(FORWARD, 3) двічі одне під одним. Що робить Agent?",
          "answers": [
            {
              "text": "Він іде 6 кроків",
              "correct": true
            },
            {
              "text": "Він іде 3 кроки",
              "correct": false
            },
            {
              "text": "Він показує помилку",
              "correct": false
            }
          ]
        },
        {
          "q": "Коли стартує твоя програма?",
          "answers": [
            {
              "text": "Коли ти пишеш чарівне слово у чат",
              "correct": true
            },
            {
              "text": "Одразу, коли ти відкриваєш Code Builder",
              "correct": false
            },
            {
              "text": "Коли ти клікаєш на Agent",
              "correct": false
            }
          ]
        },
        {
          "q": "Agent розуміє …",
          "answers": [
            {
              "text": "тільки код",
              "correct": true
            },
            {
              "text": "німецьку та англійську",
              "correct": false
            },
            {
              "text": "будь-яку мову",
              "correct": false
            }
          ]
        }
      ]
    }
  }
};
